//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTO_GR
    {
        public int AUTO_GR_ID { get; set; }
        public string PO_NUMBER { get; set; }
        public Nullable<System.DateTime> PO_DATE { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<bool> IS_POSTED { get; set; }
    }
}
