//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTO_GR_DETAIL
    {
        public int AUTO_GR_DETAIL_ID { get; set; }
        public int AUTO_GR_ID { get; set; }
        public Nullable<int> LINE_ITEM { get; set; }
        public Nullable<decimal> QTY_ITEM { get; set; }
    }
}
