//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFM_IDLE_REPORT_DATA
    {
        public int ID { get; set; }
        public string POLICE_NUMBER { get; set; }
        public string MANUFACTURER { get; set; }
        public string MODEL { get; set; }
        public string SERIES { get; set; }
        public string BODY_TYPE { get; set; }
        public string COLOR { get; set; }
        public string GROUP_LEVEL { get; set; }
        public Nullable<System.DateTime> START_CONTRACT { get; set; }
        public Nullable<System.DateTime> END_CONTRACT { get; set; }
        public string SUPPLY_METHOD { get; set; }
        public string VENDOR { get; set; }
        public string COST_CENTER { get; set; }
        public string TRANSMISSION { get; set; }
        public string FUEL_TYPE { get; set; }
        public Nullable<System.DateTime> START_IDLE { get; set; }
        public Nullable<System.DateTime> END_IDLE { get; set; }
        public Nullable<decimal> MONTHLY_INSTALLMENT { get; set; }
        public Nullable<int> REPORT_MONTH { get; set; }
        public Nullable<int> REPORT_YEAR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
    }
}
