//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class cost_center
    {
        public int cc_id { get; set; }
        public string cost_center1 { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public string modified_by { get; set; }
        public string txt_hcc_name { get; set; }
        public string function { get; set; }
        public string txt_hcc_group { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<bool> is_active { get; set; }
    }
}
