//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public long table_emp_id { get; set; }
        public string employee_id { get; set; }
        public string employee_name { get; set; }
        public string title_name { get; set; }
        public string cost_center { get; set; }
        public string city { get; set; }
        public string office_location { get; set; }
        public string division { get; set; }
        public string directorate { get; set; }
        public string company { get; set; }
        public Nullable<int> grup_level { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> flag { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public string email { get; set; }
        public string role { get; set; }
        public string acountname { get; set; }
    }
}
