//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUEL_REPORT_DATA
    {
        public int ID { get; set; }
        public string POLICE_NUMBER { get; set; }
        public Nullable<int> LITER { get; set; }
        public Nullable<decimal> ODOMETER { get; set; }
        public Nullable<decimal> COST { get; set; }
        public string FUEL_TYPE { get; set; }
        public string COST_CENTER { get; set; }
        public string FUNCTION { get; set; }
        public string MANUFACTURER { get; set; }
        public string MODEL { get; set; }
        public string SERIES { get; set; }
        public string BODY_TYPE { get; set; }
        public string VEHICLE_TYPE { get; set; }
        public string VEHICLE_USAGE { get; set; }
        public string LOCATION { get; set; }
        public Nullable<int> REPORT_MONTH { get; set; }
        public Nullable<int> REPORT_YEAR { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
    }
}
