//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCTION_CHANGE
    {
        public long FUNCTION_CHANGE_ID { get; set; }
        public string EMPLOYEE_ID { get; set; }
        public string FORMAL_NAME { get; set; }
        public string COST_CENTER { get; set; }
        public string FUNCTION_OLD { get; set; }
        public string FUNCTION_NEW { get; set; }
        public Nullable<System.DateTime> CHANGE_DATE { get; set; }
        public Nullable<System.DateTime> DATE_SEND { get; set; }
    }
}
