//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPI_REPORT_DATA
    {
        public int ID { get; set; }
        public string FORM_TYPE { get; set; }
        public string EMPLOYEE_ID { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_DATE { get; set; }
        public string REASON { get; set; }
        public string ADDRESS { get; set; }
        public string PREVIOUS_BASE_TOWN { get; set; }
        public string NEW_BASE_TOWN { get; set; }
        public string VEHICLE_USAGE { get; set; }
        public Nullable<int> VEHICLE_GROUP_LEVEL { get; set; }
        public string VEHICLE_MODEL { get; set; }
        public string COLOR { get; set; }
        public string POLICE_NUMBER { get; set; }
        public Nullable<System.DateTime> TEMPORARY_REQUEST_DATE { get; set; }
        public Nullable<System.DateTime> EE_RECEIVED_TEMP { get; set; }
        public Nullable<System.DateTime> SEND_TO_EMP_DATE { get; set; }
        public Nullable<System.DateTime> SEND_BACK_TO_HR { get; set; }
        public Nullable<System.DateTime> SEND_TO_FLEET_DATE { get; set; }
        public Nullable<System.DateTime> SEND_TO_EMPLOYEE_BENEFIT_DATE { get; set; }
        public Nullable<System.DateTime> SEND_SURAT_KUASA { get; set; }
        public Nullable<System.DateTime> SEND_AGREEMENT { get; set; }
        public string REMARK { get; set; }
        public Nullable<int> REPORT_MONTH { get; set; }
        public Nullable<int> REPORT_YEAR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public Nullable<long> TRA_ID { get; set; }
    }
}
