//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATION_CHANGE
    {
        public long LOCATION_CHANGE_ID { get; set; }
        public string EMPLOYEE_ID { get; set; }
        public string FORMAL_NAME { get; set; }
        public string BASETOWN_OLD { get; set; }
        public string BASETOWN_NEW { get; set; }
        public string ADDRESS_OLD { get; set; }
        public string ADDRESS_NEW { get; set; }
        public string CITY_OLD { get; set; }
        public string CITY_NEW { get; set; }
        public Nullable<System.DateTime> CHANGE_DATE { get; set; }
        public Nullable<System.DateTime> DATE_SEND { get; set; }
    }
}
