//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_EMPLOYEE
    {
        public MST_EMPLOYEE()
        {
            this.MST_DELEGATION = new HashSet<MST_DELEGATION>();
            this.MST_DELEGATION1 = new HashSet<MST_DELEGATION>();
            this.MST_EPAF = new HashSet<MST_EPAF>();
            this.MST_FLEET = new HashSet<MST_FLEET>();
            this.MST_FUEL_ODOMETER = new HashSet<MST_FUEL_ODOMETER>();
            this.TRA_CAF = new HashSet<TRA_CAF>();
            this.TRA_CCF = new HashSet<TRA_CCF>();
            this.TRA_CCF1 = new HashSet<TRA_CCF>();
            this.TRA_CRF = new HashSet<TRA_CRF>();
            this.TRA_CSF = new HashSet<TRA_CSF>();
            this.TRA_CTF = new HashSet<TRA_CTF>();
            this.TRA_TEMPORARY = new HashSet<TRA_TEMPORARY>();
            this.PO_REPORT_DATA = new HashSet<PO_REPORT_DATA>();
        }
    
        public string EMPLOYEE_ID { get; set; }
        public string FORMAL_NAME { get; set; }
        public string POSITION_TITLE { get; set; }
        public string DIVISON { get; set; }
        public string DIRECTORATE { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string BASETOWN { get; set; }
        public string COMPANY { get; set; }
        public string COST_CENTER { get; set; }
        public Nullable<int> GROUP_LEVEL { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public Nullable<int> FLEX_POINT { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public bool IS_ACTIVE { get; set; }
    
        public virtual ICollection<MST_DELEGATION> MST_DELEGATION { get; set; }
        public virtual ICollection<MST_DELEGATION> MST_DELEGATION1 { get; set; }
        public virtual ICollection<MST_EPAF> MST_EPAF { get; set; }
        public virtual ICollection<MST_FLEET> MST_FLEET { get; set; }
        public virtual ICollection<MST_FUEL_ODOMETER> MST_FUEL_ODOMETER { get; set; }
        public virtual ICollection<TRA_CAF> TRA_CAF { get; set; }
        public virtual ICollection<TRA_CCF> TRA_CCF { get; set; }
        public virtual ICollection<TRA_CCF> TRA_CCF1 { get; set; }
        public virtual ICollection<TRA_CRF> TRA_CRF { get; set; }
        public virtual ICollection<TRA_CSF> TRA_CSF { get; set; }
        public virtual ICollection<TRA_CTF> TRA_CTF { get; set; }
        public virtual ICollection<TRA_TEMPORARY> TRA_TEMPORARY { get; set; }
        public virtual ICollection<PO_REPORT_DATA> PO_REPORT_DATA { get; set; }
    }
}
