//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_COMPLAINT_CATEGORY
    {
        public MST_COMPLAINT_CATEGORY()
        {
            this.TRA_CCF = new HashSet<TRA_CCF>();
        }
    
        public int MST_COMPLAINT_CATEGORY_ID { get; set; }
        public string CATEGORY_NAME { get; set; }
        public string ROLE_TYPE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public bool IS_ACTIVE { get; set; }
    
        public virtual ICollection<TRA_CCF> TRA_CCF { get; set; }
    }
}
