//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_FUEL_ODOMETER
    {
        public long MST_FUEL_ODOMETER_ID { get; set; }
        public string POLICE_NUMBER { get; set; }
        public string EMPLOYEE_ID { get; set; }
        public string COST_CENTER { get; set; }
        public Nullable<decimal> FUEL_AMOUNT { get; set; }
        public Nullable<decimal> LAST_KM { get; set; }
        public Nullable<decimal> COST { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public bool IS_ACTIVE { get; set; }
    }
}
