//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_REASON
    {
        public MST_REASON()
        {
            this.TRA_CSF = new HashSet<TRA_CSF>();
            this.TRA_CTF_EXTEND = new HashSet<TRA_CTF_EXTEND>();
            this.TRA_CTF = new HashSet<TRA_CTF>();
            this.TRA_TEMPORARY = new HashSet<TRA_TEMPORARY>();
        }
    
        public int MST_REASON_ID { get; set; }
        public int DOCUMENT_TYPE { get; set; }
        public string REASON { get; set; }
        public bool IS_PENALTY { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string VEHICLE_TYPE { get; set; }
    
        public virtual MST_DOCUMENT_TYPE MST_DOCUMENT_TYPE { get; set; }
        public virtual ICollection<TRA_CSF> TRA_CSF { get; set; }
        public virtual ICollection<TRA_CTF_EXTEND> TRA_CTF_EXTEND { get; set; }
        public virtual ICollection<TRA_CTF> TRA_CTF { get; set; }
        public virtual ICollection<TRA_TEMPORARY> TRA_TEMPORARY { get; set; }
    }
}
