//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_GS
    {
        public int MST_GS_ID { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public string VEHICLE_USAGE { get; set; }
        public string POLICE_NUMBER { get; set; }
        public Nullable<int> GROUP_LEVEL { get; set; }
        public string LOCATION { get; set; }
        public Nullable<System.DateTime> GS_REQUEST_DATE { get; set; }
        public Nullable<System.DateTime> GS_FULLFILLMENT_DATE { get; set; }
        public string GS_UNIT_TYPE { get; set; }
        public string GS_POLICE_NUMBER { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string REMARK { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public bool IS_ACTIVE { get; set; }
    }
}
