//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_LOCATION_MAPPING
    {
        public int MST_LOCATION_MAPPING_ID { get; set; }
        public string LOCATION { get; set; }
        public string ADDRESS { get; set; }
        public string REGION { get; set; }
        public string ZONE_SALES { get; set; }
        public string ZONE_PRICE_LIST { get; set; }
        public System.DateTime VALIDITY_FROM { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public bool IS_ACTIVE { get; set; }
    }
}
