//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_MODUL
    {
        public MST_MODUL()
        {
            this.MST_MODUL1 = new HashSet<MST_MODUL>();
            this.TRA_CHANGES_HISTORY = new HashSet<TRA_CHANGES_HISTORY>();
            this.TRA_WORKFLOW_HISTORY = new HashSet<TRA_WORKFLOW_HISTORY>();
            this.MST_SYSACCESS = new HashSet<MST_SYSACCESS>();
        }
    
        public int MST_MODUL_ID { get; set; }
        public string MODUL_NAME { get; set; }
        public string MODUL_URL { get; set; }
        public string MENU_NAME { get; set; }
        public Nullable<int> PARENT_MODUL_ID { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public bool IS_ACTIVE { get; set; }
    
        public virtual ICollection<MST_MODUL> MST_MODUL1 { get; set; }
        public virtual MST_MODUL MST_MODUL2 { get; set; }
        public virtual ICollection<TRA_CHANGES_HISTORY> TRA_CHANGES_HISTORY { get; set; }
        public virtual ICollection<TRA_WORKFLOW_HISTORY> TRA_WORKFLOW_HISTORY { get; set; }
        public virtual ICollection<MST_SYSACCESS> MST_SYSACCESS { get; set; }
    }
}
