//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_SYSACCESS
    {
        public int MST_SYSACCESS_ID { get; set; }
        public string ROLE_NAME { get; set; }
        public string ROLE_NAME_ALIAS { get; set; }
        public int MODUL_ID { get; set; }
        public Nullable<bool> READ_ACCESS { get; set; }
        public Nullable<bool> WRITE_ACCESSS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public bool IS_ACTIVE { get; set; }
        public Nullable<bool> UPLOAD_ACCESS { get; set; }
    
        public virtual MST_MODUL MST_MODUL { get; set; }
    }
}
