//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_PENALTY_LOGIC
    {
        public int MST_PENALTY_LOGIC_ID { get; set; }
        public int YEAR { get; set; }
        public string PENALTY_LOGIC { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public bool IS_ACTIVE { get; set; }
        public Nullable<int> VENDOR { get; set; }
        public string VEHICLE_TYPE { get; set; }
    
        public virtual MST_VENDOR MST_VENDOR { get; set; }
    }
}
