//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_FLEET
    {
        public long MST_FLEET_ID { get; set; }
        public string POLICE_NUMBER { get; set; }
        public string CHASIS_NUMBER { get; set; }
        public string ENGINE_NUMBER { get; set; }
        public string EMPLOYEE_ID { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public Nullable<int> GROUP_LEVEL { get; set; }
        public string ASSIGNED_TO { get; set; }
        public string COST_CENTER { get; set; }
        public string VENDOR_NAME { get; set; }
        public string MANUFACTURER { get; set; }
        public string MODEL { get; set; }
        public string SERIES { get; set; }
        public string BODY_TYPE { get; set; }
        public string COLOR { get; set; }
        public string TRANSMISSION { get; set; }
        public Nullable<int> CAR_GROUP_LEVEL { get; set; }
        public string FUEL_TYPE { get; set; }
        public string BRANDING { get; set; }
        public Nullable<bool> AIRBAG { get; set; }
        public Nullable<int> VEHICLE_YEAR { get; set; }
        public string VEHICLE_TYPE { get; set; }
        public string VEHICLE_USAGE { get; set; }
        public string SUPPLY_METHOD { get; set; }
        public string CITY { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<bool> VAT { get; set; }
        public Nullable<bool> RESTITUTION { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string PO_NUMBER { get; set; }
        public string PO_LINE { get; set; }
        public Nullable<System.DateTime> START_CONTRACT { get; set; }
        public Nullable<System.DateTime> END_CONTRACT { get; set; }
        public string VEHICLE_STATUS { get; set; }
        public Nullable<bool> IS_TAKEN { get; set; }
        public Nullable<decimal> GR_LEFT_QTY { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string VEHICLE_FUNCTION { get; set; }
        public string REGIONAL { get; set; }
        public string CERTIFICATE_OWNERSHIP { get; set; }
        public string COMMENTS { get; set; }
        public string ASSETS { get; set; }
        public Nullable<decimal> MONTHLY_HMS_INSTALLMENT { get; set; }
        public Nullable<decimal> TOTAL_MONTHLY_CHARGE { get; set; }
        public Nullable<decimal> VAT_DECIMAL { get; set; }
        public Nullable<bool> PROJECT { get; set; }
        public string PROJECT_NAME { get; set; }
    
        public virtual MST_EMPLOYEE MST_EMPLOYEE { get; set; }
    }
}
