//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_REPORT_DATA
    {
        public int ID { get; set; }
        public string POLICE_NUMBER { get; set; }
        public string SUPPLY_METHOD { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public string COST_CENTER { get; set; }
        public string MANUFACTURER { get; set; }
        public string MODEL { get; set; }
        public string SERIES { get; set; }
        public string BODY_TYPE { get; set; }
        public string COLOR { get; set; }
        public string CHASIS_NUMBER { get; set; }
        public string ENGINE_NUMBER { get; set; }
        public string VEHICLE_TYPE { get; set; }
        public string VEHICLE_USAGE { get; set; }
        public string PO_NUMBER { get; set; }
        public string PO_LINE { get; set; }
        public Nullable<int> REPORT_MONTH { get; set; }
        public Nullable<int> REPORT_YEAR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public Nullable<long> MST_FLEET_ID { get; set; }
        public Nullable<System.DateTime> START_CONTRACT { get; set; }
        public Nullable<System.DateTime> END_CONTRACT { get; set; }
        public string VENDOR { get; set; }
        public Nullable<decimal> MONTHLY_INSTALLMENT { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<decimal> TOTAL_MONTHLY_INSTALLMENT { get; set; }
        public string EMPLOYEE_ID { get; set; }
        public string VEHICLE_FUNCTION { get; set; }
    
        public virtual MST_EMPLOYEE MST_EMPLOYEE { get; set; }
    }
}
