//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysAccess
    {
        public int AccessID { get; set; }
        public int RoleID { get; set; }
        public int ModuleID { get; set; }
        public bool FullControl { get; set; }
        public bool ReadAccess { get; set; }
        public bool CreateAccess { get; set; }
        public bool EditAccess { get; set; }
        public bool DeleteAccess { get; set; }
    
        public virtual SysRole SysRole { get; set; }
        public virtual SysModule SysModule { get; set; }
    }
}
