//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysMenu
    {
        public SysMenu()
        {
            this.SysMenu1 = new HashSet<SysMenu>();
            this.SysMenuAccesses = new HashSet<SysMenuAccess>();
        }
    
        public int MenuID { get; set; }
        public string Label { get; set; }
        public string Icon { get; set; }
        public string StateName { get; set; }
        public string Url { get; set; }
        public bool HasSubs { get; set; }
        public Nullable<int> MenuParent { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<SysMenu> SysMenu1 { get; set; }
        public virtual SysMenu SysMenu2 { get; set; }
        public virtual ICollection<SysMenuAccess> SysMenuAccesses { get; set; }
    }
}
