//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysModule
    {
        public SysModule()
        {
            this.SysAccesses = new HashSet<SysAccess>();
        }
    
        public int ModuleID { get; set; }
        public int ModuleLayerID { get; set; }
        public string ModuleName { get; set; }
        public string Url { get; set; }
        public string StateName { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<SysAccess> SysAccesses { get; set; }
    }
}
