//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysRole
    {
        public SysRole()
        {
            this.SysAccesses = new HashSet<SysAccess>();
            this.SysMenuAccesses = new HashSet<SysMenuAccess>();
            this.SysUserRoles = new HashSet<SysUserRole>();
        }
    
        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<SysAccess> SysAccesses { get; set; }
        public virtual ICollection<SysMenuAccess> SysMenuAccesses { get; set; }
        public virtual ICollection<SysUserRole> SysUserRoles { get; set; }
    }
}
