//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRA_CCF
    {
        public TRA_CCF()
        {
            this.TRA_CCF_DETAIL = new HashSet<TRA_CCF_DETAIL>();
        }
    
        public long TRA_CCF_ID { get; set; }
        public string DOCUMENT_NUMBER { get; set; }
        public int DOCUMENT_STATUS { get; set; }
        public int COMPLAINT_CATEGORY { get; set; }
        public string EMPLOYEE_ID { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public string EMPLOYEE_ID_COMPLAINT_FOR { get; set; }
        public string EMPLOYEE_NAME_COMPLAINT_FOR { get; set; }
        public string POLICE_NUMBER { get; set; }
        public string POLICE_NUMBER_GS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public bool IS_ACTIVE { get; set; }
    
        public virtual MST_COMPLAINT_CATEGORY MST_COMPLAINT_CATEGORY { get; set; }
        public virtual MST_EMPLOYEE MST_EMPLOYEE { get; set; }
        public virtual MST_EMPLOYEE MST_EMPLOYEE1 { get; set; }
        public virtual ICollection<TRA_CCF_DETAIL> TRA_CCF_DETAIL { get; set; }
    }
}
