//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRA_DOC_NUMBER
    {
        public long TRA_DOC_NUMBER_ID { get; set; }
        public string DOCUMENT_NUMBER { get; set; }
        public Nullable<int> MONTH { get; set; }
        public Nullable<int> YEAR { get; set; }
        public Nullable<int> DOCUMENT_TYPE { get; set; }
    }
}
