//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRA_CAF
    {
        public TRA_CAF()
        {
            this.TRA_CAF_PROGRESS = new HashSet<TRA_CAF_PROGRESS>();
        }
    
        public long TRA_CAF_ID { get; set; }
        public string DOCUMENT_NUMBER { get; set; }
        public int DOCUMENT_STATUS { get; set; }
        public string SIRS_NUMBER { get; set; }
        public string POLICE_NUMBER { get; set; }
        public string EMPLOYEE_ID { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public string SUPERVISOR { get; set; }
        public string AREA { get; set; }
        public Nullable<int> VENDOR_ID { get; set; }
        public string VENDOR_NAME { get; set; }
        public string VEHICLE_MODEL { get; set; }
        public Nullable<System.DateTime> INCIDENT_DATE { get; set; }
        public string INCIDENT_LOCATION { get; set; }
        public string INCIDENT_DESCRIPTION { get; set; }
        public Nullable<int> REMARK { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public bool IS_ACTIVE { get; set; }
    
        public virtual MST_EMPLOYEE MST_EMPLOYEE { get; set; }
        public virtual MST_REMARK MST_REMARK { get; set; }
        public virtual MST_VENDOR MST_VENDOR { get; set; }
        public virtual ICollection<TRA_CAF_PROGRESS> TRA_CAF_PROGRESS { get; set; }
    }
}
