//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRA_CCF_DETAIL
    {
        public long TRA_CCF_DETAIL_ID { get; set; }
        public long TRA_CCF_ID { get; set; }
        public Nullable<System.DateTime> COMPLAINT_DATE { get; set; }
        public string COMPLAINT_NOTE { get; set; }
        public string COMPLAINT_ATT { get; set; }
        public Nullable<System.DateTime> COORDINATOR_RESPONSE_DATE { get; set; }
        public string COORDINATOR_NOTE { get; set; }
        public Nullable<System.DateTime> COORDINATOR_PROMISED_DATE { get; set; }
        public string COORDINATOR_ATT { get; set; }
        public Nullable<System.DateTime> VENDOR_RESPONSE_DATE { get; set; }
        public string VENDOR_NOTE { get; set; }
        public Nullable<System.DateTime> VENDOR_PROMISED_DATE { get; set; }
        public string VENDOR_ATT { get; set; }
    
        public virtual TRA_CCF TRA_CCF { get; set; }
    }
}
