//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRA_CAF_PROGRESS
    {
        public long TRA_CAF_PROGRESS_ID { get; set; }
        public long TRA_CAF_ID { get; set; }
        public Nullable<int> STATUS_ID { get; set; }
        public Nullable<System.DateTime> PROGRESS_DATE { get; set; }
        public string REMARK { get; set; }
        public Nullable<int> ESTIMATION { get; set; }
        public Nullable<int> ACTUAL { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual TRA_CAF TRA_CAF { get; set; }
    }
}
