//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle_specs
    {
        public int vehicle_specs_id { get; set; }
        public string manufacturer { get; set; }
        public string model { get; set; }
        public string series { get; set; }
        public string body_type { get; set; }
        public string color { get; set; }
        public string image { get; set; }
        public Nullable<int> car_group_level { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_by { get; set; }
        public string last_modified { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<bool> is_active { get; set; }
    }
}
