//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICLE_HISTORY_REPORT_DATA
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string EMPLOYEE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> REPORT_MONTH { get; set; }
        public Nullable<int> REPORT_YEAR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
    }
}
