//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICLE_REPORT_DATA
    {
        public int ID { get; set; }
        public string POLICE_NUMBER { get; set; }
        public string MANUFACTURER { get; set; }
        public string MODEL { get; set; }
        public string SERIES { get; set; }
        public string BODY_TYPE { get; set; }
        public string EMPLOYEE_ID { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public string VEHICLE_TYPE { get; set; }
        public string COST_CENTER { get; set; }
        public Nullable<System.DateTime> START_RENT { get; set; }
        public Nullable<System.DateTime> END_RENT { get; set; }
        public string SUPPLY_METHOD { get; set; }
        public string VENDOR { get; set; }
        public string FUNCTION { get; set; }
        public string REGIONAL { get; set; }
        public string CITY { get; set; }
        public string TRANSMISSION { get; set; }
        public string FUEL_TYPE { get; set; }
        public string BRANDING { get; set; }
        public string COLOR { get; set; }
        public Nullable<bool> AIRBAG { get; set; }
        public Nullable<bool> ABS { get; set; }
        public string CHASIS_NUMBER { get; set; }
        public string ENGINE_NUMBER { get; set; }
        public Nullable<bool> VEHICLE_STATUS { get; set; }
        public string ASSET_NUMBER { get; set; }
        public Nullable<System.DateTime> TERMINATION_DATE { get; set; }
        public Nullable<bool> RESTITUTION { get; set; }
        public Nullable<decimal> MONTHLY_INSTALLMENT { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> TOTAL_MONTHLY_CHARGE { get; set; }
        public string PO_NUMBER { get; set; }
        public string PO_LINE { get; set; }
        public Nullable<int> REPORT_MONTH { get; set; }
        public Nullable<int> REPORT_YEAR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public Nullable<long> MST_FLEET_ID { get; set; }
    }
}
