//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class caf_progress
    {
        public long caf_progress_id { get; set; }
        public Nullable<long> accident_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<System.DateTime> progress_date { get; set; }
        public string remark { get; set; }
        public Nullable<int> estimation { get; set; }
        public Nullable<int> actual { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
    
        public virtual caf caf { get; set; }
    }
}
