//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ccf
    {
        public int ccf_id { get; set; }
        public Nullable<int> form_type_id { get; set; }
        public string request_number { get; set; }
        public Nullable<System.DateTime> request_date { get; set; }
        public string requestor { get; set; }
        public Nullable<long> fleet_id { get; set; }
        public Nullable<bool> gs { get; set; }
        public string police_number { get; set; }
        public Nullable<int> category_id { get; set; }
        public string employee_id { get; set; }
        public string employee_name { get; set; }
        public string city { get; set; }
        public string address { get; set; }
        public Nullable<int> coordinator_kpi { get; set; }
        public Nullable<int> vendor_kpi { get; set; }
        public Nullable<int> ccf_status { get; set; }
        public Nullable<int> remark_id { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
        public Nullable<int> coordinator { get; set; }
        public Nullable<System.DateTime> promised_date { get; set; }
    }
}
