//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class csf
    {
        public long csf_id { get; set; }
        public Nullable<int> form_type_id { get; set; }
        public string request_number { get; set; }
        public Nullable<System.DateTime> request_date { get; set; }
        public Nullable<int> coordinator { get; set; }
        public Nullable<int> reason_id { get; set; }
        public Nullable<System.DateTime> effective_date { get; set; }
        public Nullable<long> csf_parent_id { get; set; }
        public Nullable<long> fleet_idle { get; set; }
        public string reference_number { get; set; }
        public string employee_id { get; set; }
        public string employee_name { get; set; }
        public string cost_center { get; set; }
        public Nullable<int> group_level { get; set; }
        public string assigned_to { get; set; }
        public string vehicle_type { get; set; }
        public string vehicle_usage { get; set; }
        public string vehicle_category { get; set; }
        public Nullable<decimal> flexi_points { get; set; }
        public Nullable<int> location_id { get; set; }
        public string police_number { get; set; }
        public string manufacturer { get; set; }
        public string model { get; set; }
        public string series { get; set; }
        public string body_type { get; set; }
        public string color { get; set; }
        public Nullable<System.DateTime> contract_start { get; set; }
        public Nullable<System.DateTime> contract_end { get; set; }
        public Nullable<int> vendor_id { get; set; }
        public Nullable<System.DateTime> expected_date { get; set; }
        public string supply_method { get; set; }
        public Nullable<bool> Is_project { get; set; }
        public Nullable<int> project_id { get; set; }
        public Nullable<int> csf_status_id { get; set; }
        public Nullable<System.DateTime> start_rent { get; set; }
        public string vehicle_status { get; set; }
        public Nullable<bool> temporary_car { get; set; }
        public Nullable<int> coordinator2 { get; set; }
        public Nullable<int> remark_id { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<long> fleet_id { get; set; }
    }
}
