//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class epaf
    {
        public epaf()
        {
            this.crfs = new HashSet<crf>();
            this.ctfs = new HashSet<ctf>();
        }
    
        public int epaf_id { get; set; }
        public string form { get; set; }
        public string epaf_action { get; set; }
        public string employee_id { get; set; }
        public string employee_name { get; set; }
        public string cost_center { get; set; }
        public Nullable<System.DateTime> effective_date { get; set; }
        public Nullable<int> group_level { get; set; }
        public string expatriation { get; set; }
        public string eletter_sent { get; set; }
        public string city { get; set; }
        public string office_location { get; set; }
        public string to_city { get; set; }
        public string to_office_location { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public string csf_number { get; set; }
        public string link { get; set; }
        public string epaf_number { get; set; }
        public Nullable<System.DateTime> approved_date { get; set; }
        public string reference_number { get; set; }
        public string status { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_by { get; set; }
    
        public virtual ICollection<crf> crfs { get; set; }
        public virtual ICollection<ctf> ctfs { get; set; }
    }
}
