//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class penalty
    {
        public int penalty_id { get; set; }
        public string manufacturer { get; set; }
        public string model { get; set; }
        public string series { get; set; }
        public Nullable<int> vehicle_year { get; set; }
        public Nullable<int> month_start { get; set; }
        public Nullable<int> month_end { get; set; }
        public Nullable<decimal> penalty1 { get; set; }
        public string vehicle_type { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<bool> is_active { get; set; }
        public string vendor { get; set; }
        public Nullable<int> logic_id { get; set; }
    }
}
