//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle
    {
        public int vehicle_id { get; set; }
        public string manufacturer { get; set; }
        public string model { get; set; }
        public string series { get; set; }
        public string body_type { get; set; }
        public string color { get; set; }
        public Nullable<bool> airbag { get; set; }
        public string transmission { get; set; }
        public string branding { get; set; }
        public string image { get; set; }
        public string fuel_type { get; set; }
        public System.DateTime last_modified { get; set; }
        public string modified_by { get; set; }
        public Nullable<int> car_group_level { get; set; }
    }
}
