//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFIS.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildingFacilityListView
    {
        public int IDBuildingFacility { get; set; }
        public string IDLocation { get; set; }
        public string LocationName { get; set; }
        public string ParentLocation { get; set; }
        public string WarehouseAddress { get; set; }
        public string WarehouseStatus { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string pic1 { get; set; }
        public string pic2 { get; set; }
        public string pic3 { get; set; }
        public bool DoubleStacking { get; set; }
        public string WhsSze { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> isRegionalOffice { get; set; }
    }
}
