//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFIS.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralContImproveSandBag
    {
        public int IDContImprovSandBag { get; set; }
        public string IDLocation { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public string Department { get; set; }
        public string SubDepartment { get; set; }
        public string Title { get; set; }
        public string Status { get; set; }
        public string Owner { get; set; }
        public string EmployeeStatus { get; set; }
        public string IdeaSource { get; set; }
        public System.DateTime ImplementationDate { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string Remarks { get; set; }
    
        public virtual MasterLocation MasterLocation { get; set; }
    }
}
