//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFIS.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralContImprovSS
    {
        public int IDContImprovSS { get; set; }
        public Nullable<int> SubmitMonth { get; set; }
        public Nullable<int> SubmitYear { get; set; }
        public string Department { get; set; }
        public string Sub_Department { get; set; }
        public string Title { get; set; }
        public string Category1 { get; set; }
        public string Category2 { get; set; }
        public Nullable<System.DateTime> ProposedDate { get; set; }
        public Nullable<System.DateTime> ImplementationDate { get; set; }
        public Nullable<decimal> CostSaving_IDR { get; set; }
        public string CostSaving_USD { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string Facilitator { get; set; }
        public string Supervisor { get; set; }
        public string FirstLineAssessor { get; set; }
        public string SecondLineAssessor { get; set; }
        public Nullable<int> ProductivityScore { get; set; }
        public Nullable<int> QualityScore { get; set; }
        public Nullable<int> WorkingHourScore { get; set; }
        public Nullable<int> SafetyScore { get; set; }
        public Nullable<int> EnvironmentScore { get; set; }
        public Nullable<int> Ergonomic_HygieneScore { get; set; }
        public Nullable<int> UsabilityScore { get; set; }
        public Nullable<int> EffortScore { get; set; }
        public Nullable<int> ProActivenessScore { get; set; }
        public Nullable<int> CreativityScore { get; set; }
        public Nullable<int> FinalScore { get; set; }
        public Nullable<int> Voucher_IDR { get; set; }
        public string ABCDAwards { get; set; }
        public string VoucherNo { get; set; }
        public string Usability { get; set; }
        public string IdeaSource { get; set; }
        public string ModifiedFrom { get; set; }
        public string CopyBy { get; set; }
        public string Keywords { get; set; }
        public int Status { get; set; }
        public string Attachment { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string Remarks { get; set; }
        public string Attachment2 { get; set; }
        public string Attachment3 { get; set; }
        public string Attachment4 { get; set; }
    }
}
