//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFIS.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralBuildingFacility
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GeneralBuildingFacility()
        {
            this.GeneralBuildingFacilityDetails = new HashSet<GeneralBuildingFacilityDetail>();
            this.GeneralBuildingFacilityIcons = new HashSet<GeneralBuildingFacilityIcon>();
            this.GeneralBuildingFacilityImages = new HashSet<GeneralBuildingFacilityImage>();
            this.GeneralBuildingFacilityMaps = new HashSet<GeneralBuildingFacilityMap>();
        }
    
        public int IDBuildingFacility { get; set; }
        public string IDLocation { get; set; }
        public string WarehouseName { get; set; }
        public string WarehouseAddress { get; set; }
        public string WarehouseStatus { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string pic1 { get; set; }
        public string pic2 { get; set; }
        public string pic3 { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string Remarks { get; set; }
        public bool DoubleStacking { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralBuildingFacilityDetail> GeneralBuildingFacilityDetails { get; set; }
        public virtual MasterLocation MasterLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralBuildingFacilityIcon> GeneralBuildingFacilityIcons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralBuildingFacilityImage> GeneralBuildingFacilityImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralBuildingFacilityMap> GeneralBuildingFacilityMaps { get; set; }
    }
}
