//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFIS.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralSafeIntegration
    {
        public int IDSafeIntegration { get; set; }
        public string IDLocation { get; set; }
        public int TotalSafeEntry { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string Remarks { get; set; }
        public string LocationName { get; set; }
        public string LocationRegion { get; set; }
        public int TotalUnsafeEntry { get; set; }
        public int TotalUnseenEntry { get; set; }
        public int TotalEntry { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string EmployeeID { get; set; }
        public string FormalName { get; set; }
    
        public virtual MasterLocation MasterLocation { get; set; }
    }
}
