//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFIS.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPIDistributionCostView
    {
        public long Row { get; set; }
        public string DataType { get; set; }
        public int Year { get; set; }
        public string Type { get; set; }
        public string Func { get; set; }
        public string Dept { get; set; }
        public string Category { get; set; }
        public string Account { get; set; }
        public string val { get; set; }
        public string res { get; set; }
    }
}
