//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFIS.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPIInventoryRegionAccuracyView
    {
        public int year { get; set; }
        public string parentLocation { get; set; }
        public Nullable<decimal> jan { get; set; }
        public Nullable<decimal> feb { get; set; }
        public Nullable<decimal> mar { get; set; }
        public Nullable<decimal> apr { get; set; }
        public Nullable<decimal> may { get; set; }
        public Nullable<decimal> jun { get; set; }
        public Nullable<decimal> jul { get; set; }
        public Nullable<decimal> aug { get; set; }
        public Nullable<decimal> sep { get; set; }
        public Nullable<decimal> oct { get; set; }
        public Nullable<decimal> nov { get; set; }
        public Nullable<decimal> dec { get; set; }
    }
}
