//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFIS.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPILoadFactorCFP
    {
        public string GPNumber { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Week { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Mode { get; set; }
        public string VehicleType { get; set; }
        public string Brand { get; set; }
        public Nullable<int> DelivertyQty { get; set; }
        public string UOM { get; set; }
        public string Region { get; set; }
        public Nullable<decimal> KM { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Remarks { get; set; }
        public string Transport { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public Nullable<int> OriginQty { get; set; }
        public Nullable<decimal> KgCO2E { get; set; }
        public Nullable<int> avgLoadFactor { get; set; }
    }
}
