//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFIS.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPIUploadedEmployee
    {
        public int IDUploadedEmployee { get; set; }
        public string EmployeeID { get; set; }
        public string FormalName { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public string EmployeeCostCenter { get; set; }
        public int WorkingDays { get; set; }
        public string PositionDesc { get; set; }
        public string DepartmentDesc { get; set; }
        public string HMSOrgLvl3Desc { get; set; }
        public string HMSOrgLvl4Desc { get; set; }
        public string HMSOrgLvl5Desc { get; set; }
        public string HMSOrgLvl6Desc { get; set; }
        public string BaseTownLocation { get; set; }
        public string BaseTownCity { get; set; }
        public string StrcReportToPosition { get; set; }
        public string EmailAddress { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> EntitleOvertime { get; set; }
        public string Location { get; set; }
    }
}
