//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFIS.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadUnloadSealDetail
    {
        public string SJNumber { get; set; }
        public string GPNumber { get; set; }
        public string StatusLoadUnload { get; set; }
        public string SealNumber { get; set; }
        public string Type { get; set; }
        public string Remarks { get; set; }
    
        public virtual TransportLoadingUnloadingDetail TransportLoadingUnloadingDetail { get; set; }
    }
}
