//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFIS.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterLocation()
        {
            this.GeneralContImproveSandBags = new HashSet<GeneralContImproveSandBag>();
            this.GeneralSafeIntegrations = new HashSet<GeneralSafeIntegration>();
            this.KPIInventoryAccuracies = new HashSet<KPIInventoryAccuracy>();
            this.KPITotalRecordableInjuries = new HashSet<KPITotalRecordableInjury>();
            this.MasterEquipmentTypes = new HashSet<MasterEquipmentType>();
            this.MasterLocation1 = new HashSet<MasterLocation>();
            this.MasterUserLocationMappings = new HashSet<MasterUserLocationMapping>();
            this.WarehouseTempHumidities = new HashSet<WarehouseTempHumidity>();
            this.GeneralBuildingFacilities = new HashSet<GeneralBuildingFacility>();
            this.General5SMonitoring = new HashSet<General5SMonitoring>();
            this.WarehouseBeetleMonitorings = new HashSet<WarehouseBeetleMonitoring>();
            this.WarehouseSealStocks = new HashSet<WarehouseSealStock>();
            this.WarehouseSealManagements = new HashSet<WarehouseSealManagement>();
            this.MasterZoneLocations = new HashSet<MasterZoneLocation>();
            this.WarehouseStockForecasts = new HashSet<WarehouseStockForecast>();
            this.MasterLeadTimes = new HashSet<MasterLeadTime>();
            this.MasterLeadTimes1 = new HashSet<MasterLeadTime>();
            this.MasterMappingLocationPercentages = new HashSet<MasterMappingLocationPercentage>();
            this.MasterMappingLocationPercentages1 = new HashSet<MasterMappingLocationPercentage>();
            this.MasterFGStackings = new HashSet<MasterFGStacking>();
            this.WarehouseStockDetails = new HashSet<WarehouseStockDetail>();
            this.WarehouseStockForecastSalesPlans = new HashSet<WarehouseStockForecastSalesPlan>();
            this.WarehouseStockDetailSalesPlans = new HashSet<WarehouseStockDetailSalesPlan>();
            this.WarehouseStockCounts = new HashSet<WarehouseStockCount>();
            this.WarehouseStockCountDetails = new HashSet<WarehouseStockCountDetail>();
        }
    
        public string IDLocation { get; set; }
        public string LocationName { get; set; }
        public string ParentLocation { get; set; }
        public string Type { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsRegionalOffice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralContImproveSandBag> GeneralContImproveSandBags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralSafeIntegration> GeneralSafeIntegrations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPIInventoryAccuracy> KPIInventoryAccuracies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPITotalRecordableInjury> KPITotalRecordableInjuries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterEquipmentType> MasterEquipmentTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterLocation> MasterLocation1 { get; set; }
        public virtual MasterLocation MasterLocation2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterUserLocationMapping> MasterUserLocationMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseTempHumidity> WarehouseTempHumidities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralBuildingFacility> GeneralBuildingFacilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<General5SMonitoring> General5SMonitoring { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseBeetleMonitoring> WarehouseBeetleMonitorings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseSealStock> WarehouseSealStocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseSealManagement> WarehouseSealManagements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterZoneLocation> MasterZoneLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseStockForecast> WarehouseStockForecasts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterLeadTime> MasterLeadTimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterLeadTime> MasterLeadTimes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterMappingLocationPercentage> MasterMappingLocationPercentages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterMappingLocationPercentage> MasterMappingLocationPercentages1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterFGStacking> MasterFGStackings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseStockDetail> WarehouseStockDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseStockForecastSalesPlan> WarehouseStockForecastSalesPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseStockDetailSalesPlan> WarehouseStockDetailSalesPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseStockCount> WarehouseStockCounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseStockCountDetail> WarehouseStockCountDetails { get; set; }
    }
}
