//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFIS.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterRoleFunctionTreeListView
    {
        public int IDModule { get; set; }
        public string NameModule { get; set; }
        public Nullable<int> IDForm { get; set; }
        public string NameForm { get; set; }
        public int IDButton { get; set; }
        public string NameButton { get; set; }
    }
}
