//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFIS.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterDynamicField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterDynamicField()
        {
            this.GeneralBuildingFacilityDetails = new HashSet<GeneralBuildingFacilityDetail>();
        }
    
        public int IDDynamicField { get; set; }
        public string PageName { get; set; }
        public string FieldName { get; set; }
        public string FieldType { get; set; }
        public string GroupCollapse { get; set; }
        public int Ordering { get; set; }
        public int NotificationPeriod { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralBuildingFacilityDetail> GeneralBuildingFacilityDetails { get; set; }
    }
}
