//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFIS.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_location_item
    {
        public int id { get; set; }
        public Nullable<int> id_location { get; set; }
        public Nullable<int> id_item { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    }
}
