//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFIS.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportUnitFrequentData
    {
        public string GPNumber { get; set; }
        public Nullable<System.DateTime> GPDate { get; set; }
        public Nullable<int> GPMonth { get; set; }
        public Nullable<int> GPWeek { get; set; }
        public string Vendor { get; set; }
        public string PoliceNumber { get; set; }
        public string VehicleType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Remarks { get; set; }
    }
}
