//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFIS.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportVesselMonitoringDetail
    {
        public string GPNumber { get; set; }
        public string SJNumber { get; set; }
        public string STONumber { get; set; }
        public string OriginWarehouse { get; set; }
        public string DestinationWarehouse { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> GPDate { get; set; }
        public Nullable<System.DateTime> SJDate { get; set; }
        public string Remarks { get; set; }
    
        public virtual TransportVesselMonitoring TransportVesselMonitoring { get; set; }
    }
}
