//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFIS.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportLoadingUnloadingDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransportLoadingUnloadingDetail()
        {
            this.LoadUnloadSealDetails = new HashSet<LoadUnloadSealDetail>();
        }
    
        public string GPNumber { get; set; }
        public string SJNumber { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string StatusLoadUnload { get; set; }
        public Nullable<System.DateTime> PickInDate { get; set; }
        public Nullable<System.DateTime> LoadStartDate { get; set; }
        public Nullable<System.DateTime> LoadFinishDate { get; set; }
        public Nullable<System.DateTime> PickOutDate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoadUnloadSealDetail> LoadUnloadSealDetails { get; set; }
    }
}
