//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFIS.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseStockCountDetail
    {
        public int IDStockCountDetail { get; set; }
        public int IDStockCount { get; set; }
        public System.DateTime TransDate { get; set; }
        public string IDLocation { get; set; }
        public byte Shift { get; set; }
        public string SLoc { get; set; }
        public string FACode { get; set; }
        public bool Type { get; set; }
        public string SpeakingCode { get; set; }
        public string Brand { get; set; }
        public string Batch { get; set; }
        public Nullable<decimal> SAPQtyBox { get; set; }
        public Nullable<decimal> SAPQtyPack { get; set; }
        public Nullable<decimal> ManQtyBox { get; set; }
        public Nullable<decimal> ManQtyPack { get; set; }
        public Nullable<decimal> WarehouseQty1 { get; set; }
        public Nullable<decimal> WarehouseQty2 { get; set; }
        public Nullable<decimal> WarehouseQty3 { get; set; }
        public Nullable<decimal> WarehouseQty4 { get; set; }
        public Nullable<decimal> Unrestr { get; set; }
        public Nullable<decimal> QualityInsp { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string Remarks { get; set; }
    
        public virtual MasterFABrand MasterFABrand { get; set; }
        public virtual MasterLocation MasterLocation { get; set; }
        public virtual WarehouseStockCount WarehouseStockCount { get; set; }
    }
}
