//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFIS.EntitiesDAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseStockDetail
    {
        public int IDWarehouseStockDetail { get; set; }
        public string IDLocation { get; set; }
        public string BrandCode { get; set; }
        public int Week { get; set; }
        public int Year { get; set; }
        public decimal Opening { get; set; }
        public decimal ETASenin { get; set; }
        public decimal ETASelasa { get; set; }
        public decimal ETARabu { get; set; }
        public decimal ETAKamis { get; set; }
        public decimal ETAJumat { get; set; }
        public decimal ETASabtu { get; set; }
        public decimal ETAMinggu { get; set; }
        public decimal TotalStock { get; set; }
        public decimal Rate { get; set; }
        public int PercentageSales { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string Remarks { get; set; }
        public string LocationName { get; set; }
        public string ParentLocation { get; set; }
        public string LocationType { get; set; }
    
        public virtual MasterLocation MasterLocation { get; set; }
    }
}
