/****** Object:  StoredProcedure [dbo].[GetLeaseCostData]    Script Date: 26/12/2017 21:59:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER procedure [dbo].[GetLeaseCostData]
AS BEGIN

	MERGE LEASE_COST_BY_FUNC_REPORT_DATA AS Target
	USING (
		select VEHICLE_FUNCTION, SUM(TOTAL_MONTHLY_CHARGE) AS TOTAL_LEASE_COST, MONTH(GETDATE()) As REPORT_MONTH
		, YEAR(GETDATE()) As REPORT_YEAR, START_CONTRACT, REGIONAL FROM MST_FLEET
		WHERE (IS_ACTIVE = 1 )
		AND (PROJECT = 1)
		GROUP BY VEHICLE_FUNCTION, START_CONTRACT, REGIONAL
	) AS Source
	ON (Source.VEHICLE_FUNCTION = Target.[FUNCTION] OR (Source.VEHICLE_FUNCTION IS NULL AND Target.[FUNCTION] IS NULL))
	AND (Source.REGIONAL = Target.REGION OR (Source.REGIONAL IS NULL AND Target.REGION IS NULL))
	AND (Source.REPORT_MONTH = Target.REPORT_MONTH)
	AND (Source.REPORT_YEAR = Target.REPORT_YEAR)
	AND (Source.START_CONTRACT = Target.CREATED_DATE)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT ([FUNCTION], TOTAL_LEASE_COST, REPORT_MONTH, REPORT_YEAR, CREATED_DATE, REGION)
		VALUES( Source.VEHICLE_FUNCTION, Source.TOTAL_LEASE_COST, Source.REPORT_MONTH, 
		Source.REPORT_YEAR, Source.START_CONTRACT, Source.REGIONAL)
	WHEN MATCHED THEN
		UPDATE SET
		TOTAL_LEASE_COST = Source.TOTAL_LEASE_COST;

END
