ALTER TABLE [ARCH_TRA_CSF] ADD ARCHIVED_BY VARCHAR(50) NULL, ARCHIVED_DATE DATETIME NULL
GO

ALTER TABLE [ARCH_TRA_CRF] ADD ARCHIVED_BY VARCHAR(50) NULL, ARCHIVED_DATE DATETIME NULL
GO

ALTER TABLE [ARCH_TRA_CTF] ADD ARCHIVED_BY VARCHAR(50) NULL, ARCHIVED_DATE DATETIME NULL
GO

ALTER TABLE [ARCH_TRA_TEMPORARY] ADD ARCHIVED_BY VARCHAR(50) NULL, ARCHIVED_DATE DATETIME NULL
GO

ALTER TABLE [ARCH_TRA_CTF_EXTEND] ADD ARCHIVED_BY VARCHAR(50) NULL, ARCHIVED_DATE DATETIME NULL
GO

ALTER TABLE [ARCH_TRA_CCF] ADD ARCHIVED_BY VARCHAR(50) NULL, ARCHIVED_DATE DATETIME NULL
GO

ALTER TABLE [ARCH_TRA_CCF_DETAIL] ADD ARCHIVED_BY VARCHAR(50) NULL, ARCHIVED_DATE DATETIME NULL
GO

ALTER TABLE [ARCH_TRA_CAF] ADD ARCHIVED_BY VARCHAR(50) NULL, ARCHIVED_DATE DATETIME NULL
GO

ALTER TABLE [ARCH_TRA_CAF_PROGRESS] ADD ARCHIVED_BY VARCHAR(50) NULL, ARCHIVED_DATE DATETIME NULL
GO

