ALTER TABLE ARCH_MST_COST_OB ADD ARCHIVED_DATE DATETIME NULL, ARCHIVED_BY VARCHAR(50) NULL
GO

ALTER TABLE ARCH_MST_EMPLOYEE ADD ARCHIVED_DATE DATETIME NULL, ARCHIVED_BY VARCHAR(50) NULL
GO

ALTER TABLE ARCH_MST_EPAF ADD ARCHIVED_DATE DATETIME NULL, ARCHIVED_BY VARCHAR(50) NULL
GO

ALTER TABLE ARCH_MST_FLEET ADD ARCHIVED_DATE DATETIME NULL, ARCHIVED_BY VARCHAR(50) NULL
GO

ALTER TABLE ARCH_MST_FUEL_ODOMETER ADD ARCHIVED_DATE DATETIME NULL, ARCHIVED_BY VARCHAR(50) NULL
GO

ALTER TABLE ARCH_MST_FUNCTION_GROUP ADD ARCHIVED_DATE DATETIME NULL, ARCHIVED_BY VARCHAR(50) NULL
GO

ALTER TABLE ARCH_MST_GS ADD ARCHIVED_DATE DATETIME NULL, ARCHIVED_BY VARCHAR(50) NULL
GO

ALTER TABLE ARCH_MST_HOLIDAY_CALENDAR ADD ARCHIVED_DATE DATETIME NULL, ARCHIVED_BY VARCHAR(50) NULL
GO

ALTER TABLE ARCH_MST_LOCATION_MAPPING ADD ARCHIVED_DATE DATETIME NULL, ARCHIVED_BY VARCHAR(50) NULL
GO

ALTER TABLE ARCH_MST_PENALTY ADD ARCHIVED_DATE DATETIME NULL, ARCHIVED_BY VARCHAR(50) NULL
GO

ALTER TABLE ARCH_MST_PRICELIST ADD ARCHIVED_DATE DATETIME NULL, ARCHIVED_BY VARCHAR(50) NULL
GO

ALTER TABLE ARCH_MST_SALES_VOLUME ADD ARCHIVED_DATE DATETIME NULL, ARCHIVED_BY VARCHAR(50) NULL
GO

ALTER TABLE ARCH_MST_VEHICLE_SPECT ADD ARCHIVED_DATE DATETIME NULL, ARCHIVED_BY VARCHAR(50) NULL
GO