/*MST_COST_OB*/

CREATE TABLE [dbo].[ARCH_MST_COST_OB](
	[MST_COST_OB_ID] [bigint] NOT NULL,
	[YEAR] [int] NULL,
	[ZONE] [nvarchar](50) NULL,
	[MODEL] [nvarchar](250) NULL,
	[TYPE] [nvarchar](250) NULL,
	[OB_COST] [decimal](18, 2) NULL,
	[REMARK] [nvarchar](250) NULL,
	[CREATED_BY] [nvarchar](50) NULL,
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_BY] [nvarchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[IS_ACTIVE] [bit] NULL,
	[COST_CENTER] [char](10) NULL,
	[QTY] [int] NULL,
	[MONTH] [int] NULL,
	[VEHICLE_TYPE] [nvarchar](50) NULL,
	[FUNCTION_NAME] [nvarchar](50) NULL,
	[REGIONAL] [nvarchar](50) NULL,
 CONSTRAINT [PK_ARCH_MST_COST_OB] PRIMARY KEY CLUSTERED 
(
	[MST_COST_OB_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/*MST_FLEET*/
CREATE TABLE [dbo].[ARCH_MST_FLEET](
	[MST_FLEET_ID] [bigint] NOT NULL,
	[POLICE_NUMBER] [nvarchar](50) NULL,
	[CHASIS_NUMBER] [nvarchar](50) NULL,
	[ENGINE_NUMBER] [nvarchar](50) NULL,
	[EMPLOYEE_ID] [nvarchar](9) NULL,
	[EMPLOYEE_NAME] [nvarchar](100) NULL,
	[GROUP_LEVEL] [int] NULL,
	[ASSIGNED_TO] [nvarchar](50) NULL,
	[COST_CENTER] [char](10) NULL,
	[VENDOR_NAME] [nvarchar](100) NULL,
	[MANUFACTURER] [nvarchar](50) NULL,
	[MODEL] [nvarchar](50) NULL,
	[SERIES] [nvarchar](50) NULL,
	[BODY_TYPE] [nvarchar](50) NULL,
	[COLOR] [nvarchar](50) NULL,
	[TRANSMISSION] [nvarchar](50) NULL,
	[CAR_GROUP_LEVEL] [int] NULL,
	[FUEL_TYPE] [nvarchar](50) NULL,
	[BRANDING] [nvarchar](50) NULL,
	[AIRBAG] [bit] NULL,
	[VEHICLE_YEAR] [int] NULL,
	[VEHICLE_TYPE] [nvarchar](50) NULL,
	[VEHICLE_USAGE] [nvarchar](50) NULL,
	[SUPPLY_METHOD] [nvarchar](50) NULL,
	[CITY] [nvarchar](50) NULL,
	[ADDRESS] [text] NULL,
	[VAT] [bit] NULL,
	[RESTITUTION] [bit] NULL,
	[START_DATE] [date] NULL,
	[END_DATE] [date] NULL,
	[PO_NUMBER] [nvarchar](50) NULL,
	[PO_LINE] [nvarchar](50) NULL,
	[START_CONTRACT] [date] NULL,
	[END_CONTRACT] [date] NULL,
	[VEHICLE_STATUS] [nvarchar](50) NULL,
	[IS_TAKEN] [bit] NULL,
	[GR_LEFT_QTY] [decimal](18, 2) NULL,
	[CREATED_BY] [nvarchar](50) NULL,
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_BY] [nvarchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[IS_ACTIVE] [bit] NULL,
	[VEHICLE_FUNCTION] [nvarchar](50) NULL,
	[REGIONAL] [nvarchar](50) NULL,
	[CERTIFICATE_OWNERSHIP] [nvarchar](50) NULL,
	[COMMENTS] [nvarchar](255) NULL,
	[ASSETS] [nvarchar](50) NULL,
	[MONTHLY_HMS_INSTALLMENT] [decimal](18, 2) NULL,
	[TOTAL_MONTHLY_CHARGE] [decimal](18, 2) NULL,
	[VAT_DECIMAL] [decimal](18, 2) NULL,
	[PROJECT] [bit] NULL,
	[PROJECT_NAME] [nvarchar](50) NULL,
	[PRICE] [decimal](18, 2) NULL,
	[SALES_CODE] [nvarchar](255) NULL,
	[DOCUMENT_NUMBER] [char](15) NULL,
 CONSTRAINT [PK_ARCH_MST_FLEET] PRIMARY KEY CLUSTERED 
(
	[MST_FLEET_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

/*MST_GS*/
CREATE TABLE [dbo].[ARCH_MST_GS](
	[MST_GS_ID] [int] NOT NULL,
	[EMPLOYEE_NAME] [nvarchar](100) NULL,
	[VEHICLE_USAGE] [nvarchar](50) NULL,
	[POLICE_NUMBER] [nvarchar](50) NULL,
	[GROUP_LEVEL] [int] NULL,
	[LOCATION] [nvarchar](50) NULL,
	[GS_REQUEST_DATE] [date] NULL,
	[GS_FULLFILLMENT_DATE] [date] NULL,
	[GS_UNIT_TYPE] [nvarchar](50) NULL,
	[GS_POLICE_NUMBER] [nvarchar](50) NULL,
	[START_DATE] [date] NULL,
	[END_DATE] [date] NULL,
	[REMARK] [text] NULL,
	[CREATED_BY] [nvarchar](50) NULL,
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_BY] [nvarchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[IS_ACTIVE] [bit] NULL,
	[EMPLOYEE_ID] [nvarchar](9) NULL,
	[MANUFACTURER] [nvarchar](50) NULL,
	[MODEL] [nvarchar](50) NULL,
	[SERIES] [nvarchar](50) NULL,
	[TRANSMISSION] [nvarchar](50) NULL,
	[YEAR] [int] NULL,
	[GS_MANUFACTURER] [nvarchar](50) NULL,
	[GS_MODEL] [nvarchar](50) NULL,
	[GS_SERIES] [nvarchar](50) NULL,
	[GS_TRANSMISSION] [nvarchar](50) NULL,
	[LEAD_TIME] [datetime] NULL,
 CONSTRAINT [PK_ARCH_MST_GS] PRIMARY KEY CLUSTERED 
(
	[MST_GS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

/*MST_PENALTY*/

CREATE TABLE [dbo].[ARCH_MST_PENALTY](
	[MST_PENALTY_ID] [int] NOT NULL,
	[MANUFACTURER] [nvarchar](50) NULL,
	[MODEL] [nvarchar](50) NULL,
	[SERIES] [nvarchar](50) NULL,
	[YEAR] [int] NULL,
	[MONTH_START] [int] NULL,
	[MONTH_END] [int] NULL,
	[VEHICLE_TYPE] [nvarchar](50) NULL,
	[PENALTY] [int] NULL,
	[RESTITUTION] [bit] NULL,
	[CREATED_BY] [nvarchar](50) NULL,
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_BY] [nvarchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[IS_ACTIVE] [bit] NULL,
	[VENDOR] [int] NULL,
	[BODY_TYPE] [nvarchar](50) NULL,
 CONSTRAINT [PK_ARCH_MST_PENALTY] PRIMARY KEY CLUSTERED 
(
	[MST_PENALTY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/*MST_PRICELIST*/
CREATE TABLE [dbo].[ARCH_MST_PRICELIST](
	[MST_PRICELIST_ID] [int] NOT NULL,
	[YEAR] [int] NULL,
	[MANUFACTURER] [nvarchar](50) NULL,
	[MODEL] [nvarchar](50) NULL,
	[SERIES] [nvarchar](50) NULL,
	[ZONE_PRICE_LIST] [nvarchar](50) NULL,
	[PRICE] [decimal](18, 2) NULL,
	[INSTALLMEN_HMS] [decimal](18, 2) NULL,
	[INSTALLMEN_EMP] [decimal](18, 2) NULL,
	[VENDOR] [int] NULL,
	[CREATED_BY] [nvarchar](50) NULL,
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_BY] [nvarchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[IS_ACTIVE] [bit] NULL,
	[VEHICLE_TYPE] [nvarchar](50) NULL,
	[VEHICLE_USAGE] [nvarchar](50) NULL,
 CONSTRAINT [PK_ARCH_MST_PRICELIST] PRIMARY KEY CLUSTERED 
(
	[MST_PRICELIST_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/*MST_SALES_VOLUME*/
CREATE TABLE [dbo].[ARCH_MST_SALES_VOLUME](
	[MST_SALES_VOLUME_ID] [int] NOT NULL,
	[TYPE] [nvarchar](50) NULL,
	[REGION] [nvarchar](50) NULL,
	[MONTH] [int] NULL,
	[YEAR] [int] NULL,
	[VALUE] [decimal](18, 2) NULL,
	[CREATED_BY] [nvarchar](50) NULL,
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_BY] [nvarchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[IS_ACTIVE] [bit] NULL,
 CONSTRAINT [PK_ARCH_MST_SALES_VOLUME] PRIMARY KEY CLUSTERED 
(
	[MST_SALES_VOLUME_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/*MST_VEHICLE_SPEC*/
CREATE TABLE [dbo].[ARCH_MST_VEHICLE_SPECT](
	[MST_VEHICLE_SPECT_ID] [int] NOT NULL,
	[MANUFACTURER] [nvarchar](50) NULL,
	[MODEL] [nvarchar](50) NULL,
	[SERIES] [nvarchar](50) NULL,
	[BODY_TYPE] [nvarchar](50) NULL,
	[YEAR] [int] NULL,
	[COLOUR] [nvarchar](50) NULL,
	[IMAGE] [text] NULL,
	[GROUP_LEVEL] [int] NULL,
	[FLEX_POINT] [int] NULL,
	[CREATED_BY] [nvarchar](50) NULL,
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_BY] [nvarchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[IS_ACTIVE] [bit] NULL,
	[TRANSMISSION] [nvarchar](50) NULL,
	[FUEL_TYPE] [nvarchar](50) NULL,
 CONSTRAINT [PK_ARCH_MST_VEHICLE_SPECT] PRIMARY KEY CLUSTERED 
(
	[MST_VEHICLE_SPECT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

/*MST_EMPLOYEE*/
CREATE TABLE [dbo].[ARCH_MST_EMPLOYEE](
	[EMPLOYEE_ID] [nvarchar](9) NOT NULL,
	[FORMAL_NAME] [nvarchar](100) NULL,
	[POSITION_TITLE] [nvarchar](100) NULL,
	[DIVISON] [nvarchar](100) NULL,
	[DIRECTORATE] [nvarchar](100) NULL,
	[ADDRESS] [text] NULL,
	[CITY] [nvarchar](100) NULL,
	[BASETOWN] [nvarchar](100) NULL,
	[COMPANY] [nvarchar](50) NULL,
	[COST_CENTER] [char](10) NULL,
	[GROUP_LEVEL] [int] NULL,
	[EMAIL_ADDRESS] [nvarchar](100) NULL,
	[FLEX_POINT] [int] NULL,
	[CREATED_BY] [nvarchar](50) NULL,
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_BY] [nvarchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[IS_ACTIVE] [bit] NULL,
 CONSTRAINT [PK_ARCH_MST_EMPLOYEE] PRIMARY KEY CLUSTERED 
(
	[EMPLOYEE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

/*MST_EPAF*/

CREATE TABLE [dbo].[ARCH_MST_EPAF](
	[MST_EPAF_ID] [bigint] NOT NULL,
	[DOCUMENT_TYPE] [int] NULL,
	[EPAF_ACTION] [nvarchar](50) NULL,
	[EMPLOYEE_ID] [nvarchar](9) NULL,
	[EMPLOYEE_NAME] [nvarchar](100) NULL,
	[COST_CENTER] [char](10) NULL,
	[EFFECTIVE_DATE] [date] NULL,
	[GROUP_LEVEL] [int] NULL,
	[CITY] [nvarchar](50) NULL,
	[BASE_TOWN] [nvarchar](50) NULL,
	[EXPAT] [bit] NULL,
	[LETTER_SEND] [bit] NULL,
	[EPAF_APPROVED_DATE] [datetime] NULL,
	[REMARK] [int] NULL,
	[LAST_UPDATED] [nvarchar](50) NULL,
	[CREATED_BY] [nvarchar](50) NULL,
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_BY] [nvarchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[IS_ACTIVE] [bit] NULL,
	[GRADE_LEVEL] [int] NULL,
 CONSTRAINT [PK_ARCH_MST_EPAF] PRIMARY KEY CLUSTERED 
(
	[MST_EPAF_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/*MST_FUEL_ODOMETER*/
CREATE TABLE [dbo].[ARCH_MST_FUEL_ODOMETER](
	[MST_FUEL_ODOMETER_ID] [bigint] NOT NULL,
	[VEHICLE_TYPE] [nvarchar](50) NULL,
	[POLICE_NUMBER] [nvarchar](50) NULL,
	[EMPLOYEE_ID] [nvarchar](9) NULL,
	[EMPLOYEE_NAME] [nvarchar](100) NULL,
	[ECS_RMB_TRANSID] [int] NULL,
	[SEQ_NUMBER] [int] NULL,
	[CLAIM_TYPE] [nvarchar](250) NULL,
	[DATE_OF_COST] [date] NULL,
	[COST_CENTER] [char](10) NULL,
	[FUEL_AMOUNT] [decimal](18, 2) NULL,
	[LAST_KM] [decimal](18, 2) NULL,
	[COST] [decimal](18, 2) NULL,
	[CLAIM_COMMENT] [text] NULL,
	[POSTED_TIME] [datetime] NULL,
	[CREATED_BY] [nvarchar](50) NULL,
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_BY] [nvarchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[IS_ACTIVE] [bit] NULL,
 CONSTRAINT [PK_ARCH_MST_FUEL_ODOMETER] PRIMARY KEY CLUSTERED 
(
	[MST_FUEL_ODOMETER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

/*MST_FUNCTION_GROUP*/
CREATE TABLE [dbo].[ARCH_MST_FUNCTION_GROUP](
	[MST_FUNCTION_GROUP_ID] [int] NOT NULL,
	[FUNCTION_NAME] [nvarchar](50) NULL,
	[COST_CENTER] [char](10) NULL,
	[CREATED_BY] [nvarchar](50) NULL,
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_BY] [nvarchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[IS_ACTIVE] [bit] NULL,
 CONSTRAINT [PK_ARCH_MST_FUNCTION_GROUP] PRIMARY KEY CLUSTERED 
(
	[MST_FUNCTION_GROUP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/*MST_HOLIDAY_CALENDAR*/
CREATE TABLE [dbo].[ARCH_MST_HOLIDAY_CALENDAR](
	[MST_HOLIDAY_ID] [int] NOT NULL,
	[MST_HOLIDAY_DATE] [date] NULL,
	[DESCRIPTION] [varchar](250) NULL,
	[CREATED_BY] [nvarchar](50) NULL,
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_BY] [nvarchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[IS_ACTIVE] [bit] NULL,
 CONSTRAINT [PK_ARCH_MST_HOLIDAY_CALENDAR] PRIMARY KEY CLUSTERED 
(
	[MST_HOLIDAY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/*MST_LOCATION_MAPPING*/

CREATE TABLE [dbo].[ARCH_MST_LOCATION_MAPPING](
	[MST_LOCATION_MAPPING_ID] [int] NOT NULL,
	[LOCATION] [nvarchar](50) NULL,
	[ADDRESS] [nvarchar](250) NULL,
	[REGION] [nvarchar](50) NULL,
	[ZONE_SALES] [nvarchar](50) NULL,
	[ZONE_PRICE_LIST] [nvarchar](50) NULL,
	[VALIDITY_FROM] [date] NULL,
	[CREATED_BY] [nvarchar](50) NULL,
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_BY] [nvarchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[IS_ACTIVE] [bit] NULL,
	[BASETOWN] [nvarchar](50) NULL,
 CONSTRAINT [PK_ARCH_MST_LOCATION_MAPPING] PRIMARY KEY CLUSTERED 
(
	[MST_LOCATION_MAPPING_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

