/*TRA CSF*/
CREATE TABLE [dbo].[ARCH_TRA_CSF](
	[TRA_CSF_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DOCUMENT_NUMBER] [char](15) NOT NULL,
	[DOCUMENT_STATUS] [int] NOT NULL,
	[EPAF_ID] [bigint] NULL,
	[REASON] [int] NOT NULL,
	[EFFECTIVE_DATE] [date] NOT NULL,
	[EMPLOYEE_ID] [nvarchar](9) NOT NULL,
	[EMPLOYEE_NAME] [nvarchar](100) NOT NULL,
	[COST_CENTER] [char](10) NULL,
	[GROUP_LEVEL] [int] NULL,
	[VEHICLE_TYPE] [nvarchar](50) NULL,
	[VEHICLE_CATEGORY] [nvarchar](50) NULL,
	[VEHICLE_USAGE] [nvarchar](50) NULL,
	[LOCATION_CITY] [nvarchar](50) NULL,
	[LOCATION_ADDRESS] [nvarchar](250) NULL,
	[POLICE_NUMBER] [nvarchar](50) NULL,
	[MANUFACTURER] [nvarchar](50) NULL,
	[MODEL] [nvarchar](50) NULL,
	[SERIES] [nvarchar](50) NULL,
	[BODY_TYPE] [nvarchar](50) NULL,
	[COLOUR] [nvarchar](50) NULL,
	[START_PERIOD] [date] NULL,
	[END_PERIOD] [date] NULL,
	[VENDOR] [int] NULL,
	[EXPECTED_DATE] [date] NULL,
	[START_RENT_DATE] [date] NULL,
	[END_RENT_DATE] [date] NULL,
	[SUPPLY_METHOD] [nvarchar](50) NULL,
	[IS_PROJECT] [bit] NULL,
	[PROJECT_NAME] [nvarchar](50) NULL,
	[PO_NUMBER] [nvarchar](50) NULL,
	[REMARK] [int] NULL,
	[CREATED_BY] [nvarchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [nvarchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[IS_ACTIVE] [bit] NOT NULL,
	[VENDOR_NAME] [nvarchar](100) NULL,
	[APPROVED_FLEET] [nvarchar](50) NULL,
	[APPROVED_FLEET_DATE] [datetime] NULL,
	[VENDOR_POLICE_NUMBER] [nvarchar](50) NULL,
	[VENDOR_CHASIS_NUMBER] [nvarchar](50) NULL,
	[VENDOR_ENGINE_NUMBER] [nvarchar](50) NULL,
	[VENDOR_CONTRACT_START_DATE] [date] NULL,
	[VENDOR_CONTRACT_END_DATE] [date] NULL,
	[VENDOR_MANUFACTURER] [nvarchar](50) NULL,
	[VENDOR_MODEL] [nvarchar](50) NULL,
	[VENDOR_SERIES] [nvarchar](50) NULL,
	[VENDOR_TRANSMISSION] [nvarchar](50) NULL,
	[VENDOR_COLOUR] [nvarchar](50) NULL,
	[VENDOR_BODY_TYPE] [nvarchar](50) NULL,
	[VENDOR_AIR_BAG] [bit] NULL,
	[VENDOR_ABS] [bit] NULL,
	[VENDOR_BRANDING] [nvarchar](50) NULL,
	[VENDOR_PURPOSE] [nvarchar](50) NULL,
	[VENDOR_PO_NUMBER] [nvarchar](50) NULL,
	[VENDOR_PO_LINE] [nvarchar](50) NULL,
	[VENDOR_VAT] [bit] NULL,
	[VENDOR_RESTITUTION] [bit] NULL,
	[VENDOR_VENDOR] [nvarchar](100) NULL,
	[EMPLOYEE_ID_CREATOR] [nvarchar](9) NULL,
	[EMPLOYEE_ID_FLEET_APPROVAL] [nvarchar](9) NULL,
	[CAR_GROUP_LEVEL] [int] NULL,
	[CFM_IDLE_ID] [bigint] NULL,
	[ASSIGNED_TO] [nvarchar](250) NULL,
	[FLEXBEN] [int] NULL,
	[COMMENTS] [nvarchar](255) NULL,
	[PRICE] [decimal](18, 2) NULL,
	[VAT_DECIMAL] [decimal](18, 2) NULL,
	[DATE_SEND_VENDOR] [datetime] NULL,
 CONSTRAINT [PK_ARCH_TRA_CSF] PRIMARY KEY CLUSTERED 
(
	[TRA_CSF_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


/*TRA CRF*/
CREATE TABLE [dbo].[ARCH_TRA_CRF](
	[TRA_CRF_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DOCUMENT_NUMBER] [char](15) NOT NULL,
	[DOCUMENT_STATUS] [int] NOT NULL,
	[EPAF_ID] [bigint] NULL,
	[EMPLOYEE_ID] [nvarchar](9) NULL,
	[EMPLOYEE_NAME] [nvarchar](100) NULL,
	[COST_CENTER] [char](10) NULL,
	[COST_CENTER_NEW] [char](10) NULL,
	[LOCATION_CITY] [nvarchar](50) NULL,
	[LOCATION_OFFICE] [nvarchar](50) NULL,
	[LOCATION_CITY_NEW] [nvarchar](50) NULL,
	[LOCATION_OFFICE_NEW] [nvarchar](50) NULL,
	[VEHICLE_TYPE] [nvarchar](50) NULL,
	[VEHICLE_USAGE] [nvarchar](50) NULL,
	[EFFECTIVE_DATE] [date] NULL,
	[RELOCATION_TYPE] [nvarchar](50) NULL,
	[TEMPORARY_DELIVERABLE_DATE] [date] NULL,
	[POLICE_NUMBER] [nvarchar](50) NULL,
	[MANUFACTURER] [nvarchar](50) NULL,
	[MODEL] [nvarchar](50) NULL,
	[SERIES] [nvarchar](50) NULL,
	[BODY_TYPE] [nvarchar](50) NULL,
	[VENDOR_ID] [int] NULL,
	[VENDOR_NAME] [nvarchar](50) NULL,
	[START_PERIOD] [date] NULL,
	[END_PERIOD] [date] NULL,
	[WITHD_CITY] [varchar](50) NULL,
	[WITHD_ADDRESS] [nvarchar](1000) NULL,
	[WITHD_PIC] [varchar](50) NULL,
	[WITHD_PHONE] [varchar](50) NULL,
	[WITHD_DATETIME] [datetime] NULL,
	[DELIV_CITY] [varchar](50) NULL,
	[DELIV_ADDRESS] [nvarchar](1000) NULL,
	[DELIV_PIC] [varchar](50) NULL,
	[DELIV_PHONE] [varchar](50) NULL,
	[CHANGE_POLICE_NUMBER] [bit] NULL,
	[EXPECTED_DATE] [date] NULL,
	[PO_NUMBER] [nvarchar](50) NULL,
	[PO_LINE] [nvarchar](50) NULL,
	[PRICE] [decimal](18, 2) NULL,
	[REMARK] [int] NULL,
	[CREATED_BY] [nvarchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [nvarchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[IS_ACTIVE] [bit] NOT NULL,
	[NEW_POLICE_NUMBER] [varchar](50) NULL,
	[MST_FLEET_ID] [bigint] NULL,
	[DATE_SEND_VENDOR] [datetime] NULL,
 CONSTRAINT [PK_ARCH_TRA_CRF] PRIMARY KEY CLUSTERED 
(
	[TRA_CRF_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/*TRA CTF*/
CREATE TABLE [dbo].[ARCH_TRA_CTF](
	[TRA_CTF_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DOCUMENT_NUMBER] [char](15) NOT NULL,
	[DOCUMENT_STATUS] [int] NOT NULL,
	[EPAF_ID] [bigint] NULL,
	[EMPLOYEE_ID] [nvarchar](9) NOT NULL,
	[EMPLOYEE_NAME] [nvarchar](100) NOT NULL,
	[COST_CENTER] [char](10) NULL,
	[GROUP_LEVEL] [int] NULL,
	[REASON] [int] NULL,
	[SUPPLY_METHOD] [nvarchar](50) NULL,
	[POLICE_NUMBER] [nvarchar](50) NULL,
	[VEHICLE_YEAR] [int] NULL,
	[VEHICLE_TYPE] [nvarchar](50) NULL,
	[VEHICLE_USAGE] [nvarchar](50) NULL,
	[END_RENT_DATE] [date] NULL,
	[EFFECTIVE_DATE] [date] NULL,
	[IS_TRANSFER_TO_IDLE] [bit] NULL,
	[BUY_COST] [decimal](18, 2) NULL,
	[EXTEND_VEHICLE] [bit] NULL,
	[WITHD_PIC] [nvarchar](50) NULL,
	[WITHD_PHONE] [nvarchar](50) NULL,
	[WITHD_DATE] [date] NULL,
	[WITHD_CITY] [nvarchar](50) NULL,
	[WITHD_ADDRESS] [nvarchar](1000) NULL,
	[EMPLOYEE_CONTRIBUTION] [decimal](18, 2) NULL,
	[PENALTY] [decimal](18, 2) NULL,
	[REFUND_COST] [decimal](18, 2) NULL,
	[BUY_COST_TOTAL] [decimal](18, 2) NULL,
	[USER_DECISION] [int] NULL,
	[PENALTY_PO_NUMBER] [nvarchar](50) NULL,
	[PENALTY_PO_LINE] [nvarchar](50) NULL,
	[PENALTY_PRICE] [decimal](18, 2) NULL,
	[REMARK] [int] NULL,
	[CREATED_BY] [nvarchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [nvarchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[IS_ACTIVE] [bit] NOT NULL,
	[VEHICLE_LOCATION] [nvarchar](50) NULL,
	[EMPLOYEE_ID_CREATOR] [nvarchar](9) NULL,
	[EMPLOYEE_ID_FLEET_APPROVAL] [nvarchar](9) NULL,
	[APPROVED_FLEET] [nvarchar](50) NULL,
	[APPROVED_FLEET_DATE] [datetime] NULL,
	[DATE_SEND_VENDOR] [datetime] NULL,
 CONSTRAINT [PK_ARCH_TRA_CTF] PRIMARY KEY CLUSTERED 
(
	[TRA_CTF_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/*TRA TEMPORARY*/
CREATE TABLE [dbo].[ARCH_TRA_TEMPORARY](
	[TRA_TEMPORARY_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DOCUMENT_NUMBER] [char](15) NOT NULL,
	[DOCUMENT_STATUS] [int] NOT NULL,
	[DOCUMENT_NUMBER_RELATED] [char](15) NULL,
	[REASON] [int] NULL,
	[EMPLOYEE_ID] [nvarchar](9) NULL,
	[EMPLOYEE_NAME] [nvarchar](100) NULL,
	[COST_CENTER] [char](10) NULL,
	[GROUP_LEVEL] [int] NULL,
	[ACTUAL_GROUP] [nvarchar](50) NULL,
	[SUPPLY_METHOD] [nvarchar](50) NULL,
	[VEHICLE_TYPE] [nvarchar](50) NULL,
	[POLICE_NUMBER] [nvarchar](50) NULL,
	[MANUFACTURER] [nvarchar](50) NULL,
	[MODEL] [nvarchar](50) NULL,
	[SERIES] [nvarchar](50) NULL,
	[BODY_TYPE] [nvarchar](50) NULL,
	[COLOR] [nvarchar](50) NULL,
	[START_DATE] [date] NULL,
	[END_DATE] [date] NULL,
	[CREATED_BY] [nvarchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [nvarchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[IS_ACTIVE] [bit] NOT NULL,
	[IS_PROJECT] [bit] NULL,
	[LOCATION_CITY] [nvarchar](50) NULL,
	[LOCATION_ADDRESS] [nvarchar](250) NULL,
	[APPROVED_FLEET] [nvarchar](50) NULL,
	[APPROVED_FLEET_DATE] [datetime] NULL,
	[EMPLOYEE_ID_CREATOR] [nvarchar](9) NULL,
	[EMPLOYEE_ID_FLEET_APPROVAL] [nvarchar](9) NULL,
	[VENDOR_NAME] [nvarchar](50) NULL,
	[VENDOR_POLICE_NUMBER] [nvarchar](50) NULL,
	[VENDOR_CHASIS_NUMBER] [nvarchar](50) NULL,
	[VENDOR_ENGINE_NUMBER] [nvarchar](50) NULL,
	[VENDOR_CONTRACT_START_DATE] [date] NULL,
	[VENDOR_CONTRACT_END_DATE] [date] NULL,
	[VENDOR_MANUFACTURER] [nvarchar](50) NULL,
	[VENDOR_MODEL] [nvarchar](50) NULL,
	[VENDOR_SERIES] [nvarchar](50) NULL,
	[VENDOR_TRANSMISSION] [nvarchar](50) NULL,
	[VENDOR_COLOUR] [nvarchar](50) NULL,
	[VENDOR_BODY_TYPE] [nvarchar](50) NULL,
	[VENDOR_AIR_BAG] [bit] NULL,
	[VENDOR_ABS] [bit] NULL,
	[VENDOR_BRANDING] [nvarchar](50) NULL,
	[VENDOR_PURPOSE] [nvarchar](50) NULL,
	[VENDOR_PO_NUMBER] [nvarchar](50) NULL,
	[VENDOR_PO_LINE] [nvarchar](50) NULL,
	[VENDOR_VAT] [bit] NULL,
	[VENDOR_RESTITUTION] [bit] NULL,
	[VENDOR_VENDOR] [nvarchar](100) NULL,
	[CAR_GROUP_LEVEL] [int] NULL,
	[PROJECT_NAME] [nvarchar](50) NULL,
	[CFM_IDLE_ID] [bigint] NULL,
	[VEHICLE_USAGE] [nvarchar](50) NULL,
	[ASSIGNED_TO] [nvarchar](250) NULL,
	[COMMENTS] [nvarchar](255) NULL,
	[PRICE] [decimal](18, 2) NULL,
	[VAT_DECIMAL] [decimal](18, 2) NULL,
	[DATE_SEND_VENDOR] [datetime] NULL,
 CONSTRAINT [PK_ARCH_TRA_TEMPORAR] PRIMARY KEY CLUSTERED 
(
	[TRA_TEMPORARY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/*TRA CTF EXTEND*/
CREATE TABLE [dbo].[ARCH_TRA_CTF_EXTEND](
	[TRA_CTF_EXTEND_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TRA_CTF_ID] [bigint] NULL,
	[NEW_PROPOSED_DATE] [date] NULL,
	[EXTEND_PO_NUMBER] [nvarchar](50) NULL,
	[EXTEND_PO_LINE] [nvarchar](50) NULL,
	[EXTEND_PRICE] [decimal](18, 2) NULL,
	[REASON] [int] NULL,
	[EXTEND_POLICE_NUMBER] [nvarchar](50) NULL,
 CONSTRAINT [PK_ARCH_TRA_CTF_EXTEND] PRIMARY KEY CLUSTERED 
(
	[TRA_CTF_EXTEND_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/*TRA CCF*/
CREATE TABLE [dbo].[ARCH_TRA_CCF](
	[TRA_CCF_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DOCUMENT_NUMBER] [char](15) NOT NULL,
	[DOCUMENT_STATUS] [int] NOT NULL,
	[COMPLAINT_CATEGORY] [int] NOT NULL,
	[EMPLOYEE_ID] [nvarchar](9) NULL,
	[EMPLOYEE_NAME] [nvarchar](100) NULL,
	[EMPLOYEE_ID_COMPLAINT_FOR] [nvarchar](9) NULL,
	[EMPLOYEE_NAME_COMPLAINT_FOR] [nvarchar](100) NULL,
	[POLICE_NUMBER] [nvarchar](50) NULL,
	[POLICE_NUMBER_GS] [nvarchar](50) NULL,
	[CREATED_BY] [nvarchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [nvarchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[IS_ACTIVE] [bit] NOT NULL,
	[LOCATION_CITY] [nvarchar](50) NULL,
	[LOCATION_ADDRESS] [nvarchar](250) NULL,
	[VEHICLE_TYPE] [nvarchar](50) NULL,
	[VEHICLE_USAGE] [nvarchar](50) NULL,
	[MANUFACTURE] [nvarchar](50) NULL,
	[MODEL] [nvarchar](50) NULL,
	[SERIES] [nvarchar](50) NULL,
	[VENDOR] [nvarchar](50) NULL,
	[START_PERIOD] [date] NULL,
	[END_PERIOD] [date] NULL,
	[COORDINATOR_KPI] [int] NULL,
	[VENDOR_KPI] [int] NULL,
	[COORDINATOR_NAME] [nvarchar](50) NULL,
 CONSTRAINT [PK_ARCH_TRA_CCF] PRIMARY KEY CLUSTERED 
(
	[TRA_CCF_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


/*TRA CCF DETAIL*/
CREATE TABLE [dbo].[ARCH_TRA_CCF_DETAIL](
	[TRA_CCF_DETAIL_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TRA_CCF_ID] [bigint] NOT NULL,
	[COMPLAINT_DATE] [date] NULL,
	[COMPLAINT_NOTE] [nvarchar](250) NULL,
	[COMPLAINT_ATT] [nvarchar](100) NULL,
	[COORDINATOR_RESPONSE_DATE] [date] NULL,
	[COORDINATOR_NOTE] [nvarchar](250) NULL,
	[COORDINATOR_PROMISED_DATE] [date] NULL,
	[COORDINATOR_ATT] [nvarchar](100) NULL,
	[VENDOR_RESPONSE_DATE] [date] NULL,
	[VENDOR_NOTE] [nvarchar](250) NULL,
	[VENDOR_PROMISED_DATE] [date] NULL,
	[VENDOR_ATT] [nvarchar](100) NULL,
	[COMPLAINT_URL] [nvarchar](100) NULL,
	[COORDINATOR_URL] [nvarchar](100) NULL,
	[VENDOR_URL] [nvarchar](100) NULL,
 CONSTRAINT [PK_ARCH_TRA_CCF_DETAIL] PRIMARY KEY CLUSTERED 
(
	[TRA_CCF_DETAIL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/*TRA CAF*/
CREATE TABLE [dbo].[ARCH_TRA_CAF](
	[TRA_CAF_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DOCUMENT_NUMBER] [char](15) NOT NULL,
	[DOCUMENT_STATUS] [int] NOT NULL,
	[SIRS_NUMBER] [nvarchar](50) NULL,
	[POLICE_NUMBER] [nvarchar](50) NULL,
	[EMPLOYEE_ID] [nvarchar](9) NULL,
	[EMPLOYEE_NAME] [nvarchar](100) NULL,
	[SUPERVISOR] [nvarchar](100) NULL,
	[AREA] [nvarchar](50) NULL,
	[VENDOR_ID] [int] NULL,
	[VENDOR_NAME] [nvarchar](100) NULL,
	[VEHICLE_MODEL] [nvarchar](50) NULL,
	[INCIDENT_DATE] [date] NULL,
	[INCIDENT_LOCATION] [nvarchar](50) NULL,
	[INCIDENT_DESCRIPTION] [text] NULL,
	[REMARK] [int] NULL,
	[CREATED_BY] [nvarchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [nvarchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[IS_ACTIVE] [bit] NOT NULL,
 CONSTRAINT [PK_ARCH_TRA_CAF] PRIMARY KEY CLUSTERED 
(
	[TRA_CAF_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO


/*TRA CAF PROGRESS*/
CREATE TABLE [dbo].[ARCH_TRA_CAF_PROGRESS](
	[TRA_CAF_PROGRESS_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TRA_CAF_ID] [bigint] NOT NULL,
	[STATUS_ID] [int] NULL,
	[PROGRESS_DATE] [date] NULL,
	[REMARK] [text] NULL,
	[ESTIMATION] [datetime] NULL,
	[ACTUAL] [datetime] NULL,
	[CREATED_BY] [nvarchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [nvarchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
 CONSTRAINT [PK_ARCH_TRA_CAF_PROGRESS] PRIMARY KEY CLUSTERED 
(
	[TRA_CAF_PROGRESS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO