Create procedure [dbo].[GetNoOfVehicleMakeType]
AS BEGIN

	MERGE NO_OF_VEHICLE_MAKE_TYPE_REPORT_DATA AS Target
	USING (
		select MANUFACTURER, BODY_TYPE, COUNT(CHASIS_NUMBER) AS NO_OF_VEHICLE, 
		MONTH(START_CONTRACT) AS REPORT_MONTH, YEAR(START_CONTRACT) AS REPORT_YEAR, START_CONTRACT FROM MST_FLEET
		WHERE (IS_ACTIVE = 1 )
		GROUP BY MANUFACTURER, BODY_TYPE, START_CONTRACT, MONTH(START_CONTRACT)
	) AS Source
	On (Source.MANUFACTURER = Target.MANUFACTURER OR (Source.MANUFACTURER IS NULL AND Target.MANUFACTURER IS NULL))
	AND (Source.BODY_TYPE = Target.BODY_TYPE OR (Source.BODY_TYPE IS NULL AND Target.BODY_TYPE IS NULL))
	AND (Source.REPORT_MONTH = Target.REPORT_MONTH)
	AND (Source.REPORT_YEAR = Target.REPORT_YEAR)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (MANUFACTURER, BODY_TYPE, NO_OF_VEHICLE, REPORT_MONTH, REPORT_YEAR, CREATED_DATE)
		VALUES( Source.MANUFACTURER, Source.BODY_TYPE, Source.NO_OF_VEHICLE, Source.REPORT_MONTH, 
		Source.REPORT_YEAR, Source.START_CONTRACT)
	WHEN MATCHED THEN
		UPDATE SET
		NO_OF_VEHICLE = Source.NO_OF_VEHICLE;

END