--FOR QAS
INSERT INTO ROLE_CONFIG(ROLE_NAME) VALUES('PMI ID UR 3066 OPS FMS ADMINISTRATOR QA IMDL')
INSERT INTO ROLE_CONFIG(ROLE_NAME) VALUES('PMI ID UR 3066 OPS FMS VIEWER QA IMDL')
INSERT INTO ROLE_CONFIG(ROLE_NAME) VALUES('PMI ID UR 3066 OPS FMS HR QA IMDL')
INSERT INTO ROLE_CONFIG(ROLE_NAME) VALUES('PMI ID UR 3066 OPS FMS FLEET QA IMDL')
INSERT INTO ROLE_CONFIG(ROLE_NAME) VALUES('PMI ID UR 3066 OPS FMS IS SUPPORT QA IMDL')

--FOR PRODUCTION
--INSERT INTO ROLE_CONFIG(ROLE_NAME) VALUES('PMI ID UR 3066 OPS FMS ADMINISTRATOR PRD IMDL')
--INSERT INTO ROLE_CONFIG(ROLE_NAME) VALUES('PMI ID UR 3066 OPS FMS VIEWER PRD IMDL')
--INSERT INTO ROLE_CONFIG(ROLE_NAME) VALUES('PMI ID UR 3066 OPS FMS HR PRD IMDL')
--INSERT INTO ROLE_CONFIG(ROLE_NAME) VALUES('PMI ID UR 3066 OPS FMS FLEET PRD IMDL')
--INSERT INTO ROLE_CONFIG(ROLE_NAME) VALUES('PMI ID UR 3066 OPS FMS IS SUPPORT PRD IMDL')




















