--FOR QAS
--INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
--VALUES('USER_ROLE','PMI ID UR 3066 OPS FMS ADMINISTRATOR QA IMDL', 'PMI ID UR 3066 OPS FMS ADMINISTRATOR QA IMDL', 'SYSTEM', getdate(),1)
--INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
--VALUES('USER_ROLE','PMI ID UR 3066 OPS FMS VIEWER QA IMDL', 'PMI ID UR 3066 OPS FMS VIEWER QA IMDL', 'SYSTEM', getdate(),1)
--INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
--VALUES('USER_ROLE','PMI ID UR 3066 OPS FMS HR QA IMDL', 'PMI ID UR 3066 OPS FMS HR QA IMDL', 'SYSTEM', getdate(),1)
--INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
--VALUES('USER_ROLE','PMI ID UR 3066 OPS FMS FLEET QA IMDL', 'PMI ID UR 3066 OPS FMS FLEET QA IMDL', 'SYSTEM', getdate(),1)





--FOR PRODUCTION
INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('USER_ROLE','PMI ID UR 3066 OPS FMS COM. FINANCE MANAGER PRD IMDL', 'PMI ID UR 3066 OPS FMS COM. FINANCE MANAGER PRD IMDL', 'SYSTEM', getdate(),1)
INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('USER_ROLE','PMI ID UR 3066 OPS FMS OPS. FINANCE MANAGER PRD IMDL', 'PMI ID UR 3066 OPS FMS OPS. FINANCE MANAGER PRD IMDL', 'SYSTEM', getdate(),1)
INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('USER_ROLE','PMI ID UR 3066 OPS FMS RDE/MRD LOGISTIC PRD IMDL', 'PMI ID UR 3066 OPS FMS RDE/MRD LOGISTIC PRD IMDL', 'SYSTEM', getdate(),1)
INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('USER_ROLE','PMI ID UR 3066 OPS FMS LOGISTIC & DIST. MANAGER PRD IMDL', 'PMI ID UR 3066 OPS FMS LOGISTIC & DIST. MANAGER PRD IMDL', 'SYSTEM', getdate(),1)
INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('USER_ROLE','PMI ID UR 3066 OPS FMS FLEET SPV PRD IMDL', 'PMI ID UR 3066 OPS FMS FLEET SPV PRD IMDL', 'SYSTEM', getdate(),1)
INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('USER_ROLE','PMI ID UR 3066 OPS FMS HR SPV PRD IMDL', 'PMI ID UR 3066 OPS FMS HR SPV PRD IMDL', 'SYSTEM', getdate(),1)
INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('USER_ROLE','PMI ID UR 3066 OPS FMS FLEET MANAGER PRD IMDL', 'PMI ID UR 3066 OPS FMS FLEET MANAGER PRD IMDL', 'SYSTEM', getdate(),1)
INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('USER_ROLE','PMI ID UR 3066 OPS FMS FLEET STAFF PRD IMDL', 'PMI ID UR 3066 OPS FMS FLEET STAFF PRD IMDL', 'SYSTEM', getdate(),1)
INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('USER_ROLE','PMI ID UR 3066 OPS FMS HR MANAGER PRD IMDL', 'PMI ID UR 3066 OPS FMS HR MANAGER PRD IMDL', 'SYSTEM', getdate(),1)
INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('USER_ROLE','PMI ID UR 3066 OPS FMS FINANCE ZONE PRD IMDL', 'PMI ID UR 3066 OPS FMS FINANCE ZONE PRD IMDL', 'SYSTEM', getdate(),1)
INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('USER_ROLE','PMI ID UR 3066 OPS FMS EHS PRD IMDL', 'PMI ID UR 3066 OPS FMS EHS PRD IMDL', 'SYSTEM', getdate(),1)

