CREATE PROC usp_UpdateMasterFunctionGroup
AS
BEGIN

SET NOCOUNT ON;
MERGE MST_FUNCTION_GROUP AS TARGET
USING FUNCTION_CHANGE AS SOURCE
ON (TARGET.MST_FUNCTION_GROUP_ID = SOURCE.FUNCTION_CHANGE_ID)
WHEN MATCHED AND TARGET.COST_CENTER != SOURCE.COST_CENTER 
THEN UPDATE SET 
TARGET.FUNCTION_NAME = SOURCE.FUNCTION_NEW,
TARGET.COST_CENTER = SOURCE.COST_CENTER
WHEN NOT MATCHED BY TARGET THEN
INSERT(
	FUNCTION_NAME,
	COST_CENTER,
	CREATED_BY,
	CREATED_DATE,
	MODIFIED_BY,
	MODIFIED_DATE,
	IS_ACTIVE)
VALUES(	SOURCE.FUNCTION_NEW,
		SOURCE.COST_CENTER,
		'SYSTEM',
		GETDATE(),
		NULL,
		NULL,
		1);
END
