SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create procedure [dbo].[SP_COPEndRent]
AS BEGIN

	UPDATE MST_FLEET
	set IS_ACTIVE =0
	where iif(VEHICLE_TYPE = NULL,'', UPPER(VEHICLE_TYPE)) = 'BENEFIT'
	AND iif(VEHICLE_USAGE = NULL,'', UPPER(VEHICLE_USAGE)) = 'COP'
	AND GETDATE()>=DATEADD(DAY,1,END_CONTRACT)
	AND IS_ACTIVE=1

END