Create procedure [dbo].[GetAccidentData]
AS BEGIN

	MERGE ACCIDENT_REPORT_DATA AS Target
	USING (
		select COUNT(C.TRA_CAF_ID) AS ACCIDENT_COUNT, F.VEHICLE_TYPE, F.REGIONAL, MONTH(C.CREATED_DATE) AS REPORT_MONTH, 
		YEAR(C.CREATED_DATE) AS REPORT_YEAR, C.CREATED_DATE
		FROM TRA_CAF C JOIN MST_FLEET F ON C.POLICE_NUMBER = F.POLICE_NUMBER
		GROUP BY F.VEHICLE_TYPE, F.REGIONAL, C.CREATED_DATE, MONTH(C.CREATED_DATE)
	) AS Source
	On (Source.REPORT_MONTH = Target.REPORT_MONTH)
	AND (Source.REPORT_YEAR = Target.REPORT_YEAR)
	AND (Source.CREATED_DATE = Target.CREATED_DATE)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (ACCIDENT_COUNT, VEHICLE_TYPE, REGION, REPORT_MONTH, REPORT_YEAR, CREATED_DATE)
		VALUES( Source.ACCIDENT_COUNT, Source.VEHICLE_TYPE, Source.REGIONAL, Source.REPORT_MONTH, 
		Source.REPORT_YEAR, Source.CREATED_DATE);

END