Create procedure [dbo].[GetSalesData]
AS BEGIN

	MERGE SALES_BY_REGION_REPORT_DATA AS Target
	USING (
		select SUM(COST) AS TOTAL_KM, SUM(FO.COST) AS TOTAL_COST, SV.[VALUE] AS STICK, SV.REGION, MONTH(FO.CREATED_DATE) AS REPORT_MONTH, 
		YEAR(FO.CREATED_DATE) AS REPORT_YEAR, FO.CREATED_DATE FROM MST_FUEL_ODOMETER FO 
		JOIN MST_EMPLOYEE E ON FO.EMPLOYEE_ID = E.EMPLOYEE_ID
		JOIN MST_FUNCTION_GROUP CC ON E.COST_CENTER = CC.COST_CENTER
		JOIN MST_LOCATION_MAPPING LM ON E.CITY = LM.LOCATION
		JOIN MST_SALES_VOLUME SV ON LM.REGION = SV.REGION AND MONTH(FO.DATE_OF_COST) = SV.[MONTH] AND YEAR(FL.DATE_OF_COST) = SV.[YEAR] 
		WHERE (FO.VEHICLE_TYPE = 'WTC')
		AND (CC.FUNCTION_NAME = 'SALES')
		GROUP BY SV.[VALUE], SV.REGION, FO.CREATED_DATE, MONTH(FO.CREATED_DATE)
	) AS Source
	On (Source.REPORT_MONTH = Target.REPORT_MONTH)
	AND (Source.REPORT_YEAR = Target.REPORT_YEAR)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (TOTAL_KM, TOTAL_COST, STICK, REGION, REPORT_MONTH, REPORT_YEAR, CREATED_DATE)
		VALUES( Source.TOTAL_KM, Source.TOTAL_COST, Source.STICK, Source.REGION, MONTH(Source.CREATED_DATE), YEAR(Source.CREATED_DATE), Source.CREATED_DATE);

END