use [FMS];
Create procedure [dbo].[GetAccidentData]
AS BEGIN

	MERGE ACCIDENT_REPORT_DATA AS Target
	USING (
		select COUNT(TRA_CAF_ID) AS ACCIDENT_COUNT, VEHICLE_TYPE, REGION, MONTH(CREATED_DATE) AS REPORT_MONTH, 
		YEAR(CREATED_DATE) AS REPORT_YEAR, CREATED_DATE
		FROM TRA_CAF
		GROUP BY VEHICLE_TYPE, REGION, REPORT_MONTH
	) AS Source
	On (Source.MST_FLEET_ID = Target.MST_FLEET_ID)
	AND (Source.CREATED_DATE = Target.CREATED_DATE)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (ACCIDENT_COUNT, VEHICLE_TYPE, REGION, REPORT_MONTH, REPORT_YEAR, CREATED_DATE)
		VALUES( Source.ACCIDENT_COUNT, Source.VEHICLE_TYPE, Source.REGION, Source.REPORT_MONTH, 
		Source.REPORT_YEAR, Source.CREATED_DATE);

END