use [FMS];
Create procedure [dbo].[GetCFMIdleVehicle]
AS BEGIN

	MERGE CFM_IDLE_REPORT_DATA AS Target
	USING (
		select MST_FLEET_ID, POLICE_NUMBER, MANUFACTURER, MODEL, SERIES, BODY_TYPE, COLOR, GROUP_LEVEL, START_CONTRACT, 
		END_CONTRACT, SUPPLY_METHOD, VENDOR, COST_CENTER, TRANSMISSION, FUEL_TYPE, START_IDLE, END_IDLE, 
		MONTHLY_HMS_INSTALLMENT, CREATED_DATE FROM MST_FLEET
		WHERE (VEHICLE_USAGE = 'CFM IDLE')
	) AS Source
	On (Source.MST_FLEET_ID = Target.ID)
	AND (Source.CREATED_DATE = Target.CREATED_DATE)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT ( MST_FLEET_ID, POLICE_NUMBER, MANUFACTURER, MODEL, SERIES, BODY_TYPE, COLOR, GROUP_LEVEL, START_CONTRACT, 
		END_CONTRACT, SUPPLY_METHOD, VENDOR, COST_CENTER, TRANSMISSION, FUEL_TYPE, START_IDLE, END_IDLE, 
		MONTHLY_INSTALLMENT, REPORT_MONTH, REPORT_YEAR, CREATED_DATE)
		VALUES( Source.MST_FLEET_ID, Source.POLICE_NUMBER, Source.MANUFACTURER, Source.MODEL, Source.SERIES
		, Source.BODY_TYPE, Source.COLOR, Source.GROUP_LEVEL, Source.START_CONTRACT, Source.END_CONTRACT
		, Source.SUPPLY_METHOD, Source.VENDOR, Source.COST_CENTER, Source.TRANSMISSION, Source.FUEL_TYPE
		, Source.START_IDLE, Source.END_IDLE, Source.MONTHLY_HMS_INSTALLMENT, MONTH(Source.CREATED_DATE), 
		YEAR(Source.CREATED_DATE), Source.CREATED_DATE);

END