use [FMS];
Create procedure [dbo].[GetFuelCostData]
AS BEGIN

	MERGE FUEL_COST_REPORT_DATA AS Target
	USING (
		select SUM(COST) AS TOTAL_FUEL_COST, VEHICLE_TYPE, [FUNCTION], REGIONAL, MONTH(CREATED_DATE) AS REPORT_MONTH, 
		YEAR(CREATED_DATE) AS REPORT_YEAR, CREATED_DATE FROM MST_FUEL_ODOMETER FO JOIN MST_FLEET FL ON FO.POLICE_NUMBER = FL.POLICE_NUMBER
		WHERE (IS_ACTIVE = 1 )
		GROUP BY VEHICLE_TYPE, , REPORT_MONTH
	) AS Source
	
	On (Source.VEHICLE_TYPE = Target.VEHICLE_TYPE OR (Source.VEHICLE_TYPE IS NULL AND Target.VEHICLE_TYPE IS NULL))
	AND (Source.[FUNCTION] = Target.[FUNCTION] OR (Source.[FUNCTION] IS NULL AND Target.[FUNCTION] IS NULL))
	AND (Source.REGIONAL = Target.REGION OR (Source.REGIONAL IS NULL AND Target.REGION IS NULL))
	AND (Source.CREATED_DATE = Target.CREATED_DATE)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (TOTAL_FUEL_COST, VEHICLE_TYPE, [FUNCTION], REGION, REPORT_MONTH, REPORT_YEAR, CREATED_DATE)
		VALUES( Source.TOTAL_FUEL_COST, Source.VEHICLE_TYPE, Source.[FUNCTION], Source.REGION, MONTH(Source.CREATED_DATE), 
		YEAR(Source.CREATED_DATE), Source.CREATED_DATE);

END