Create procedure [dbo].[GetFuelCostData]
AS BEGIN

	MERGE FUEL_COST_BY_FUNC_REPORT_DATA AS Target
	USING (
		select SUM(FO.COST) AS TOTAL_FUEL_COST, FO.VEHICLE_TYPE, CC.FUNCTION_NAME, LM.REGION, 
		MONTH(FO.POSTED_TIME) AS REPORT_MONTH, YEAR(FO.POSTED_TIME) AS REPORT_YEAR, FO.POSTED_TIME 
		FROM MST_FUEL_ODOMETER FO
		JOIN MST_EMPLOYEE E ON FO.EMPLOYEE_ID = E.EMPLOYEE_ID
		JOIN MST_FUNCTION_GROUP CC ON E.COST_CENTER = CC.COST_CENTER
		JOIN MST_LOCATION_MAPPING LM ON E.CITY = LM.LOCATION
		GROUP BY FO.VEHICLE_TYPE, CC.FUNCTION_NAME, LM.REGION, FO.POSTED_TIME, MONTH(FO.POSTED_TIME)
	) AS Source
	
	On (Source.VEHICLE_TYPE = Target.VEHICLE_TYPE OR (Source.VEHICLE_TYPE IS NULL AND Target.VEHICLE_TYPE IS NULL))
	AND (Source.FUNCTION_NAME = Target.[FUNCTION] OR (Source.FUNCTION_NAME IS NULL AND Target.[FUNCTION] IS NULL))
	AND (Source.REGION = Target.REGION OR (Source.REGION IS NULL AND Target.REGION IS NULL))
	AND (Source.POSTED_TIME = Target.CREATED_DATE)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (TOTAL_FUEL_COST, VEHICLE_TYPE, [FUNCTION], REGION, REPORT_MONTH, REPORT_YEAR, CREATED_DATE)
		VALUES( Source.TOTAL_FUEL_COST, Source.VEHICLE_TYPE, Source.FUNCTION_NAME, Source.REGION, 
		MONTH(Source.POSTED_TIME), YEAR(Source.POSTED_TIME), Source.POSTED_TIME);

END