IF EXISTS(SELECT 1 FROM sys.procedures 
          WHERE Name = 'GetKPIData')
BEGIN
    DROP PROCEDURE [dbo].[GetKPIData]
END
GO
CREATE procedure [dbo].[GetKPIData]
AS BEGIN
	MERGE KPI_REPORT_DATA AS Target
	USING (
		select 'CSF' AS FORM_TYPE, C.EMPLOYEE_ID, C.EMPLOYEE_NAME, C.EFFECTIVE_DATE, R.REASON, 
		(SELECT EMP.ADDRESS FROM MST_EMPLOYEE EMP WHERE EMP.EMPLOYEE_ID = C.EMPLOYEE_ID) AS LOCATION_ADDRESS,
		(SELECT SETT.SETTING_NAME FROM MST_SETTING SETT WHERE SETT.MST_SETTING_ID = 
			CASE WHEN C.VEHICLE_USAGE = '' THEN ''
			ELSE
				CONVERT(INT,C.VEHICLE_USAGE)
			END
			)
				AS VEHICLE_USAGE
		, C.GROUP_LEVEL, C.MODEL, C.COLOUR, C.POLICE_NUMBER, 
		(SELECT rem.REMARK FROM MST_REMARK rem WHERE rem.MST_REMARK_ID = C.REMARK) AS REMARK, C.CREATED_DATE, C.TRA_CSF_ID AS TRA_ID, 
		(SELECT EMP.COST_CENTER FROM MST_EMPLOYEE EMP WHERE EMP.EMPLOYEE_ID = C.EMPLOYEE_ID) AS COST_CENTER
		FROM TRA_CSF C JOIN MST_REASON R ON C.REASON = R.MST_REASON_ID 
		WHERE UPPER(C.VEHICLE_TYPE) = '1'
	) AS Source
	On (Source.EMPLOYEE_ID = Target.EMPLOYEE_ID)
	AND (Source.CREATED_DATE = Target.CREATED_DATE)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT ( FORM_TYPE, EMPLOYEE_ID, EMPLOYEE_NAME, EFFECTIVE_DATE, REASON, ADDRESS, 
		VEHICLE_USAGE, VEHICLE_GROUP_LEVEL, VEHICLE_MODEL, COLOR, POLICE_NUMBER, REMARK, REPORT_MONTH, REPORT_YEAR, CREATED_DATE,TRA_ID, COST_CENTER)
		VALUES( Source.FORM_TYPE, Source.EMPLOYEE_ID, Source.EMPLOYEE_NAME, Source.EFFECTIVE_DATE, Source.REASON
		, Source.LOCATION_ADDRESS, Source.VEHICLE_USAGE, Source.GROUP_LEVEL, Source.MODEL
		, Source.COLOUR, Source.POLICE_NUMBER, Source.REMARK, MONTH(Source.CREATED_DATE), 
		YEAR(Source.CREATED_DATE), Source.CREATED_DATE, Source.TRA_ID, Source.COST_CENTER);
		
	MERGE KPI_REPORT_DATA AS Target
	USING (
		select 'CTF' AS FORM_TYPE, C.EMPLOYEE_ID, C.EMPLOYEE_NAME, C.EFFECTIVE_DATE, R.REASON, 
		(SELECT EMP.ADDRESS FROM MST_EMPLOYEE EMP WHERE EMP.EMPLOYEE_ID = C.EMPLOYEE_ID) AS LOCATION_ADDRESS,
		C.VEHICLE_USAGE, C.GROUP_LEVEL, F.MODEL, F.COLOR, C.POLICE_NUMBER, 
		(SELECT rem.REMARK FROM MST_REMARK rem WHERE rem.MST_REMARK_ID = c.REMARK) AS REMARK, C.CREATED_DATE, C.TRA_CTF_ID AS TRA_ID,
		(SELECT EMP.COST_CENTER FROM MST_EMPLOYEE EMP WHERE EMP.EMPLOYEE_ID = C.EMPLOYEE_ID) AS COST_CENTER
		FROM TRA_CTF C JOIN MST_REASON R ON C.REASON = R.MST_REASON_ID JOIN MST_FLEET F ON C.POLICE_NUMBER = F.POLICE_NUMBER AND C.EMPLOYEE_ID = F.EMPLOYEE_ID
		WHERE UPPER(C.VEHICLE_TYPE) = 'BENEFIT'
	) AS Source
	On (Source.POLICE_NUMBER = Target.POLICE_NUMBER)
	AND (Source.EMPLOYEE_ID = TARGET.EMPLOYEE_ID)
	AND (Source.CREATED_DATE = Target.CREATED_DATE)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT ( FORM_TYPE, EMPLOYEE_ID, EMPLOYEE_NAME, EFFECTIVE_DATE, REASON, ADDRESS, 
		VEHICLE_USAGE, VEHICLE_GROUP_LEVEL, VEHICLE_MODEL, COLOR, POLICE_NUMBER, REMARK, REPORT_MONTH, REPORT_YEAR, CREATED_DATE, TRA_ID,COST_CENTER)
		VALUES( Source.FORM_TYPE, Source.EMPLOYEE_ID, Source.EMPLOYEE_NAME, Source.EFFECTIVE_DATE, Source.REASON
		, Source.LOCATION_ADDRESS, Source.VEHICLE_USAGE, Source.GROUP_LEVEL, Source.MODEL, Source.COLOR
		, Source.POLICE_NUMBER, Source.REMARK, MONTH(Source.CREATED_DATE), YEAR(Source.CREATED_DATE), Source.CREATED_DATE, Source.TRA_ID,Source.COST_CENTER);
				
	MERGE KPI_REPORT_DATA AS Target
	USING (
		select 'CRF' AS FORM_TYPE, C.EMPLOYEE_ID, C.EMPLOYEE_NAME, C.EFFECTIVE_DATE, 
		(SELECT EMP.ADDRESS FROM MST_EMPLOYEE EMP WHERE EMP.EMPLOYEE_ID = C.EMPLOYEE_ID) AS LOCATION_ADDRESS,
		C.LOCATION_OFFICE,C.LOCATION_OFFICE_NEW, C.VEHICLE_USAGE, (SELECT EMP.GROUP_LEVEL FROM MST_EMPLOYEE EMP WHERE EMP.EMPLOYEE_ID = C.EMPLOYEE_ID) AS GROUP_LEVEL, C.MODEL, F.COLOR, F.POLICE_NUMBER, 
		(SELECT rem.REMARK FROM MST_REMARK rem WHERE rem.MST_REMARK_ID = c.REMARK) AS REMARK, C.CREATED_DATE, C.TRA_CRF_ID AS TRA_ID,
		(SELECT EMP.COST_CENTER FROM MST_EMPLOYEE EMP WHERE EMP.EMPLOYEE_ID = C.EMPLOYEE_ID) AS COST_CENTER
		FROM TRA_CRF C JOIN MST_FLEET F ON C.MST_FLEET_ID = F.MST_FLEET_ID
		WHERE UPPER(C.VEHICLE_TYPE) = 'BENEFIT'
	) AS Source
	On (Source.POLICE_NUMBER = Target.POLICE_NUMBER)
	AND (Source.EMPLOYEE_ID = TARGET.EMPLOYEE_ID)
	AND (Source.CREATED_DATE = Target.CREATED_DATE)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT ( FORM_TYPE, EMPLOYEE_ID, EMPLOYEE_NAME, EFFECTIVE_DATE,ADDRESS, PREVIOUS_BASE_TOWN, NEW_BASE_TOWN, 
		VEHICLE_USAGE, VEHICLE_GROUP_LEVEL, VEHICLE_MODEL, COLOR, POLICE_NUMBER, REMARK, REPORT_MONTH, REPORT_YEAR, CREATED_DATE, TRA_ID,COST_CENTER)
		VALUES( Source.FORM_TYPE, Source.EMPLOYEE_ID, Source.EMPLOYEE_NAME, Source.EFFECTIVE_DATE
		, Source.LOCATION_ADDRESS, Source.LOCATION_OFFICE, Source.LOCATION_OFFICE_NEW, Source.VEHICLE_USAGE, Source.GROUP_LEVEL, Source.MODEL
		, Source.COLOR, Source.POLICE_NUMBER, Source.REMARK, MONTH(Source.CREATED_DATE), 
		YEAR(Source.CREATED_DATE), Source.CREATED_DATE,Source.TRA_ID, Source.COST_CENTER);
END
