Create procedure [dbo].[GetLiterByFunction]
AS BEGIN

	MERGE LITER_BY_FUNC_REPORT_DATA AS Target
	USING (
		select SUM(FUEL_AMOUNT) AS TOTAL_LITER, FL.VEHICLE_TYPE, FL.VEHICLE_FUNCTION, 
		MONTH(FO.CREATED_DATE) AS REPORT_MONTH, YEAR(FO.CREATED_DATE) AS REPORT_YEAR, FO.CREATED_DATE
		FROM MST_FUEL_ODOMETER FO JOIN MST_FLEET FL ON FO.POLICE_NUMBER = FL.POLICE_NUMBER
		GROUP BY FL.VEHICLE_TYPE, FL.VEHICLE_FUNCTION, FO.CREATED_DATE, MONTH(FO.CREATED_DATE)
	) AS Source
	On (Source.REPORT_MONTH = Target.REPORT_MONTH)
	AND (Source.REPORT_YEAR = Target.REPORT_YEAR)
	AND (Source.CREATED_DATE = Target.CREATED_DATE)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (TOTAL_LITER, VEHICLE_TYPE, [FUNCTION], REPORT_MONTH, REPORT_YEAR, CREATED_DATE)
		VALUES( Source.TOTAL_LITER, Source.VEHICLE_TYPE, Source.VEHICLE_FUNCTION, 
		Source.REPORT_MONTH, Source.REPORT_YEAR, Source.CREATED_DATE);

END