Create procedure [dbo].[GetLiterByFunction]
AS BEGIN

	MERGE LITER_BY_FUNC_REPORT_DATA AS Target
	USING (
		select SUM(FUEL_AMOUNT) AS TOTAL_LITER, FO.VEHICLE_TYPE, CC.FUNCTION_NAME, 
		MONTH(FO.POSTED_TIME) AS REPORT_MONTH, YEAR(FO.POSTED_TIME) AS REPORT_YEAR, FO.POSTED_TIME
		FROM MST_FUEL_ODOMETER FO
		JOIN MST_EMPLOYEE E ON FO.EMPLOYEE_ID = E.EMPLOYEE_ID
		JOIN MST_FUNCTION_GROUP CC ON E.COST_CENTER = CC.COST_CENTER
		GROUP BY FO.VEHICLE_TYPE, CC.FUNCTION_NAME, FO.POSTED_TIME, MONTH(FO.POSTED_TIME)
	) AS Source
	On (Source.REPORT_MONTH = Target.REPORT_MONTH)
	AND (Source.REPORT_YEAR = Target.REPORT_YEAR)
	AND (Source.POSTED_TIME = Target.CREATED_DATE)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (TOTAL_LITER, VEHICLE_TYPE, [FUNCTION], REPORT_MONTH, REPORT_YEAR, CREATED_DATE)
		VALUES( Source.TOTAL_LITER, Source.VEHICLE_TYPE, Source.FUNCTION_NAME, 
		Source.REPORT_MONTH, Source.REPORT_YEAR, Source.POSTED_TIME);

END