use [FMS];
Create procedure [dbo].[GetSalesData]
AS BEGIN

	MERGE SALES_BY_REGION_REPORT_DATA AS Target
	USING (
		select SUM(COST) AS TOTAL_KM, SUM(FO.COST) AS TOTAL_COST, SUM(SV.[VALUE]) AS STICK, SV.REGION, MONTH(FO.CREATED_DATE) AS REPORT_MONTH, 
		YEAR(FO.CREATED_DATE) AS REPORT_YEAR, FO.CREATED_DATE FROM MST_FUEL_ODOMETER FO JOIN MST_SALES_VOLUME SV ON MONTH(FO.CREATED_DATE) = MONTH(SV.CREATED_DATE)
		AND YEAR(FO.CREATED_DATE) = YEAR(SV.CREATED_DATE) JOIN MST_FLEET FL ON FO.POLICE_NUMBER = FL.POLICE_NUMBER
		WHERE (IS_ACTIVE = 1 )
		AND (FL.VEHICLE_TYPE = 'WTC')
		AND (SV.[FUNCTION] = 'Sales')
		GROUP BY REPORT_MONTH
	) AS Source
	On (Source.REPORT_MONTH = Target.REPORT_MONTH)
	AND (Source.REPORT_YEAR = Target.REPORT_YEAR)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (TOTAL_KM, TOTAL_COST, STICK, REGION, REPORT_MONTH, REPORT_YEAR, CREATED_DATE)
		VALUES( Source.TOTAL_KM, Source.TOTAL_COST, Source.STICK, Source.REGION, MONTH(Source.CREATED_DATE), YEAR(Source.CREATED_DATE), Source.CREATED_DATE);

END