Create procedure [dbo].[GetLiterByFunction]
AS BEGIN

	MERGE LITER_BY_FUNC_REPORT_DATA AS Target
	USING (
		select SUM(FUEL_AMOUNT) AS TOTAL_LITER, FO.VEHICLE_TYPE, CC.FUNCTION_NAME, LM.REGION, 
		FO.DATE_OF_COST
		FROM MST_FUEL_ODOMETER FO
		JOIN MST_EMPLOYEE E ON FO.EMPLOYEE_ID = E.EMPLOYEE_ID
		JOIN MST_FUNCTION_GROUP CC ON E.COST_CENTER = CC.COST_CENTER
		JOIN MST_LOCATION_MAPPING LM ON E.BASETOWN = LM.BASETOWN
		GROUP BY FO.VEHICLE_TYPE, CC.FUNCTION_NAME, LM.REGION, FO.DATE_OF_COST
	) AS Source
	On (Source.DATE_OF_COST = Target.CREATED_DATE)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (TOTAL_LITER, VEHICLE_TYPE, [FUNCTION], REGION, REPORT_MONTH, REPORT_YEAR, CREATED_DATE)
		VALUES( Source.TOTAL_LITER, Source.VEHICLE_TYPE, Source.FUNCTION_NAME, Source.REGION, 
		Month(Source.DATE_OF_COST), Year(Source.DATE_OF_COST), Source.DATE_OF_COST);

END