Create procedure [dbo].[GetLeaseCostData]
AS BEGIN

	-- CSF --
    MERGE LEASE_COST_BY_FUNC_REPORT_DATA AS Target
    USING (
      SELECT TRA_CSF.CREATED_DATE AS CREATED_DATE, MST_FLEET.VEHICLE_FUNCTION AS VEHICLE_FUNCTION, MST_FLEET.REGIONAL, MST_PRICELIST.PRICE AS PRICE
      FROM TRA_CSF
      INNER JOIN MST_FLEET ON MST_FLEET.ENGINE_NUMBER = TRA_CSF.VENDOR_ENGINE_NUMBER
        AND MST_FLEET.CHASIS_NUMBER = TRA_CSF.VENDOR_CHASIS_NUMBER
      INNER JOIN MST_PRICELIST ON MST_PRICELIST.MANUFACTURER = MST_FLEET.MANUFACTURER
        AND MST_PRICELIST.MODEL = MST_FLEET.MODEL
        AND MST_PRICELIST.SERIES = MST_FLEET.SERIES
        AND MST_PRICELIST.YEAR = MST_FLEET.VEHICLE_YEAR
      WHERE TRA_CSF.IS_ACTIVE = 1
    ) AS Source
    ON (Source.PRICE = Target.TOTAL_LEASE_COST OR (Source.PRICE IS NULL AND Target.TOTAL_LEASE_COST IS NULL))
      AND (Source.VEHICLE_FUNCTION = Target.[FUNCTION] OR (Source.VEHICLE_FUNCTION IS NULL AND Target.[FUNCTION] IS NULL))
      AND (Source.REGIONAL = Target.REGION OR (Source.REGIONAL IS NULL AND Target.REGION IS NULL))
      AND (MONTH(Source.CREATED_DATE) = Target.REPORT_MONTH OR (Source.CREATED_DATE IS NULL AND Target.REPORT_MONTH IS NULL))
      AND (YEAR(Source.CREATED_DATE) = Target.REPORT_YEAR OR (Source.CREATED_DATE IS NULL AND Target.REPORT_YEAR IS NULL))
    WHEN NOT MATCHED BY Target THEN
    INSERT ([TOTAL_LEASE_COST]
      ,[FUNCTION]
	  ,[REGION]
      ,[REPORT_MONTH]
      ,[REPORT_YEAR]
      ,[CREATED_DATE])
    VALUES (Source.PRICE
      ,Source.VEHICLE_FUNCTION
	  ,Source.REGIONAL
      ,MONTH(Source.CREATED_DATE)
      ,YEAR(Source.CREATED_DATE)
      ,Source.CREATED_DATE);

    -- Temporary --
    MERGE LEASE_COST_BY_FUNC_REPORT_DATA AS Target
    USING (
      SELECT TRA_TEMPORARY.CREATED_DATE AS CREATED_DATE, MST_FLEET.VEHICLE_FUNCTION AS VEHICLE_FUNCTION, MST_FLEET.REGIONAL, MST_PRICELIST.PRICE AS PRICE
      FROM TRA_TEMPORARY
      INNER JOIN MST_FLEET ON MST_FLEET.ENGINE_NUMBER = TRA_TEMPORARY.VENDOR_ENGINE_NUMBER
        AND MST_FLEET.CHASIS_NUMBER = TRA_TEMPORARY.VENDOR_CHASIS_NUMBER
      INNER JOIN MST_PRICELIST ON MST_PRICELIST.MANUFACTURER = MST_FLEET.MANUFACTURER
        AND MST_PRICELIST.MODEL = MST_FLEET.MODEL
        AND MST_PRICELIST.SERIES = MST_FLEET.SERIES
        AND MST_PRICELIST.YEAR = MST_FLEET.VEHICLE_YEAR
      WHERE TRA_TEMPORARY.IS_ACTIVE = 1
    ) AS Source
    ON (Source.PRICE = Target.TOTAL_LEASE_COST OR (Source.PRICE IS NULL AND Target.TOTAL_LEASE_COST IS NULL))
      AND (Source.VEHICLE_FUNCTION = Target.[FUNCTION] OR (Source.VEHICLE_FUNCTION IS NULL AND Target.[FUNCTION] IS NULL))
      AND (Source.REGIONAL = Target.REGION OR (Source.REGIONAL IS NULL AND Target.REGION IS NULL))
      AND (MONTH(Source.CREATED_DATE) = Target.REPORT_MONTH OR (Source.CREATED_DATE IS NULL AND Target.REPORT_MONTH IS NULL))
      AND (YEAR(Source.CREATED_DATE) = Target.REPORT_YEAR OR (Source.CREATED_DATE IS NULL AND Target.REPORT_YEAR IS NULL))
    WHEN NOT MATCHED BY Target THEN
    INSERT ([TOTAL_LEASE_COST]
      ,[FUNCTION]
	  ,[REGION]
      ,[REPORT_MONTH]
      ,[REPORT_YEAR]
      ,[CREATED_DATE])
    VALUES (Source.PRICE
      ,Source.VEHICLE_FUNCTION
      ,Source.REGIONAL
      ,MONTH(Source.CREATED_DATE)
      ,YEAR(Source.CREATED_DATE)
      ,Source.CREATED_DATE);
END
GO