Create procedure [dbo].[GetKPIData]
AS BEGIN

	MERGE KPI_REPORT_DATA AS Target
	USING (
		select 'CSF' AS FORM_TYPE, C.EMPLOYEE_ID, C.EMPLOYEE_NAME, C.EFFECTIVE_DATE, R.REASON, C.LOCATION_ADDRESS,
		C.VEHICLE_USAGE, C.GROUP_LEVEL, C.MODEL, C.COLOUR, C.POLICE_NUMBER, RE.REMARK, C.CREATED_DATE 
		FROM TRA_CSF C JOIN MST_REASON R ON C.REASON = R.MST_REASON_ID JOIN MST_REMARK RE ON C.REMARK = RE.MST_REMARK_ID
	) AS Source
	On (Source.POLICE_NUMBER = Target.POLICE_NUMBER)
	AND (Source.CREATED_DATE = Target.CREATED_DATE)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT ( FORM_TYPE, EMPLOYEE_ID, EMPLOYEE_NAME, EFFECTIVE_DATE, REASON, ADDRESS, 
		VEHICLE_USAGE, VEHICLE_GROUP_LEVEL, VEHICLE_MODEL, COLOR, POLICE_NUMBER, REMARK, REPORT_MONTH, REPORT_YEAR, CREATED_DATE)
		VALUES( Source.FORM_TYPE, Source.EMPLOYEE_ID, Source.EMPLOYEE_NAME, Source.EFFECTIVE_DATE, Source.REASON
		, Source.LOCATION_ADDRESS, Source.VEHICLE_USAGE, Source.GROUP_LEVEL, Source.MODEL
		, Source.COLOUR, Source.POLICE_NUMBER, Source.REMARK, MONTH(Source.CREATED_DATE), 
		YEAR(Source.CREATED_DATE), Source.CREATED_DATE);
		
	MERGE KPI_REPORT_DATA AS Target
	USING (
		select 'CTF' AS FORM_TYPE, C.EMPLOYEE_ID, C.EMPLOYEE_NAME, C.EFFECTIVE_DATE, R.REASON, C.WITHD_ADDRESS,
		C.VEHICLE_USAGE, C.GROUP_LEVEL, F.MODEL, F.COLOR, C.POLICE_NUMBER, RE.REMARK, C.CREATED_DATE 
		FROM TRA_CTF C JOIN MST_REASON R ON C.REASON = R.MST_REASON_ID JOIN MST_FLEET F ON C.POLICE_NUMBER = F.POLICE_NUMBER
		JOIN MST_REMARK RE ON C.REMARK = RE.MST_REMARK_ID
	) AS Source
	On (Source.POLICE_NUMBER = Target.POLICE_NUMBER)
	AND (Source.CREATED_DATE = Target.CREATED_DATE)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT ( FORM_TYPE, EMPLOYEE_ID, EMPLOYEE_NAME, EFFECTIVE_DATE, REASON, ADDRESS, 
		VEHICLE_USAGE, VEHICLE_GROUP_LEVEL, VEHICLE_MODEL, COLOR, POLICE_NUMBER, REMARK, REPORT_MONTH, REPORT_YEAR, CREATED_DATE)
		VALUES( Source.FORM_TYPE, Source.EMPLOYEE_ID, Source.EMPLOYEE_NAME, Source.EFFECTIVE_DATE, Source.REASON
		, Source.WITHD_ADDRESS, Source.VEHICLE_USAGE, Source.GROUP_LEVEL, Source.MODEL, Source.COLOR
		, Source.POLICE_NUMBER, Source.REMARK, MONTH(Source.CREATED_DATE), YEAR(Source.CREATED_DATE), Source.CREATED_DATE);
				
	MERGE KPI_REPORT_DATA AS Target
	USING (
		select 'CRF' AS FORM_TYPE, C.EMPLOYEE_ID, C.EMPLOYEE_NAME, C.EFFECTIVE_DATE, C.LOCATION_OFFICE,
		C.LOCATION_OFFICE_NEW, C.VEHICLE_USAGE, F.GROUP_LEVEL, C.MODEL, F.COLOR, F.POLICE_NUMBER, RE.REMARK, C.CREATED_DATE 
		FROM TRA_CRF C JOIN MST_FLEET F ON C.MST_FLEET_ID = F.MST_FLEET_ID
		JOIN MST_REMARK RE ON C.REMARK = RE.MST_REMARK_ID
	) AS Source
	On (Source.EMPLOYEE_ID = Target.EMPLOYEE_ID)
	AND (Source.CREATED_DATE = Target.CREATED_DATE)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT ( FORM_TYPE, EMPLOYEE_ID, EMPLOYEE_NAME, EFFECTIVE_DATE, PREVIOUS_BASE_TOWN, NEW_BASE_TOWN, 
		VEHICLE_USAGE, VEHICLE_GROUP_LEVEL, VEHICLE_MODEL, COLOR, POLICE_NUMBER, REMARK, REPORT_MONTH, REPORT_YEAR, CREATED_DATE)
		VALUES( Source.FORM_TYPE, Source.EMPLOYEE_ID, Source.EMPLOYEE_NAME, Source.EFFECTIVE_DATE
		, Source.LOCATION_OFFICE, Source.LOCATION_OFFICE_NEW, Source.VEHICLE_USAGE, Source.GROUP_LEVEL, Source.MODEL
		, Source.COLOR, Source.POLICE_NUMBER, Source.REMARK, MONTH(Source.CREATED_DATE), 
		YEAR(Source.CREATED_DATE), Source.CREATED_DATE);

	MERGE KPI_REPORT_DATA AS Target
	USING (
		select 'TEMPORARY' AS FORM_TYPE, C.EMPLOYEE_ID, C.EMPLOYEE_NAME, R.REASON, C.[START_DATE], C.LOCATION_ADDRESS,
		C.VENDOR_CONTRACT_START_DATE, F.GROUP_LEVEL, C.MODEL, C.COLOR, F.POLICE_NUMBER, C.CREATED_DATE 
		FROM TRA_TEMPORARY C JOIN MST_FLEET F ON C.POLICE_NUMBER = F.POLICE_NUMBER
		JOIN MST_REASON R ON C.REASON = R.MST_REASON_ID
	) AS Source
	On (Source.EMPLOYEE_ID = Target.EMPLOYEE_ID)
	AND (Source.CREATED_DATE = Target.CREATED_DATE)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT ( FORM_TYPE, EMPLOYEE_ID, EMPLOYEE_NAME, EFFECTIVE_DATE, REASON, ADDRESS, VEHICLE_GROUP_LEVEL, 
		VEHICLE_MODEL, COLOR, POLICE_NUMBER, REPORT_MONTH, REPORT_YEAR, CREATED_DATE)
		VALUES( Source.FORM_TYPE, Source.EMPLOYEE_ID, Source.EMPLOYEE_NAME, Source.[START_DATE], Source.REASON
		, Source.LOCATION_ADDRESS, Source.GROUP_LEVEL, Source.MODEL, Source.COLOR, Source.POLICE_NUMBER
		, MONTH(Source.CREATED_DATE), YEAR(Source.CREATED_DATE), Source.CREATED_DATE);

END