use [FMS];
Create procedure [dbo].[GetFuelData]
AS BEGIN

	MERGE FUEL_REPORT_DATA AS Target
	USING (
		select FO.POLICE_NUMBER, SUM(FO.FUEL_AMOUNT) AS LITER, MAX(FO.LAST_KM) AS ODOMETER, SUM(FO.COST) AS TOTAL_COST, FL.FUEL_TYPE, FL.COST_CENTER, 
		FL.VEHICLE_FUNCTION, FL.MANUFACTURER, FL.MODEL, FL.SERIES, FL.BODY_TYPE, FL.VEHICLE_TYPE, FL.VEHICLE_USAGE, 
		LM.BASE_TOWN, MONTH(CREATED_DATE) AS REPORT_MONTH, YEAR(CREATED_DATE) AS REPORT_YEAR, FO.CREATED_DATE, FL.MST_FLEET_ID
		FROM MST_FUEL_ODOMETER FO JOIN MST_FLEET FL ON FO.POLICE_NUMBER = FL.POLICE_NUMBER JOIN MST_LOCATION_MAPPING LM ON
		FL.CITY = LM.LOCATION
		GROUP BY REPORT_MONTH, FO.POLICE_NUMBER, FL.FUEL_TYPE, FL.COST_CENTER, FL.VEHICLE_FUNCTION, FL.MANUFACTURER, FL.MODEL, 
		FL.SERIES, FL.BODY_TYPE, FL.VEHICLE_TYPE, FL.VEHICLE_USAGE, LM.BASETOWN
	) AS Source
	On (Source.MST_FLEET_ID = Target.MST_FLEET_ID)
	AND (Source.CREATED_DATE = Target.CREATED_DATE)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (POLICE_NUMBER, LITER, ODOMETER, COST, FUEL_TYPE, COST_CENTER, [FUNCTION], MANUFACTURER, MODEL, 
		SERIES, BODY_TYPE, VEHICLE_TYPE, VEHICLE_USAGE, LOCATION, REPORT_MONTH, REPORT_YEAR, CREATED_DATE, MST_FLEET_ID)
		VALUES( Source.POLICE_NUMBER, Source.LITER, Source.ODOMETER, Source.TOTAL_COST, Source.FUEL_TYPE, Source.COST_CENTER, 
		Source.VEHICLE_FUNCTION, Source.MANUFACTURER, Source.MODEL, Source.SERIES, Source.BODY_TYPE, Source.VEHICLE_TYPE, 
		Source.VEHICLE_USAGE, Source.BASE_TOWN, MONTH(Source.CREATED_DATE), YEAR(Source.CREATED_DATE), Source.CREATED_DATE, 
		Source.MST_FLEET_ID);

END