Create procedure [dbo].[GetFuelData]
AS BEGIN

	MERGE FUEL_REPORT_DATA AS Target
	USING (
		select FO.POLICE_NUMBER, SUM(FO.FUEL_AMOUNT) AS LITER, MAX(FO.LAST_KM) AS ODOMETER, SUM(FO.COST) AS TOTAL_COST, FL.FUEL_TYPE, FL.COST_CENTER, 
		FL.VEHICLE_FUNCTION, FL.MANUFACTURER, FL.MODEL, FL.SERIES, FL.BODY_TYPE, FL.VEHICLE_TYPE, FL.VEHICLE_USAGE, 
		LM.BASETOWN, MONTH(FO.POSTED_TIME) AS REPORT_MONTH, YEAR(FO.POSTED_TIME) AS REPORT_YEAR, FO.POSTED_TIME
		FROM MST_FUEL_ODOMETER FO JOIN MST_FLEET FL ON FO.EMPLOYEE_ID = FL.EMPLOYEE_ID JOIN MST_LOCATION_MAPPING LM ON
		upper(FL.CITY) = upper(LM.LOCATION)
		GROUP BY MONTH(FO.CREATED_DATE), FO.POLICE_NUMBER, FL.FUEL_TYPE, FL.COST_CENTER, FL.VEHICLE_FUNCTION, FL.MANUFACTURER, FL.MODEL, 
		FL.SERIES, FL.BODY_TYPE, FL.VEHICLE_TYPE, FL.VEHICLE_USAGE, LM.BASETOWN, FO.POSTED_TIME
	) AS Source
	On (Source.POLICE_NUMBER = Target.POLICE_NUMBER)
	AND (Source.POSTED_TIME = Target.CREATED_DATE)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (POLICE_NUMBER, LITER, ODOMETER, COST, FUEL_TYPE, COST_CENTER, [FUNCTION], MANUFACTURER, MODEL, 
		SERIES, BODY_TYPE, VEHICLE_TYPE, VEHICLE_USAGE, LOCATION, REPORT_MONTH, REPORT_YEAR, CREATED_DATE)
		VALUES( Source.POLICE_NUMBER, Source.LITER, Source.ODOMETER, Source.TOTAL_COST, Source.FUEL_TYPE, Source.COST_CENTER, 
		Source.VEHICLE_FUNCTION, Source.MANUFACTURER, Source.MODEL, Source.SERIES, Source.BODY_TYPE, Source.VEHICLE_TYPE, 
		Source.VEHICLE_USAGE, Source.BASETOWN, MONTH(Source.POSTED_TIME), YEAR(Source.POSTED_TIME), Source.POSTED_TIME);

END