use [FMS];
Create procedure [dbo].[GetPOData]
AS BEGIN

	MERGE PO_REPORT_DATA AS Target
	USING (
		select POLICE_NUMBER, SUPPLY_METHOD, EMPLOYEE_NAME, COST_CENTER, MANUFACTURER, MODEL, SERIES, 
		BODY_TYPE, COLOR, CHASIS_NUMBER, ENGINE_NUMBER, VEHICLE_TYPE, VEHICLE_USAGE, PO_NUMBER,
		PO_LINE, CREATED_DATE, FL.MST_FLEET_ID
		FROM MST_FLEET FL
		GROUP BY VEHICLE_FUNCTION
	) AS Source
	On (Source.MST_FLEET_ID = Target.MST_FLEET_ID)
	AND (Source.CREATED_DATE = Target.CREATED_DATE)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (POLICE_NUMBER, SUPPLY_METHOD, EMPLOYEE_NAME, COST_CENTER, MANUFACTURER, MODEL, SERIES, BODY_TYPE, 
		COLOR, CHASIS_NUMBER, ENGINE_NUMBER, VEHICLE_TYPE, VEHICLE_USAGE, PO_NUMBER, PO_LINE, REPORT_MONTH, 
		REPORT_YEAR, CREATED_DATE, MST_FLEET_ID)
		VALUES( Source.POLICE_NUMBER, Source.SUPPLY_METHOD, Source.EMPLOYEE_NAME, Source.COST_CENTER, Source.MANUFACTURER, 
		Source.MODEL, Source.SERIES, Source.BODY_TYPE, Source.COLOR, Source.CHASIS_NUMBER, Source.ENGINE_NUMBER,
		Source.VEHICLE_TYPE, Source.VEHICLE_USAGE, Source.PO_NUMBER, Source.PO_LINE, Source.BASE_TOWN, 
		MONTH(Source.CREATED_DATE), YEAR(Source.CREATED_DATE), Source.CREATED_DATE, Source.MST_FLEET_ID);

END