USE [FMS]
GO

/****** Object:  View [PMI\ywicakso].[View_EPAF_CRF]    Script Date: 11/24/2017 10:55:51 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW View_EPAF_CRF
AS
SELECT 'RELOCATION' AS ACTION_TYPE, EMPLID, NAME AS NAME_FORMAL, COST_CENTER AS CC, EFFDT AS EFFDATE, GRADE_LVL AS GROUP_LEVEL, CITY, LOCATION_DESC AS BASETOWN, 'SYSTEM' AS LASTUPDOPRID
FROM   PSFT_GEN..SYSADM.PS_HMS_JOB_FLEET_VW AS PS_HMS_JOB_FLEET_VW_1
WHERE (ACTION = 'DTA') AND (ACTION_REASON_DESC LIKE 'Relocation%')

GO

