DROP TABLE [dbo].[MST_HOLIDAY_CALENDAR]
GO

CREATE TABLE [dbo].[MST_HOLIDAY_CALENDAR](
	[MST_HOLIDAY_ID] [int] IDENTITY(1,1) NOT NULL,
	[MST_HOLIDAY_DATE] [date] NOT NULL,
	[DESCRIPTION] [varchar](250) NOT NULL,
	[CREATED_BY] [nvarchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [nvarchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[IS_ACTIVE] [bit] NOT NULL,
 CONSTRAINT [PK_MST_HOLIDAY_CALENDAR] PRIMARY KEY CLUSTERED 
(
	[MST_HOLIDAY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


