ALTER TABLE [dbo].[VEHICLE_REPORT_DATA] ADD
	[MST_FLEET_ID] [bigint] NULL

ALTER TABLE [dbo].[CFM_IDLE_REPORT_DATA] ADD
	[MST_FLEET_ID] [bigint] NULL
	
ALTER TABLE [dbo].[FUEL_REPORT_DATA] ADD
	[MST_FLEET_ID] [bigint] NULL

ALTER TABLE [dbo].[NO_OF_VEHICLE_REPORT_DATA] ADD
	[REGION] [nvarchar](50) NULL
GO