BEGIN TRANSACTION
GO

CREATE TABLE dbo.Tmp_AUTO_GR
	(
	AUTO_GR_ID int NOT NULL IDENTITY (1, 1),
	PO_NUMBER varchar(20) NULL,
	PO_DATE datetime NULL,
	CREATED_DATE datetime NULL,
	IS_POSTED bit NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_AUTO_GR SET (LOCK_ESCALATION = TABLE)
GO
SET IDENTITY_INSERT dbo.Tmp_AUTO_GR ON
GO
IF EXISTS(SELECT * FROM dbo.AUTO_GR)
	 EXEC('INSERT INTO dbo.Tmp_AUTO_GR (AUTO_GR_ID, PO_NUMBER, PO_DATE, CREATED_DATE, IS_POSTED)
		SELECT AUTO_GR_ID, PO_NUMBER, PO_DATE, CREATED_DATE, IS_POSTED FROM dbo.AUTO_GR WITH (HOLDLOCK TABLOCKX)')
GO
SET IDENTITY_INSERT dbo.Tmp_AUTO_GR OFF
GO
DROP TABLE dbo.AUTO_GR
GO
EXECUTE sp_rename N'dbo.Tmp_AUTO_GR', N'AUTO_GR', 'OBJECT' 
GO
ALTER TABLE dbo.AUTO_GR ADD CONSTRAINT
	PK_AUTO_GR PRIMARY KEY CLUSTERED 
	(
	AUTO_GR_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
COMMIT


BEGIN TRANSACTION
GO
CREATE TABLE dbo.Tmp_AUTO_GR_DETAIL
	(
	AUTO_GR_DETAIL_ID int NOT NULL IDENTITY (1, 1),
	AUTO_GR_ID int NOT NULL,
	LINE_ITEM int NULL,
	QTY_ITEM decimal(18, 2) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_AUTO_GR_DETAIL SET (LOCK_ESCALATION = TABLE)
GO
SET IDENTITY_INSERT dbo.Tmp_AUTO_GR_DETAIL ON
GO
IF EXISTS(SELECT * FROM dbo.AUTO_GR_DETAIL)
	 EXEC('INSERT INTO dbo.Tmp_AUTO_GR_DETAIL (AUTO_GR_DETAIL_ID, AUTO_GR_ID, LINE_ITEM, QTY_ITEM)
		SELECT AUTO_GR_DETAIL_ID, AUTO_GR_ID, LINE_ITEM, QTY_ITEM FROM dbo.AUTO_GR_DETAIL WITH (HOLDLOCK TABLOCKX)')
GO
SET IDENTITY_INSERT dbo.Tmp_AUTO_GR_DETAIL OFF
GO
DROP TABLE dbo.AUTO_GR_DETAIL
GO
EXECUTE sp_rename N'dbo.Tmp_AUTO_GR_DETAIL', N'AUTO_GR_DETAIL', 'OBJECT' 
GO
ALTER TABLE dbo.AUTO_GR_DETAIL ADD CONSTRAINT
	PK_AUTO_GR_DETAIL PRIMARY KEY CLUSTERED 
	(
	AUTO_GR_DETAIL_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
COMMIT
