SET IDENTITY_INSERT [dbo].[MST_DOCUMENT_TYPE] ON 
INSERT [dbo].[MST_DOCUMENT_TYPE] ([MST_DOCUMENT_TYPE_ID], [DOCUMENT_TYPE], [DOCUMENT_INISIAL]) VALUES (8, N'EXTEND', N'EXT')
SET IDENTITY_INSERT [dbo].[MST_DOCUMENT_TYPE] OFF
