CREATE TABLE [dbo].[FUEL_COST_BY_FUNC_REPORT_DATA](
	[TOTAL_FUEL_COST] [decimal](18,2) NULL,
	[VEHICLE_TYPE] [nvarchar](50) NULL,
	[FUNCTION] [nvarchar](50) NULL,
	[REGION] [nvarchar](50) NULL,
	[REPORT_MONTH] [int] NULL,
	[REPORT_YEAR] [int] NULL,
	[CREATED_DATE] [datetime] NULL

)ON [PRIMARY]

GO