INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (33,'RptCfmIdle','~/RptCfmIdle','CFM Idle',1,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (34,'RptKpiMonitoring','~/RptKpiMonitoring','KPI Monitoring',1,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (35,'RptVehicle','~/RptVehicle','Vehicle',1,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (36,'RptFuel','~/RptFuel','Fuel',1,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (37,'RptPo','~/RptPo','PO',1,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (38,'RptAutoGr','~/RptAutoGr','Auto GR',1,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (39,'RptGs','~/RptGs','GS',1,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (40,'RptExecutiveSummary','~/RptExecutiveSummary','Executive Summary',1,'SYSTEM',GETDATE(),1);