ALTER TABLE MST_FLEET DROP COLUMN 
	PURPOSE, 
	TERMINATION_DATE,
	ACTUAL_GROUP,
	PRICE

ALTER TABLE MST_FLEET ADD 
	CERTIFICATE_OWNERSHIP nvarchar(50) null,
	COMMENTS nvarchar(255) null,
	ASSETS nvarchar(50) null,
	MONTHLY_HMS_INSTALLMENT DECIMAL(18,2) null,
	TOTAL_MONTHLY_CHARGE DECIMAL(18,2) null,
	VAT_DECIMAL DECIMAL(18,2) null

ALTER TABLE MST_EPAF 
	ADD GRADE_LEVEL INT NULL