CREATE TABLE [dbo].[VEHICLE_HISTORY_REPORT_DATA](
	[DATE] [date] NULL,
	[EMPLOYEE] [nvarchar](50) NULL,
	[DESCRIPTION] [nvarchar](MAX) NULL,
	[REPORT_MONTH] [int] NULL,
	[REPORT_YEAR] [int] NULL

) ON [PRIMARY]

GO