CREATE TABLE [dbo].[KPI_REPORT_DATA](
	[FORM_TYPE] [nvarchar](10) NULL,
	[EMPLOYEE_ID] [nvarchar](9) NULL,
	[EMPLOYEE_NAME] [nvarchar](100) NULL,
	[EFFECTIVE_DATE] [date] NULL,
	[REASON] [nvarchar](250) NULL,
	[ADDRESS] [nvarchar](250) NULL,
	[PREVIOUS_BASE_TOWN] [nvarchar](50) NULL,
	[NEW_BASE_TOWN] [nvarchar](50) NULL,
	[VEHICLE_USAGE] [nvarchar](50) NULL,
	[VEHICLE_GROUP_LEVEL] [int] NULL,
	[VEHICLE_MODEL] [nvarchar](50) NULL,
	[COLOR] [nvarchar](50) NULL,
	[POLICE_NUMBER] [nvarchar](50) NULL,
	[TEMPORARY_REQUEST_DATE] [date] NULL,
	[DAYS_DIFF_KPI_MEET] [int] NULL,
	[EE_RECEIVED_TEMP] [date] NULL,
	[DAYS_DIFF_EE_RECEIVED] [int] NULL,
	[SEND_TO_EMP_DATE] [date] NULL,
	[SEND_BACK_TO_HR] [date] NULL,
	[DAYS_DIFF_SEND_TO_HR] [int] NULL,
	[SEND_TO_FLEET_DATE] [date] NULL,
	[SEND_TO_EMPLOYEE_BENEFIT_DATE] [date] NULL,
	[SEND_SURAT_KUASA] [date] NULL,
	[DAYS_DIFF_SURAT_KUASA] [int] NULL,
	[SEND_AGREEMENT] [date] NULL,
	[DAYS_DIFF_AGREEMENT] [int] NULL,
	[REMARK] [nvarchar](250) NULL

)ON [PRIMARY]

GO