IF EXISTS(SELECT 1 FROM sys.procedures 
          WHERE Name = 'GetFuelData')
BEGIN
    DROP PROCEDURE [dbo].[GetFuelData]
END
GO
CREATE procedure [dbo].[GetFuelData]
AS BEGIN
	
	MERGE FUEL_REPORT_DATA AS Target
	USING (
		select t1.POLICE_NUMBER,SUM(t1.FUEL_AMOUNT) AS LITER,  MAX(t1.LAST_KM) AS ODOMETER, SUM(t1.COST) AS TOTAL_COST, 
		t1.FUEL_TYPE, t1.COST_CENTER, t1.VEHICLE_FUNCTION, t1.MANUFACTURER, t1.MODEL, t1.SERIES, t1.BODY_TYPE, t1.VEHICLE_TYPE, t1.VEHICLE_USAGE,
		t1.REPORT_MONTH, t1.REPORT_YEAR, t1.POSTED_TIME, t1.CITY,
		(SELECT MAX(d.REGION) FROM MST_LOCATION_MAPPING d WHERE upper(d.LOCATION) = upper(t1.CITY)) AS REGION,
		(SELECT MAX(c.BASETOWN) FROM MST_LOCATION_MAPPING c WHERE upper(c.LOCATION) = upper(t1.CITY)) AS LOCATION
		from (
		select a.Police_Number,a.FUEL_AMOUNT, a.LAST_KM, a.COST,
		b.FUEL_TYPE, b.COST_CENTER, b.VEHICLE_FUNCTION, b.MANUFACTURER, b.MODEL, b.SERIES, b.BODY_TYPE, b.VEHICLE_TYPE, b.VEHICLE_USAGE,
		MONTH(a.POSTED_TIME) AS REPORT_MONTH, YEAR(a.POSTED_TIME) AS REPORT_YEAR, a.POSTED_TIME, b.CITY
		from MST_FUEL_ODOMETER a left join MST_FLEET b ON a.Police_Number = b.Police_Number)t1
		group by t1.REPORT_MONTH, t1.POLICE_NUMBER,t1.FUEL_TYPE, t1.COST_CENTER, t1.VEHICLE_FUNCTION, t1.MANUFACTURER, t1.MODEL, t1.SERIES, t1.BODY_TYPE, t1.VEHICLE_TYPE, t1.VEHICLE_USAGE,
		t1.REPORT_MONTH, t1.REPORT_YEAR, t1.CITY, t1.POSTED_TIME
	) AS Source
	On (Target.POLICE_NUMBER = Source.POLICE_NUMBER
	AND Target.REPORT_MONTH = Source.REPORT_MONTH
	AND Target.REPORT_YEAR = Source.REPORT_YEAR
	AND Target.CREATED_DATE = Source.POSTED_TIME
	AND Target.COST_CENTER = Source.COST_CENTER
	AND Target.[FUNCTION] = Source.VEHICLE_FUNCTION
	AND Target.LOCATION = Source.LOCATION)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (POLICE_NUMBER, LITER, ODOMETER, COST, FUEL_TYPE, COST_CENTER, [FUNCTION], MANUFACTURER, MODEL, 
		SERIES, BODY_TYPE, VEHICLE_TYPE, VEHICLE_USAGE, LOCATION, REPORT_MONTH, REPORT_YEAR, CREATED_DATE, REGIONAL)
		VALUES( Source.POLICE_NUMBER, Source.LITER, Source.ODOMETER, Source.TOTAL_COST, Source.FUEL_TYPE, Source.COST_CENTER, 
		Source.VEHICLE_FUNCTION, Source.MANUFACTURER, Source.MODEL, Source.SERIES, Source.BODY_TYPE, Source.VEHICLE_TYPE, 
		Source.VEHICLE_USAGE, Source.LOCATION, REPORT_MONTH, REPORT_YEAR, Source.POSTED_TIME, Source.REGION)
	WHEN MATCHED THEN
	UPDATE SET POLICE_NUMBER = Source.POLICE_NUMBER,
			LITER = Source.LITER,
			ODOMETER = Source.ODOMETER,
			COST = Source.TOTAL_COST,
			FUEL_TYPE = Source.FUEL_TYPE,
			COST_CENTER = Source.COST_CENTER,
			[FUNCTION] = Source.VEHICLE_FUNCTION,
			MANUFACTURER = Source.MANUFACTURER,
			MODEL = Source.MODEL,
			SERIES = Source.SERIES,
			BODY_TYPE = Source.BODY_TYPE,
			VEHICLE_TYPE = Source.VEHICLE_TYPE,
			VEHICLE_USAGE = Source.VEHICLE_USAGE,
			LOCATION = Source.LOCATION,
			REPORT_MONTH = Source.REPORT_MONTH,
			REPORT_YEAR = Source.REPORT_YEAR,
			CREATED_DATE = Source.POSTED_TIME,
			REGIONAL = Source.REGION;
END