ALTER TABLE [dbo].[PO_REPORT_DATA] ADD
	EMPLOYEE_ID nvarchar(9) NULL FOREIGN KEY REFERENCES MST_EMPLOYEE(EMPLOYEE_ID);

ALTER TABLE [dbo].[TRA_CCF] ADD
	COORDINATOR_NAME nvarchar(50) NULL;

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (41,'RptCcf','~/RptCcf','CCF Report',1,'SYSTEM',GETDATE(),1);