ALTER TABLE VEHICLE_REPORT_DATA ADD
	CAR_GROUP_LEVEL INT NULL,
	VEHICLE_YEAR INT NULL,
	VEHICLE_USAGE NVARCHAR(50) NULL,
	PROJECT BIT NULL,
	PROJECT_NAME NVARCHAR(50) NULL,
	EMPLOYEE_GROUP_LEVEL INT NULL,
	ASSIGNED_TO NVARCHAR(50) NULL,
	ADDRESS TEXT NULL,
	START_DATE DATE NULL,
	END_DATE DATE NULL,
	CERTIFICATE_OF_OWNERSHIP NVARCHAR(50) NULL,
	COMMENTS NVARCHAR(255) NULL