CREATE TABLE [dbo].[NO_OF_WTC_VEHICLE_REPORT_DATA](
	[FUNCTION] [nvarchar](50) NULL,
	[NO_OF_VEHICLE] [int] NULL,
	[REGIONAL] [nvarchar](50) NULL,
	[REPORT_MONTH] [int] NULL,
	[REPORT_YEAR] [int] NULL,
	[CREATED_DATE] [datetime] NOT NULL

)ON [PRIMARY]

GO