CREATE TABLE [dbo].[SALES_BY_REGION_REPORT_DATA](
	[TOTAL_KM] [decimal](18,2) NULL,
	[TOTAL_COST] [decimal](18,2) NULL,
	[STICK] [decimal](18,2) NULL,
	[REPORT_MONTH] [int] NULL,
	[REPORT_YEAR] [int] NULL

)ON [PRIMARY]

GO