INSERT INTO MST_SYSACCESS(ROLE_NAME,ROLE_NAME_ALIAS,MODUL_ID,READ_ACCESS,WRITE_ACCESSS,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('ADMINISTRATOR','Administrator',1,1,1,'SYSTEM',GETDATE(),1)

INSERT INTO MST_SYSACCESS(ROLE_NAME,ROLE_NAME_ALIAS,MODUL_ID,READ_ACCESS,WRITE_ACCESSS,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('HR','HR',1,1,1,'SYSTEM',GETDATE(),1)

INSERT INTO MST_SYSACCESS(ROLE_NAME,ROLE_NAME_ALIAS,MODUL_ID,READ_ACCESS,WRITE_ACCESSS,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('FLEET','Fleet',1,1,1,'SYSTEM',GETDATE(),1)

INSERT INTO MST_SYSACCESS(ROLE_NAME,ROLE_NAME_ALIAS,MODUL_ID,READ_ACCESS,WRITE_ACCESSS,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('VIEWER','Viewer',1,1,0,'SYSTEM',GETDATE(),1)

INSERT INTO MST_SYSACCESS(ROLE_NAME,ROLE_NAME_ALIAS,MODUL_ID,READ_ACCESS,WRITE_ACCESSS,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('USER','User',1,1,0,'SYSTEM',GETDATE(),1)