CREATE TABLE [dbo].[SALES_BY_REGION_REPORT_DATA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TOTAL_KM] [decimal](18,2) NULL,
	[TOTAL_COST] [decimal](18,2) NULL,
	[STICK] [decimal](18,2) NULL,
	[REPORT_MONTH] [int] NULL,
	[REPORT_YEAR] [int] NULL,
	[CREATED_DATE] [datetime] NOT NULL,
CONSTRAINT [PK_SALES_BY_REGION_REPORT_DATA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

)ON [PRIMARY]

GO