CREATE TABLE [dbo].[NO_OF_VEHICLE_MAKE_TYPE_REPORT_DATA](
	[MANUFACTURER] [nvarchar](50) NULL,
	[BODY_TYPE] [nvarchar](50) NULL,
	[NO_OF_VEHICLE] [int] NULL,
	[REPORT_MONTH] [int] NULL,
	[REPORT_YEAR] [int] NULL,
	[CREATED_DATE] [datetime] NOT NULL

)ON [PRIMARY]

GO