

CREATE TABLE [dbo].[PO_REPORT_DATA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[POLICE_NUMBER] [nvarchar](50) NULL,
	[SUPPLY_METHOD] [nvarchar](50) NULL,
	[EMPLOYEE_NAME] [nvarchar](100) NULL,
	[COST_CENTER] [char](10) NULL,
	[MANUFACTURER] [nvarchar](50) NULL,
	[MODEL] [nvarchar](50) NULL,
	[SERIES] [nvarchar](50) NULL,
	[BODY_TYPE] [nvarchar](50) NULL,
	[COLOR] [nvarchar](50) NULL,
	[CHASIS_NUMBER] [nvarchar](50) NULL,
	[ENGINE_NUMBER] [nvarchar](50) NULL,
	[VEHICLE_TYPE] [nvarchar](50) NULL,
	[VEHICLE_USAGE] [nvarchar](50) NULL,
	[PO_NUMBER] [nvarchar](50) NULL,
	[PO_LINE] [nvarchar](50) NULL,
	[REPORT_MONTH] [int] NULL,
	[REPORT_YEAR] [int] NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MST_FLEET_ID] [bigint] NULL,
	[START_CONTRACT] [datetime] NULL,
	[END_CONTRACT] [datetime] NULL,
	[VENDOR] [nvarchar](100) NULL,
	[MONTHLY_INSTALLMENT] [decimal](18, 2) NULL,
	[GST] [decimal](18, 2) NULL,
	[TOTAL_MONTHLY_INSTALLMENT] [decimal](18, 2) NULL,
	[EMPLOYEE_ID] [nvarchar](9) NULL,
	[VEHICLE_FUNCTION] [nvarchar](50) NULL,
 CONSTRAINT [PK_PO_REPORT_DATA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[PO_REPORT_DATA]  WITH CHECK ADD FOREIGN KEY([EMPLOYEE_ID])
REFERENCES [dbo].[MST_EMPLOYEE] ([EMPLOYEE_ID])
GO


/****** Object:  StoredProcedure [dbo].[GetFuelCostData]    Script Date: 26/12/2017 10:24:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER procedure [dbo].[GetFuelCostData]
AS BEGIN

	MERGE FUEL_COST_BY_FUNC_REPORT_DATA AS Target
	USING (
		select SUM(FO.COST) AS TOTAL_FUEL_COST, FO.VEHICLE_TYPE, CC.FUNCTION_NAME, LM.REGION, 
		FO.DATE_OF_COST 
		FROM MST_FUEL_ODOMETER FO
		LEFT JOIN MST_EMPLOYEE E ON FO.EMPLOYEE_ID = E.EMPLOYEE_ID
		LEFT JOIN MST_FUNCTION_GROUP CC ON IIF(FO.VEHICLE_TYPE = 'BENEFIT', E.COST_CENTER, FO.COST_CENTER) = CC.COST_CENTER
		LEFT JOIN MST_LOCATION_MAPPING LM ON E.BASETOWN = LM.BASETOWN
		GROUP BY FO.VEHICLE_TYPE, CC.FUNCTION_NAME, LM.REGION, FO.DATE_OF_COST
	) AS Source
	
	On (Source.VEHICLE_TYPE = Target.VEHICLE_TYPE OR (Source.VEHICLE_TYPE IS NULL AND Target.VEHICLE_TYPE IS NULL))
	AND (Source.FUNCTION_NAME = Target.[FUNCTION] OR (Source.FUNCTION_NAME IS NULL AND Target.[FUNCTION] IS NULL))
	AND (Source.REGION = Target.REGION OR (Source.REGION IS NULL AND Target.REGION IS NULL))
	AND (Source.DATE_OF_COST = Target.CREATED_DATE)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (TOTAL_FUEL_COST, VEHICLE_TYPE, [FUNCTION], REGION, REPORT_MONTH, REPORT_YEAR, CREATED_DATE)
		VALUES( Source.TOTAL_FUEL_COST, Source.VEHICLE_TYPE, Source.FUNCTION_NAME, Source.REGION, 
		MONTH(Source.DATE_OF_COST), YEAR(Source.DATE_OF_COST), Source.DATE_OF_COST);

END

/****** Object:  StoredProcedure [dbo].[GetLeaseCostData]    Script Date: 26/12/2017 21:59:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER procedure [dbo].[GetLeaseCostData]
AS BEGIN

	MERGE LEASE_COST_BY_FUNC_REPORT_DATA AS Target
	USING (
		select VEHICLE_FUNCTION, SUM(TOTAL_MONTHLY_CHARGE) AS TOTAL_LEASE_COST, START_CONTRACT, REGIONAL FROM MST_FLEET
		WHERE (IS_ACTIVE = 1 )
		AND (PROJECT = 1)
		GROUP BY VEHICLE_FUNCTION, START_CONTRACT, REGIONAL
	) AS Source
	ON (Source.VEHICLE_FUNCTION = Target.[FUNCTION] OR (Source.VEHICLE_FUNCTION IS NULL AND Target.[FUNCTION] IS NULL))
	AND (Source.START_CONTRACT = Target.CREATED_DATE)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT ([FUNCTION], TOTAL_LEASE_COST, REPORT_MONTH, REPORT_YEAR, CREATED_DATE, REGION)
		VALUES( Source.VEHICLE_FUNCTION, Source.TOTAL_LEASE_COST, MONTH(Source.START_CONTRACT), 
		YEAR(Source.START_CONTRACT), Source.START_CONTRACT, Source.REGIONAL);

END
