
--CSF EPAF reason
INSERT INTO [dbo].[MST_REASON]([DOCUMENT_TYPE],[REASON],[IS_PENALTY],[CREATED_BY],[CREATED_DATE],[IS_ACTIVE])
     VALUES(1,'Hire',0,'SYSTEM',CURRENT_TIMESTAMP,1);
INSERT INTO [dbo].[MST_REASON]([DOCUMENT_TYPE],[REASON],[IS_PENALTY],[CREATED_BY],[CREATED_DATE],[IS_ACTIVE])
     VALUES(1,'Rehire',0,'SYSTEM',CURRENT_TIMESTAMP,1);
INSERT INTO [dbo].[MST_REASON]([DOCUMENT_TYPE],[REASON],[IS_PENALTY],[CREATED_BY],[CREATED_DATE],[IS_ACTIVE])
     VALUES(1,'Promotion',0,'SYSTEM',CURRENT_TIMESTAMP,1);
INSERT INTO [dbo].[MST_REASON]([DOCUMENT_TYPE],[REASON],[IS_PENALTY],[CREATED_BY],[CREATED_DATE],[IS_ACTIVE])
     VALUES(1,'STA',0,'SYSTEM',CURRENT_TIMESTAMP,1);
INSERT INTO [dbo].[MST_REASON]([DOCUMENT_TYPE],[REASON],[IS_PENALTY],[CREATED_BY],[CREATED_DATE],[IS_ACTIVE])
     VALUES(1,'IA',0,'SYSTEM',CURRENT_TIMESTAMP,1);


--CTF EPAF reason
INSERT INTO [dbo].[MST_REASON]([DOCUMENT_TYPE],[REASON],[IS_PENALTY],[CREATED_BY],[CREATED_DATE],[IS_ACTIVE])
     VALUES(6,'Terminate by Company',0,'SYSTEM',CURRENT_TIMESTAMP,1);
INSERT INTO [dbo].[MST_REASON]([DOCUMENT_TYPE],[REASON],[IS_PENALTY],[CREATED_BY],[CREATED_DATE],[IS_ACTIVE])
     VALUES(6,'STA Out',0,'SYSTEM',CURRENT_TIMESTAMP,1);
INSERT INTO [dbo].[MST_REASON]([DOCUMENT_TYPE],[REASON],[IS_PENALTY],[CREATED_BY],[CREATED_DATE],[IS_ACTIVE])
     VALUES(6,'IA Out',0,'SYSTEM',CURRENT_TIMESTAMP,1);
INSERT INTO [dbo].[MST_REASON]([DOCUMENT_TYPE],[REASON],[IS_PENALTY],[CREATED_BY],[CREATED_DATE],[IS_ACTIVE])
     VALUES(6,'Promotion',0,'SYSTEM',CURRENT_TIMESTAMP,1);


