
INSERT INTO MST_SYSACCESS(ROLE_NAME,ROLE_NAME_ALIAS,MODUL_ID,READ_ACCESS,WRITE_ACCESSS,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('COM. FINANCE MANAGER','ComFinanceManager',1,1,1,'SYSTEM',GETDATE(),1)

INSERT INTO MST_SYSACCESS(ROLE_NAME,ROLE_NAME_ALIAS,MODUL_ID,READ_ACCESS,WRITE_ACCESSS,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('OPS. FINANCE MANAGER','OpsFinanceManager',1,1,1,'SYSTEM',GETDATE(),1)

INSERT INTO MST_SYSACCESS(ROLE_NAME,ROLE_NAME_ALIAS,MODUL_ID,READ_ACCESS,WRITE_ACCESSS,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('RDE/MRD LOGISTIC','Logistic',1,1,1,'SYSTEM',GETDATE(),1)

INSERT INTO MST_SYSACCESS(ROLE_NAME,ROLE_NAME_ALIAS,MODUL_ID,READ_ACCESS,WRITE_ACCESSS,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('LOGISTIC  & DIST. MANAGER','LDManager',1,1,1,'SYSTEM',GETDATE(),1)

INSERT INTO MST_SYSACCESS(ROLE_NAME,ROLE_NAME_ALIAS,MODUL_ID,READ_ACCESS,WRITE_ACCESSS,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('FLEET SPV','Fleet',1,1,1,'SYSTEM',GETDATE(),1)

INSERT INTO MST_SYSACCESS(ROLE_NAME,ROLE_NAME_ALIAS,MODUL_ID,READ_ACCESS,WRITE_ACCESSS,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('HR SPV','HR',1,1,1,'SYSTEM',GETDATE(),1)

INSERT INTO MST_SYSACCESS(ROLE_NAME,ROLE_NAME_ALIAS,MODUL_ID,READ_ACCESS,WRITE_ACCESSS,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('FLEET MANAGER','FleetManager',1,1,1,'SYSTEM',GETDATE(),1)

INSERT INTO MST_SYSACCESS(ROLE_NAME,ROLE_NAME_ALIAS,MODUL_ID,READ_ACCESS,WRITE_ACCESSS,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('FLEET STAFF','Fleet',1,1,1,'SYSTEM',GETDATE(),1)

INSERT INTO MST_SYSACCESS(ROLE_NAME,ROLE_NAME_ALIAS,MODUL_ID,READ_ACCESS,WRITE_ACCESSS,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('HR MANAGER','HRManager',1,1,1,'SYSTEM',GETDATE(),1)

INSERT INTO MST_SYSACCESS(ROLE_NAME,ROLE_NAME_ALIAS,MODUL_ID,READ_ACCESS,WRITE_ACCESSS,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('FINANCE ZONE','FinanceZone',1,1,1,'SYSTEM',GETDATE(),1)

INSERT INTO MST_SYSACCESS(ROLE_NAME,ROLE_NAME_ALIAS,MODUL_ID,READ_ACCESS,WRITE_ACCESSS,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('EHS','EHS',1,1,1,'SYSTEM',GETDATE(),1)
