DECLARE @ID int;

--insert first data for home
INSERT INTO MST_MODUL(MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES ('Home','~/Home','Home',NULL,'SYSTEM',GETDATE(),1)

SELECT @ID = MST_MODUL_ID FROM MST_MODUL WHERE MODUL_NAME = 'Home'

--insert first data for master
INSERT INTO MST_MODUL(MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES ('MasterData','~/Home','Master Data',@ID,'SYSTEM',GETDATE(),1)

SELECT @ID = MST_MODUL_ID FROM MST_MODUL WHERE MODUL_NAME = 'MasterData'

INSERT INTO MST_MODUL(MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES ('MasterEmployee','~/MstEmployee','Master Employee',@ID,'SYSTEM',GETDATE(),1)

INSERT INTO MST_MODUL(MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES ('MasterFleet','~/MstFleet','Master Fleet',@ID,'SYSTEM',GETDATE(),1)

INSERT INTO MST_MODUL(MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES ('MasterComplaintCategory','~/MstComplaint','Master Complaint Category',@ID,'SYSTEM',GETDATE(),1)

INSERT INTO MST_MODUL(MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES ('MasterPriceList','~/MstPriceList','Master Price List',@ID,'SYSTEM',GETDATE(),1)

INSERT INTO MST_MODUL(MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES ('MasterVendor','~/MstVendor','Master Vendor',@ID,'SYSTEM',GETDATE(),1)

INSERT INTO MST_MODUL(MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES ('MasterSetting','~/MstSetting','Master Setting',@ID,'SYSTEM',GETDATE(),1)

INSERT INTO MST_MODUL(MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES ('MasterEpaf','~/MstEpaf','Master Epaf',@ID,'SYSTEM',GETDATE(),1)

INSERT INTO MST_MODUL(MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES ('MasterPenalty','~/MstPenalty','Master Penalty',@ID,'SYSTEM',GETDATE(),1)

INSERT INTO MST_MODUL(MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES ('MasterGroupCostCenter','~/MstGroupCostCenter','Master Group Cost Center',@ID,'SYSTEM',GETDATE(),1)

INSERT INTO MST_MODUL(MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES ('MasterHoliday','~/MstHolidayCalender','Master Holiday',@ID,'SYSTEM',GETDATE(),1)

INSERT INTO MST_MODUL(MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES ('MasterReason','~/MstReason','Master Reason',@ID,'SYSTEM',GETDATE(),1)

INSERT INTO MST_MODUL(MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES ('MasterFuelOdoMeter','~/MstFuelOdometer','Master Fuel Odometer',@ID,'SYSTEM',GETDATE(),1)

INSERT INTO MST_MODUL(MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES ('MasterVehicleSpect','~/MstVehicleSpect','Master Vehicle Spect',@ID,'SYSTEM',GETDATE(),1)

INSERT INTO MST_MODUL(MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES ('MasterLocationMapping','~/MstLocationMapping','Master Location Mapping',@ID,'SYSTEM',GETDATE(),1)

INSERT INTO MST_MODUL(MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES ('MasterCostOB','~/MstCostOB','Master Cost OB',@ID,'SYSTEM',GETDATE(),1)

INSERT INTO MST_MODUL(MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES ('MasterGS','~/MstGS','Master GS',@ID,'SYSTEM',GETDATE(),1)

INSERT INTO MST_MODUL(MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES ('MasterSalesVolume','~/MstSalesVolume','Master Sales Volume',@ID,'SYSTEM',GETDATE(),1)

INSERT INTO MST_MODUL(MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES ('MasterDelegation','~/MstDelegation','Master Delegation',@ID,'SYSTEM',GETDATE(),1)

INSERT INTO MST_MODUL(MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES ('MasterRemark','~/MstRemark','Master Remark',@ID,'SYSTEM',GETDATE(),1)

INSERT INTO MST_MODUL(MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES ('MasterSysAccess','~/MstSysAccess','Master SysAccess',@ID,'SYSTEM',GETDATE(),1)

INSERT INTO MST_MODUL(MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES ('MasterPenaltyLogic','~/MstPenaltyLogic','Master Penalty Logic',@ID,'SYSTEM',GETDATE(),1)