INSERT INTO MST_EMPLOYEE(EMPLOYEE_ID,FORMAL_NAME,POSITION_TITLE,DIVISON,DIRECTORATE,[ADDRESS],CITY,BASETOWN,COMPANY,COST_CENTER,GROUP_LEVEL,EMAIL_ADDRESS,FLEX_POINT,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('50493229','EMPLOYEE 50493229','Manager BP Operations','JYAHWBAWCGWXYCGDQAQZ','Human Resources','Jl. Permata II Lot BB-3,BB-4B,BB-7,BB-8A, Desa SukaluyuKec Teluk Jambe, Karawang International Industrial City','Karawang','Plant Karawang','HMS','3066762CIX',2,'email',0,'SYSTEM',GETDATE(),1)

INSERT INTO MST_EMPLOYEE(EMPLOYEE_ID,FORMAL_NAME,POSITION_TITLE,DIVISON,DIRECTORATE,[ADDRESS],CITY,BASETOWN,COMPANY,COST_CENTER,GROUP_LEVEL,EMAIL_ADDRESS,FLEX_POINT,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('80009015','EMPLOYEE 80009015','Manager BP Operations','JYAHWBAWCGWXYCGDQAQZ','Human Resources','Jl. Rungkut Industri Raya No. 18Kec. Rungkut','Surabaya','Office Rungkut I Surabaya','HMS','3066762CIX',1,'email',0,'SYSTEM',GETDATE(),1)

INSERT INTO MST_EMPLOYEE(EMPLOYEE_ID,FORMAL_NAME,POSITION_TITLE,DIVISON,DIRECTORATE,[ADDRESS],CITY,BASETOWN,COMPANY,COST_CENTER,GROUP_LEVEL,EMAIL_ADDRESS,FLEX_POINT,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('80427294','EMPLOYEE 80427294','Financial Analyst','EPUBEWIFDNPBOMEWZRJY','Sales','Jl. Rungkut Industri Raya No. 18Kec. Rungkut','Surabaya','Office Rungkut I Surabaya','HMS','3066410XAB',NULL,'email',0,'SYSTEM',GETDATE(),1)

INSERT INTO MST_EMPLOYEE(EMPLOYEE_ID,FORMAL_NAME,POSITION_TITLE,DIVISON,DIRECTORATE,[ADDRESS],CITY,BASETOWN,COMPANY,COST_CENTER,GROUP_LEVEL,EMAIL_ADDRESS,FLEX_POINT,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('50408656','EMPLOYEE 50408656','Manager HR OPEN+','GRGHABXMNEIAMMERAXDN','Human Resources','Jl. Rungkut Industri Raya No. 18Kec. Rungkut','Surabaya','Office Rungkut I Surabaya','HMS','3066762HIX',2,'email',0,'SYSTEM',GETDATE(),1)

INSERT INTO MST_EMPLOYEE(EMPLOYEE_ID,FORMAL_NAME,POSITION_TITLE,DIVISON,DIRECTORATE,[ADDRESS],CITY,BASETOWN,COMPANY,COST_CENTER,GROUP_LEVEL,EMAIL_ADDRESS,FLEX_POINT,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('80011729','EMPLOYEE 80011729','Excise Executive','UCCHCZUXZMHIMPNCKIWE','Operations','Jl. Rungkut Industri Raya No. 18Kec. Rungkut','Surabaya','Office Rungkut I Surabaya','HMS','3066302GEX',NULL,'email',0,'SYSTEM',GETDATE(),1)

INSERT INTO MST_EMPLOYEE(EMPLOYEE_ID,FORMAL_NAME,POSITION_TITLE,DIVISON,DIRECTORATE,[ADDRESS],CITY,BASETOWN,COMPANY,COST_CENTER,GROUP_LEVEL,EMAIL_ADDRESS,FLEX_POINT,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('50418088','EMPLOYEE 50418088','Spv Area Mkt Multi Tasking','ZDVZJFGDYHOUYYJKIQJR','Sales','Jl. Made Sabara II No. 1Kel. Korumba, Kec. Mandonga','Kendari','Area Kendari','HMS','3066550JGG',NULL,'email',0,'SYSTEM',GETDATE(),1)

INSERT INTO MST_EMPLOYEE(EMPLOYEE_ID,FORMAL_NAME,POSITION_TITLE,DIVISON,DIRECTORATE,[ADDRESS],CITY,BASETOWN,COMPANY,COST_CENTER,GROUP_LEVEL,EMAIL_ADDRESS,FLEX_POINT,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('80425522','EMPLOYEE 80425522','Lead Operator','RKPTUVWCBYJLNWUUKMJW','Operations','Jl. Raya Surabaya-Malang Km. 51,4Kec. Sukorejo','Pasuruan','Plant Sukorejo','ATB','1670151BSC',NULL,'email',0,'SYSTEM',GETDATE(),1)

INSERT INTO MST_EMPLOYEE(EMPLOYEE_ID,FORMAL_NAME,POSITION_TITLE,DIVISON,DIRECTORATE,[ADDRESS],CITY,BASETOWN,COMPANY,COST_CENTER,GROUP_LEVEL,EMAIL_ADDRESS,FLEX_POINT,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('50408581','EMPLOYEE 50408581','Team Leader','FQQKNWGZUPQCFWZYFYMI','Operations','Jl. Raya Surabaya-Malang Km. 51,4Kec. Sukorejo','Pasuruan','Plant Sukorejo','HMS','3066320JFE',NULL,'email',0,'SYSTEM',GETDATE(),1)

INSERT INTO MST_EMPLOYEE(EMPLOYEE_ID,FORMAL_NAME,POSITION_TITLE,DIVISON,DIRECTORATE,[ADDRESS],CITY,BASETOWN,COMPANY,COST_CENTER,GROUP_LEVEL,EMAIL_ADDRESS,FLEX_POINT,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('50434183','EMPLOYEE 50434183','Manager Key Accounts','AYCXUJNFBELMLUEMBMIK','Sales','Jl. Jendral Sudirman Kav.52-53, Lot 3&5, 16th-20thOne Pacific Place, Sudirman Central Business District','Jakarta','Office OPP Jakarta','HMS','3066410YAA',1,'email',0,'SYSTEM',GETDATE(),1)