INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('VEHICLE_TYPE','BENEFIT', 'Benefit', 'SYSTEM', getdate(),1)
INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('VEHICLE_TYPE','WTC', 'WTC', 'SYSTEM', getdate(),1)

INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('VEHICLE_USAGE','COP', 'COP', 'SYSTEM', getdate(),1)
INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('VEHICLE_USAGE','CFM', 'CFM', 'SYSTEM', getdate(),1)

INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('VEHICLE_CATEGORY','AS_ENTITLED', 'As Entitled', 'SYSTEM', getdate(),1)
INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('VEHICLE_CATEGORY','FLEXY_BENEFIT', 'Flexy Benefit', 'SYSTEM', getdate(),1)

INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('PROJECT','PROJECT1', 'Project 1', 'SYSTEM', getdate(),1)
INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('PROJECT','PROJECT2', 'Project 2', 'SYSTEM', getdate(),1)

INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('SUPPLY_METHOD','LEASE', 'Lease', 'SYSTEM', getdate(),1)
INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('SUPPLY_METHOD','SERVICE', 'Service', 'SYSTEM', getdate(),1)

INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('STATUS_VEHICLE','ACTIVE', 'Active', 'SYSTEM', getdate(),1)
INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('STATUS_VEHICLE','CFM_IDLE', 'CFM Idle', 'SYSTEM', getdate(),1)

--FOR QAS
--INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
--VALUES('USER_ROLE','PMI ID UR 3066 OPS FMS ADMINISTRATOR QA IMDL', 'PMI ID UR 3066 OPS FMS ADMINISTRATOR QA IMDL', 'SYSTEM', getdate(),1)
--INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
--VALUES('USER_ROLE','PMI ID UR 3066 OPS FMS VIEWER QA IMDL', 'PMI ID UR 3066 OPS FMS VIEWER QA IMDL', 'SYSTEM', getdate(),1)
--INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
--VALUES('USER_ROLE','PMI ID UR 3066 OPS FMS HR QA IMDL', 'PMI ID UR 3066 OPS FMS HR QA IMDL', 'SYSTEM', getdate(),1)
--INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
--VALUES('USER_ROLE','PMI ID UR 3066 OPS FMS FLEET QA IMDL', 'PMI ID UR 3066 OPS FMS FLEET QA IMDL', 'SYSTEM', getdate(),1)





--FOR PRODUCTION
INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('USER_ROLE','PMI ID UR 3066 OPS FMS ADMINISTRATOR PRD IMDL', 'PMI ID UR 3066 OPS FMS ADMINISTRATOR PRD IMDL', 'SYSTEM', getdate(),1)
INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('USER_ROLE','PMI ID UR 3066 OPS FMS VIEWER PRD IMDL', 'PMI ID UR 3066 OPS FMS VIEWER PRD IMDL', 'SYSTEM', getdate(),1)
INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('USER_ROLE','PMI ID UR 3066 OPS FMS HR PRD IMDL', 'PMI ID UR 3066 OPS FMS HR PRD IMDL', 'SYSTEM', getdate(),1)
INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('USER_ROLE','PMI ID UR 3066 OPS FMS FLEET PRD IMDL', 'PMI ID UR 3066 OPS FMS FLEET PRD IMDL', 'SYSTEM', getdate(),1)
INSERT INTO MST_SETTING(SETTING_GROUP,SETTING_NAME,SETTING_VALUE,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES('USER_ROLE','PMI ID UR 3066 OPS FMS IS SUPPORT PRD IMDL', 'PMI ID UR 3066 OPS FMS FLEET PRD IMDL', 'SYSTEM', getdate(),1)

