INSERT INTO dbo.MST_FLEET(
POLICE_NUMBER, CHASIS_NUMBER, ENGINE_NUMBER, EMPLOYEE_ID, EMPLOYEE_NAME, 
GROUP_LEVEL, ASSIGNED_TO, COST_CENTER, VENDOR_NAME, MANUFACTURER, 
MODEL, SERIES,BODY_TYPE, COLOR, TRANSMISSION, 
CAR_GROUP_LEVEL, FUEL_TYPE, BRANDING, AIRBAG, VEHICLE_YEAR, 
VEHICLE_TYPE, VEHICLE_USAGE, SUPPLY_METHOD, CITY, ADDRESS, 
VAT_DECIMAL, RESTITUTION, START_DATE,END_DATE, PO_NUMBER, 
PO_LINE, START_CONTRACT, END_CONTRACT, MONTHLY_HMS_INSTALLMENT, VEHICLE_STATUS, 
CERTIFICATE_OWNERSHIP, COMMENTS, ASSETS,TOTAL_MONTHLY_CHARGE,VEHICLE_FUNCTION,
REGIONAL, CREATED_BY, CREATED_DATE, IS_ACTIVE,VAT
)
SELECT [MASTER DATA FLEET],F2,F3,F4,F5,
		F6,F8,F9,F10,F11,
		F12,F13,F14,F15,F16,
		F17,F18,F19,IIF(F20 = 'Yes',1,0),F21,
		F22,F23,F24,F25,F26,
		F28,IIF(F29 = 'Yes',1,0),F30,F31,F33,
		F34,F35,F36,F37,1,
		F39,F40,F41,F42,F43,
		F44,SYSTEM_USER,SYSDATETIME(),1,IIF(F28>0,1,0)
FROM OPENROWSET('Microsoft.ACE.OLEDB.12.0',
                       'Excel 8.0;Database=\\PMIIDSUBDEV41\SSISFiles$\FMS\Template & Data - Master Data Fleet - sent.xlsx;', 
                       'SELECT * FROM [Data$]')
WHERE F3 IN (SELECT dbo.MST_EMPLOYEE.EMPLOYEE_ID FROM dbo.MST_EMPLOYEE)