Create procedure [dbo].[FixGetNoOfVehicleMakeType]
AS BEGIN

	MERGE NO_OF_VEHICLE_MAKE_TYPE_REPORT_DATA AS Target
	USING (
		select MANUFACTURER, BODY_TYPE, COUNT(CHASIS_NUMBER) AS NO_OF_VEHICLE, 
		MONTH(START_CONTRACT) AS REPORT_MONTH, YEAR(START_CONTRACT) AS REPORT_YEAR, START_CONTRACT FROM MST_FLEET
		WHERE
		(
			(START_CONTRACT < '2018-01-31')
			AND 
			(
				IIF(END_DATE = null, MONTH(END_CONTRACT), MONTH(END_DATE)) >=1 
				AND (YEAR(END_CONTRACT) >= 2018)
			)
		)
		GROUP BY MANUFACTURER, BODY_TYPE, START_CONTRACT
	) AS Source
	On (Source.MANUFACTURER = Target.MANUFACTURER OR (Source.MANUFACTURER IS NULL AND Target.MANUFACTURER IS NULL))
	AND (Source.BODY_TYPE = Target.BODY_TYPE OR (Source.BODY_TYPE IS NULL AND Target.BODY_TYPE IS NULL))
	AND (Source.START_CONTRACT = Target.CREATED_DATE)
	AND (1 = Target.REPORT_MONTH)
	AND (2018 = Target.REPORT_YEAR)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (MANUFACTURER, BODY_TYPE, NO_OF_VEHICLE, REPORT_MONTH, REPORT_YEAR, CREATED_DATE)
		VALUES( Source.MANUFACTURER, Source.BODY_TYPE, Source.NO_OF_VEHICLE, 1, 
		2018, Source.START_CONTRACT)
	WHEN MATCHED THEN
		UPDATE SET
		NO_OF_VEHICLE = Source.NO_OF_VEHICLE;

	MERGE NO_OF_VEHICLE_MAKE_TYPE_REPORT_DATA AS Target
	USING (
		select MANUFACTURER, BODY_TYPE, COUNT(CHASIS_NUMBER) AS NO_OF_VEHICLE, 
		MONTH(START_CONTRACT) AS REPORT_MONTH, YEAR(START_CONTRACT) AS REPORT_YEAR, START_CONTRACT FROM MST_FLEET
		WHERE
		(
			(START_CONTRACT < '2018-03-01')
			AND 
			(
				IIF(END_DATE = null, MONTH(END_CONTRACT), MONTH(END_DATE)) >=2
				AND (YEAR(END_CONTRACT) >= 2018)
			)
		)
		GROUP BY MANUFACTURER, BODY_TYPE, START_CONTRACT
	) AS Source
	On (Source.MANUFACTURER = Target.MANUFACTURER OR (Source.MANUFACTURER IS NULL AND Target.MANUFACTURER IS NULL))
	AND (Source.BODY_TYPE = Target.BODY_TYPE OR (Source.BODY_TYPE IS NULL AND Target.BODY_TYPE IS NULL))
	AND (Source.START_CONTRACT = Target.CREATED_DATE)
	AND (2 = Target.REPORT_MONTH)
	AND (2018 = Target.REPORT_YEAR)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (MANUFACTURER, BODY_TYPE, NO_OF_VEHICLE, REPORT_MONTH, REPORT_YEAR, CREATED_DATE)
		VALUES( Source.MANUFACTURER, Source.BODY_TYPE, Source.NO_OF_VEHICLE, Source.REPORT_MONTH, 
		Source.REPORT_YEAR, Source.START_CONTRACT)
	WHEN MATCHED THEN
		UPDATE SET
		NO_OF_VEHICLE = Source.NO_OF_VEHICLE;

	MERGE NO_OF_VEHICLE_MAKE_TYPE_REPORT_DATA AS Target
	USING (
		select MANUFACTURER, BODY_TYPE, COUNT(CHASIS_NUMBER) AS NO_OF_VEHICLE, 
		MONTH(START_CONTRACT) AS REPORT_MONTH, YEAR(START_CONTRACT) AS REPORT_YEAR, START_CONTRACT FROM MST_FLEET
		WHERE
		(
			(START_CONTRACT < '2018-03-31')
			AND 
			(
				IIF(END_DATE = null, MONTH(END_CONTRACT), MONTH(END_DATE)) >=3 
				AND (YEAR(END_CONTRACT) >= 2018)
			)
		)
		GROUP BY MANUFACTURER, BODY_TYPE, START_CONTRACT
	) AS Source
	On (Source.MANUFACTURER = Target.MANUFACTURER OR (Source.MANUFACTURER IS NULL AND Target.MANUFACTURER IS NULL))
	AND (Source.BODY_TYPE = Target.BODY_TYPE OR (Source.BODY_TYPE IS NULL AND Target.BODY_TYPE IS NULL))
	AND (Source.START_CONTRACT = Target.CREATED_DATE)
	AND (3 = Target.REPORT_MONTH)
	AND (2018 = Target.REPORT_YEAR)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (MANUFACTURER, BODY_TYPE, NO_OF_VEHICLE, REPORT_MONTH, REPORT_YEAR, CREATED_DATE)
		VALUES( Source.MANUFACTURER, Source.BODY_TYPE, Source.NO_OF_VEHICLE, 3, 
		2018, Source.START_CONTRACT)
	WHEN MATCHED THEN
		UPDATE SET
		NO_OF_VEHICLE = Source.NO_OF_VEHICLE;

	MERGE NO_OF_VEHICLE_MAKE_TYPE_REPORT_DATA AS Target
	USING (
		select MANUFACTURER, BODY_TYPE, COUNT(CHASIS_NUMBER) AS NO_OF_VEHICLE, 
		MONTH(START_CONTRACT) AS REPORT_MONTH, YEAR(START_CONTRACT) AS REPORT_YEAR, START_CONTRACT FROM MST_FLEET
		WHERE
		(
			(START_CONTRACT < '2018-04-30')
			AND 
			(
				IIF(END_DATE = null, MONTH(END_CONTRACT), MONTH(END_DATE)) >=4
				AND (YEAR(END_CONTRACT) >= 2018)
			)
		)
		GROUP BY MANUFACTURER, BODY_TYPE, START_CONTRACT
	) AS Source
	On (Source.MANUFACTURER = Target.MANUFACTURER OR (Source.MANUFACTURER IS NULL AND Target.MANUFACTURER IS NULL))
	AND (Source.BODY_TYPE = Target.BODY_TYPE OR (Source.BODY_TYPE IS NULL AND Target.BODY_TYPE IS NULL))
	AND (Source.START_CONTRACT = Target.CREATED_DATE)
	AND (4 = Target.REPORT_MONTH)
	AND (2018 = Target.REPORT_YEAR)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (MANUFACTURER, BODY_TYPE, NO_OF_VEHICLE, REPORT_MONTH, REPORT_YEAR, CREATED_DATE)
		VALUES( Source.MANUFACTURER, Source.BODY_TYPE, Source.NO_OF_VEHICLE, 4, 
		2018, Source.START_CONTRACT)
	WHEN MATCHED THEN
		UPDATE SET
		NO_OF_VEHICLE = Source.NO_OF_VEHICLE;

	MERGE NO_OF_VEHICLE_MAKE_TYPE_REPORT_DATA AS Target
	USING (
		select MANUFACTURER, BODY_TYPE, COUNT(CHASIS_NUMBER) AS NO_OF_VEHICLE, 
		MONTH(START_CONTRACT) AS REPORT_MONTH, YEAR(START_CONTRACT) AS REPORT_YEAR, START_CONTRACT FROM MST_FLEET
		WHERE
		(
			(START_CONTRACT < '2018-05-31')
			AND 
			(
				IIF(END_DATE = null, MONTH(END_CONTRACT), MONTH(END_DATE)) >=5 
				AND (YEAR(END_CONTRACT) >= 2018)
			)
		)
		GROUP BY MANUFACTURER, BODY_TYPE, START_CONTRACT
	) AS Source
	On (Source.MANUFACTURER = Target.MANUFACTURER OR (Source.MANUFACTURER IS NULL AND Target.MANUFACTURER IS NULL))
	AND (Source.BODY_TYPE = Target.BODY_TYPE OR (Source.BODY_TYPE IS NULL AND Target.BODY_TYPE IS NULL))
	AND (Source.START_CONTRACT = Target.CREATED_DATE)
	AND (5 = Target.REPORT_MONTH)
	AND (2018 = Target.REPORT_YEAR)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (MANUFACTURER, BODY_TYPE, NO_OF_VEHICLE, REPORT_MONTH, REPORT_YEAR, CREATED_DATE)
		VALUES( Source.MANUFACTURER, Source.BODY_TYPE, Source.NO_OF_VEHICLE, 5, 
		2018, Source.START_CONTRACT)
	WHEN MATCHED THEN
		UPDATE SET
		NO_OF_VEHICLE = Source.NO_OF_VEHICLE;
		
	MERGE NO_OF_VEHICLE_MAKE_TYPE_REPORT_DATA AS Target
	USING (
		select MANUFACTURER, BODY_TYPE, COUNT(CHASIS_NUMBER) AS NO_OF_VEHICLE, 
		MONTH(START_CONTRACT) AS REPORT_MONTH, YEAR(START_CONTRACT) AS REPORT_YEAR, START_CONTRACT FROM MST_FLEET
		WHERE
		(
			(START_CONTRACT < '2018-06-30')
			AND 
			(
				IIF(END_DATE = null, MONTH(END_CONTRACT), MONTH(END_DATE)) >=6
				AND (YEAR(END_CONTRACT) >= 2018)
			)
		)
		GROUP BY MANUFACTURER, BODY_TYPE, START_CONTRACT
	) AS Source
	On (Source.MANUFACTURER = Target.MANUFACTURER OR (Source.MANUFACTURER IS NULL AND Target.MANUFACTURER IS NULL))
	AND (Source.BODY_TYPE = Target.BODY_TYPE OR (Source.BODY_TYPE IS NULL AND Target.BODY_TYPE IS NULL))
	AND (Source.START_CONTRACT = Target.CREATED_DATE)
	AND (6 = Target.REPORT_MONTH)
	AND (2018 = Target.REPORT_YEAR)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (MANUFACTURER, BODY_TYPE, NO_OF_VEHICLE, REPORT_MONTH, REPORT_YEAR, CREATED_DATE)
		VALUES( Source.MANUFACTURER, Source.BODY_TYPE, Source.NO_OF_VEHICLE, 6, 
		2018, Source.START_CONTRACT)
	WHEN MATCHED THEN
		UPDATE SET
		NO_OF_VEHICLE = Source.NO_OF_VEHICLE;

END