Create procedure [dbo].[FixGetNoOfWTCVehicle]
AS BEGIN

	MERGE NO_OF_WTC_VEHICLE_REPORT_DATA AS Target
	USING (
		select VEHICLE_FUNCTION, COUNT(CHASIS_NUMBER) AS NO_OF_VEHICLE, REGIONAL,
		MONTH(START_CONTRACT) AS REPORT_MONTH, YEAR(START_CONTRACT) AS REPORT_YEAR, START_CONTRACT FROM MST_FLEET
		WHERE 
		(
			(START_CONTRACT < '2018-01-31')
			AND 
			(
				IIF(END_DATE = null, MONTH(END_CONTRACT), MONTH(END_DATE)) >=1 
				AND (YEAR(END_CONTRACT) >= 2018)
			)
		)
		AND (VEHICLE_FUNCTION = 'SALES' OR VEHICLE_FUNCTION = 'MARKETING')
		AND (VEHICLE_TYPE = 'WTC')
		GROUP BY VEHICLE_FUNCTION, REGIONAL, START_CONTRACT
	) AS Source
	On (Source.VEHICLE_FUNCTION = Target.[FUNCTION] OR (Source.VEHICLE_FUNCTION IS NULL AND Target.[FUNCTION] IS NULL))
	AND (Source.REGIONAL = Target.REGIONAL OR (Source.REGIONAL IS NULL AND Target.REGIONAL IS NULL))
	AND (Source.START_CONTRACT = Target.CREATED_DATE)
	AND (1 = Target.REPORT_MONTH)
	AND (2018 = Target.REPORT_YEAR)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT ([FUNCTION], NO_OF_VEHICLE, REGIONAL, REPORT_MONTH, REPORT_YEAR, CREATED_DATE)
		VALUES( Source.VEHICLE_FUNCTION, Source.NO_OF_VEHICLE, Source.REGIONAL, Source.REPORT_MONTH, 
		Source.REPORT_YEAR, Source.START_CONTRACT)
	WHEN MATCHED THEN
		UPDATE SET
		NO_OF_VEHICLE = Source.NO_OF_VEHICLE;

	MERGE NO_OF_WTC_VEHICLE_REPORT_DATA AS Target
	USING (
		select VEHICLE_FUNCTION, COUNT(CHASIS_NUMBER) AS NO_OF_VEHICLE, REGIONAL,
		MONTH(START_CONTRACT) AS REPORT_MONTH, YEAR(START_CONTRACT) AS REPORT_YEAR, START_CONTRACT FROM MST_FLEET
		WHERE 
		(
			(START_CONTRACT < '2018-03-01')
			AND 
			(
				IIF(END_DATE = null, MONTH(END_CONTRACT), MONTH(END_DATE)) >=2 
				AND (YEAR(END_CONTRACT) >= 2018)
			)
		)
		AND (VEHICLE_FUNCTION = 'SALES' OR VEHICLE_FUNCTION = 'MARKETING')
		AND (VEHICLE_TYPE = 'WTC')
		GROUP BY VEHICLE_FUNCTION, REGIONAL, START_CONTRACT
	) AS Source
	On (Source.VEHICLE_FUNCTION = Target.[FUNCTION] OR (Source.VEHICLE_FUNCTION IS NULL AND Target.[FUNCTION] IS NULL))
	AND (Source.REGIONAL = Target.REGIONAL OR (Source.REGIONAL IS NULL AND Target.REGIONAL IS NULL))
	AND (Source.START_CONTRACT = Target.CREATED_DATE)
	AND (2 = Target.REPORT_MONTH)
	AND (2018 = Target.REPORT_YEAR)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT ([FUNCTION], NO_OF_VEHICLE, REGIONAL, REPORT_MONTH, REPORT_YEAR, CREATED_DATE)
		VALUES( Source.VEHICLE_FUNCTION, Source.NO_OF_VEHICLE, Source.REGIONAL, 2, 
		2018, Source.START_CONTRACT)
	WHEN MATCHED THEN
		UPDATE SET
		NO_OF_VEHICLE = Source.NO_OF_VEHICLE;

	MERGE NO_OF_WTC_VEHICLE_REPORT_DATA AS Target
	USING (
		select VEHICLE_FUNCTION, COUNT(CHASIS_NUMBER) AS NO_OF_VEHICLE, REGIONAL,
		MONTH(START_CONTRACT) AS REPORT_MONTH, YEAR(START_CONTRACT) AS REPORT_YEAR, START_CONTRACT FROM MST_FLEET
		WHERE 
		(
			(START_CONTRACT < '2018-03-31')
			AND 
			(
				IIF(END_DATE = null, MONTH(END_CONTRACT), MONTH(END_DATE)) >=3 
				AND (YEAR(END_CONTRACT) >= 2018)
			)
		)
		AND (VEHICLE_FUNCTION = 'SALES' OR VEHICLE_FUNCTION = 'MARKETING')
		AND (VEHICLE_TYPE = 'WTC')
		GROUP BY VEHICLE_FUNCTION, REGIONAL, START_CONTRACT
	) AS Source
	On (Source.VEHICLE_FUNCTION = Target.[FUNCTION] OR (Source.VEHICLE_FUNCTION IS NULL AND Target.[FUNCTION] IS NULL))
	AND (Source.REGIONAL = Target.REGIONAL OR (Source.REGIONAL IS NULL AND Target.REGIONAL IS NULL))
	AND (Source.START_CONTRACT = Target.CREATED_DATE)
	AND (3 = Target.REPORT_MONTH)
	AND (2018 = Target.REPORT_YEAR)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT ([FUNCTION], NO_OF_VEHICLE, REGIONAL, REPORT_MONTH, REPORT_YEAR, CREATED_DATE)
		VALUES( Source.VEHICLE_FUNCTION, Source.NO_OF_VEHICLE, Source.REGIONAL, 3, 
		2018, Source.START_CONTRACT)
	WHEN MATCHED THEN
		UPDATE SET
		NO_OF_VEHICLE = Source.NO_OF_VEHICLE;

	MERGE NO_OF_WTC_VEHICLE_REPORT_DATA AS Target
	USING (
		select VEHICLE_FUNCTION, COUNT(CHASIS_NUMBER) AS NO_OF_VEHICLE, REGIONAL,
		MONTH(START_CONTRACT) AS REPORT_MONTH, YEAR(START_CONTRACT) AS REPORT_YEAR, START_CONTRACT FROM MST_FLEET
		WHERE 
		(
			(START_CONTRACT < '2018-04-30')
			AND 
			(
				IIF(END_DATE = null, MONTH(END_CONTRACT), MONTH(END_DATE)) >=4 
				AND (YEAR(END_CONTRACT) >= 2018)
			)
		)
		AND (VEHICLE_FUNCTION = 'SALES' OR VEHICLE_FUNCTION = 'MARKETING')
		AND (VEHICLE_TYPE = 'WTC')
		GROUP BY VEHICLE_FUNCTION, REGIONAL, START_CONTRACT
	) AS Source
	On (Source.VEHICLE_FUNCTION = Target.[FUNCTION] OR (Source.VEHICLE_FUNCTION IS NULL AND Target.[FUNCTION] IS NULL))
	AND (Source.REGIONAL = Target.REGIONAL OR (Source.REGIONAL IS NULL AND Target.REGIONAL IS NULL))
	AND (Source.START_CONTRACT = Target.CREATED_DATE)
	AND (4 = Target.REPORT_MONTH)
	AND (2018 = Target.REPORT_YEAR)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT ([FUNCTION], NO_OF_VEHICLE, REGIONAL, REPORT_MONTH, REPORT_YEAR, CREATED_DATE)
		VALUES( Source.VEHICLE_FUNCTION, Source.NO_OF_VEHICLE, Source.REGIONAL, 4, 
		2018, Source.START_CONTRACT)
	WHEN MATCHED THEN
		UPDATE SET
		NO_OF_VEHICLE = Source.NO_OF_VEHICLE;

	MERGE NO_OF_WTC_VEHICLE_REPORT_DATA AS Target
	USING (
		select VEHICLE_FUNCTION, COUNT(CHASIS_NUMBER) AS NO_OF_VEHICLE, REGIONAL,
		MONTH(START_CONTRACT) AS REPORT_MONTH, YEAR(START_CONTRACT) AS REPORT_YEAR, START_CONTRACT FROM MST_FLEET
		WHERE 
		(
			(START_CONTRACT < '2018-05-31')
			AND 
			(
				IIF(END_DATE = null, MONTH(END_CONTRACT), MONTH(END_DATE)) >=5 
				AND (YEAR(END_CONTRACT) >= 2018)
			)
		)
		AND (VEHICLE_FUNCTION = 'SALES' OR VEHICLE_FUNCTION = 'MARKETING')
		AND (VEHICLE_TYPE = 'WTC')
		GROUP BY VEHICLE_FUNCTION, REGIONAL, START_CONTRACT
	) AS Source
	On (Source.VEHICLE_FUNCTION = Target.[FUNCTION] OR (Source.VEHICLE_FUNCTION IS NULL AND Target.[FUNCTION] IS NULL))
	AND (Source.REGIONAL = Target.REGIONAL OR (Source.REGIONAL IS NULL AND Target.REGIONAL IS NULL))
	AND (Source.START_CONTRACT = Target.CREATED_DATE)
	AND (5 = Target.REPORT_MONTH)
	AND (2018 = Target.REPORT_YEAR)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT ([FUNCTION], NO_OF_VEHICLE, REGIONAL, REPORT_MONTH, REPORT_YEAR, CREATED_DATE)
		VALUES( Source.VEHICLE_FUNCTION, Source.NO_OF_VEHICLE, Source.REGIONAL, 5, 
		2018, Source.START_CONTRACT)
	WHEN MATCHED THEN
		UPDATE SET
		NO_OF_VEHICLE = Source.NO_OF_VEHICLE;

	MERGE NO_OF_WTC_VEHICLE_REPORT_DATA AS Target
	USING (
		select VEHICLE_FUNCTION, COUNT(CHASIS_NUMBER) AS NO_OF_VEHICLE, REGIONAL,
		MONTH(START_CONTRACT) AS REPORT_MONTH, YEAR(START_CONTRACT) AS REPORT_YEAR, START_CONTRACT FROM MST_FLEET
		WHERE 
		(
			(START_CONTRACT < '2018-06-30')
			AND 
			(
				IIF(END_DATE = null, MONTH(END_CONTRACT), MONTH(END_DATE)) >=6 
				AND (YEAR(END_CONTRACT) >= 2018)
			)
		)
		AND (VEHICLE_FUNCTION = 'SALES' OR VEHICLE_FUNCTION = 'MARKETING')
		AND (VEHICLE_TYPE = 'WTC')
		GROUP BY VEHICLE_FUNCTION, REGIONAL, START_CONTRACT
	) AS Source
	On (Source.VEHICLE_FUNCTION = Target.[FUNCTION] OR (Source.VEHICLE_FUNCTION IS NULL AND Target.[FUNCTION] IS NULL))
	AND (Source.REGIONAL = Target.REGIONAL OR (Source.REGIONAL IS NULL AND Target.REGIONAL IS NULL))
	AND (Source.START_CONTRACT = Target.CREATED_DATE)
	AND (6 = Target.REPORT_MONTH)
	AND (2018 = Target.REPORT_YEAR)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT ([FUNCTION], NO_OF_VEHICLE, REGIONAL, REPORT_MONTH, REPORT_YEAR, CREATED_DATE)
		VALUES( Source.VEHICLE_FUNCTION, Source.NO_OF_VEHICLE, Source.REGIONAL, 6, 
		2018, Source.START_CONTRACT)
	WHEN MATCHED THEN
		UPDATE SET
		NO_OF_VEHICLE = Source.NO_OF_VEHICLE;
END