/****** Object:  StoredProcedure [dbo].[GetLeaseCostData]    Script Date: 26/12/2017 21:59:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
Create procedure [dbo].[FixLeaseCostData]
AS BEGIN
	--Untuk Bulan 1
	MERGE LEASE_COST_BY_FUNC_REPORT_DATA AS Target
	USING (
		select VEHICLE_FUNCTION, SUM(TOTAL_MONTHLY_CHARGE) AS TOTAL_LEASE_COST, MONTH(START_CONTRACT) As REPORT_MONTH
		, YEAR(START_CONTRACT) As REPORT_YEAR, START_CONTRACT, REGIONAL FROM MST_FLEET
		WHERE 
		(
			(START_CONTRACT < '2018-01-31')
			AND 
			(
				IIF(END_DATE = null, MONTH(END_CONTRACT), MONTH(END_DATE)) >=1 
				AND (YEAR(END_CONTRACT) >= 2018)
			)
		)
		AND (PROJECT = 1)
		GROUP BY VEHICLE_FUNCTION, REGIONAL, START_CONTRACT
	) AS Source
	ON (Source.VEHICLE_FUNCTION = Target.[FUNCTION] OR (Source.VEHICLE_FUNCTION IS NULL AND Target.[FUNCTION] IS NULL))
	AND (Source.REGIONAL = Target.REGION OR (Source.REGIONAL IS NULL AND Target.REGION IS NULL))
	AND (Source.START_CONTRACT = Target.CREATED_DATE)
	AND (1 = Target.REPORT_MONTH)
	AND (2018 = Target.REPORT_YEAR)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT ([FUNCTION], TOTAL_LEASE_COST, REPORT_MONTH, REPORT_YEAR, CREATED_DATE, REGION)
		VALUES( Source.VEHICLE_FUNCTION, Source.TOTAL_LEASE_COST, 1, 
		2018, Source.START_CONTRACT, Source.REGIONAL)
	WHEN MATCHED THEN
		UPDATE SET
		TOTAL_LEASE_COST = Source.TOTAL_LEASE_COST;

	MERGE LEASE_COST_BY_FUNC_REPORT_DATA AS Target
	USING (
		select VEHICLE_FUNCTION, SUM(TOTAL_MONTHLY_CHARGE) AS TOTAL_LEASE_COST, MONTH(START_CONTRACT) As REPORT_MONTH
		, YEAR(START_CONTRACT) As REPORT_YEAR, START_CONTRACT, REGIONAL FROM MST_FLEET
		WHERE 
		(
			(START_CONTRACT < '2018-03-01')
			AND 
			(
				IIF(END_DATE = null, MONTH(END_CONTRACT), MONTH(END_DATE)) >=2 
				AND (YEAR(END_CONTRACT) >= 2018)
			)
		)
		AND (PROJECT = 1)
		GROUP BY VEHICLE_FUNCTION, REGIONAL, START_CONTRACT
	) AS Source
	ON (Source.VEHICLE_FUNCTION = Target.[FUNCTION] OR (Source.VEHICLE_FUNCTION IS NULL AND Target.[FUNCTION] IS NULL))
	AND (Source.REGIONAL = Target.REGION OR (Source.REGIONAL IS NULL AND Target.REGION IS NULL))
	AND (Source.START_CONTRACT = Target.CREATED_DATE)
	AND (2 = Target.REPORT_MONTH)
	AND (2018 = Target.REPORT_YEAR)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT ([FUNCTION], TOTAL_LEASE_COST, REPORT_MONTH, REPORT_YEAR, CREATED_DATE, REGION)
		VALUES( Source.VEHICLE_FUNCTION, Source.TOTAL_LEASE_COST, 2, 
		2018, Source.START_CONTRACT, Source.REGIONAL)
	WHEN MATCHED THEN
		UPDATE SET
		TOTAL_LEASE_COST = Source.TOTAL_LEASE_COST;

	MERGE LEASE_COST_BY_FUNC_REPORT_DATA AS Target
	USING (
		select VEHICLE_FUNCTION, SUM(TOTAL_MONTHLY_CHARGE) AS TOTAL_LEASE_COST, MONTH(START_CONTRACT) As REPORT_MONTH
		, YEAR(START_CONTRACT) As REPORT_YEAR, START_CONTRACT, REGIONAL FROM MST_FLEET
		WHERE 
		(
			(START_CONTRACT < '2018-03-31')
			AND 
			(
				IIF(END_DATE = null, MONTH(END_CONTRACT), MONTH(END_DATE)) >=3 
				AND (YEAR(END_CONTRACT) >= 2018)
			)
		)
		AND (PROJECT = 1)
		GROUP BY VEHICLE_FUNCTION, REGIONAL, START_CONTRACT
	) AS Source
	ON (Source.VEHICLE_FUNCTION = Target.[FUNCTION] OR (Source.VEHICLE_FUNCTION IS NULL AND Target.[FUNCTION] IS NULL))
	AND (Source.REGIONAL = Target.REGION OR (Source.REGIONAL IS NULL AND Target.REGION IS NULL))
	AND (Source.START_CONTRACT = Target.CREATED_DATE)
	AND (3 = Target.REPORT_MONTH)
	AND (2018 = Target.REPORT_YEAR)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT ([FUNCTION], TOTAL_LEASE_COST, REPORT_MONTH, REPORT_YEAR, CREATED_DATE, REGION)
		VALUES( Source.VEHICLE_FUNCTION, Source.TOTAL_LEASE_COST, 3, 
		2018, Source.START_CONTRACT, Source.REGIONAL)
	WHEN MATCHED THEN
		UPDATE SET
		TOTAL_LEASE_COST = Source.TOTAL_LEASE_COST;

	MERGE LEASE_COST_BY_FUNC_REPORT_DATA AS Target
	USING (
		select VEHICLE_FUNCTION, SUM(TOTAL_MONTHLY_CHARGE) AS TOTAL_LEASE_COST, MONTH(START_CONTRACT) As REPORT_MONTH
		, YEAR(START_CONTRACT) As REPORT_YEAR, START_CONTRACT, REGIONAL FROM MST_FLEET
		WHERE 
		(
			(START_CONTRACT < '2018-04-30')
			AND 
			(
				IIF(END_DATE = null, MONTH(END_CONTRACT), MONTH(END_DATE)) >=4 
				AND (YEAR(END_CONTRACT) >= 2018)
			)
		)
		AND (PROJECT = 1)
		GROUP BY VEHICLE_FUNCTION, REGIONAL, START_CONTRACT
	) AS Source
	ON (Source.VEHICLE_FUNCTION = Target.[FUNCTION] OR (Source.VEHICLE_FUNCTION IS NULL AND Target.[FUNCTION] IS NULL))
	AND (Source.REGIONAL = Target.REGION OR (Source.REGIONAL IS NULL AND Target.REGION IS NULL))
	AND (Source.START_CONTRACT = Target.CREATED_DATE)
	AND (4 = Target.REPORT_MONTH)
	AND (2018 = Target.REPORT_YEAR)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT ([FUNCTION], TOTAL_LEASE_COST, REPORT_MONTH, REPORT_YEAR, CREATED_DATE, REGION)
		VALUES( Source.VEHICLE_FUNCTION, Source.TOTAL_LEASE_COST, 4, 
		2018, Source.START_CONTRACT, Source.REGIONAL)
	WHEN MATCHED THEN
		UPDATE SET
		TOTAL_LEASE_COST = Source.TOTAL_LEASE_COST;

	MERGE LEASE_COST_BY_FUNC_REPORT_DATA AS Target
	USING (
		select VEHICLE_FUNCTION, SUM(TOTAL_MONTHLY_CHARGE) AS TOTAL_LEASE_COST, MONTH(START_CONTRACT) As REPORT_MONTH
		, YEAR(START_CONTRACT) As REPORT_YEAR, START_CONTRACT, REGIONAL FROM MST_FLEET
		WHERE 
		(
			(START_CONTRACT < '2018-05-31')
			AND 
			(
				IIF(END_DATE = null, MONTH(END_CONTRACT), MONTH(END_DATE)) >=5 
				AND (YEAR(END_CONTRACT) >= 2018)
			)
		)
		AND (PROJECT = 1)
		GROUP BY VEHICLE_FUNCTION, REGIONAL, START_CONTRACT
	) AS Source
	ON (Source.VEHICLE_FUNCTION = Target.[FUNCTION] OR (Source.VEHICLE_FUNCTION IS NULL AND Target.[FUNCTION] IS NULL))
	AND (Source.REGIONAL = Target.REGION OR (Source.REGIONAL IS NULL AND Target.REGION IS NULL))
	AND (Source.START_CONTRACT = Target.CREATED_DATE)
	AND (5 = Target.REPORT_MONTH)
	AND (2018 = Target.REPORT_YEAR)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT ([FUNCTION], TOTAL_LEASE_COST, REPORT_MONTH, REPORT_YEAR, CREATED_DATE, REGION)
		VALUES( Source.VEHICLE_FUNCTION, Source.TOTAL_LEASE_COST, 5, 
		2018, Source.START_CONTRACT, Source.REGIONAL)
	WHEN MATCHED THEN
		UPDATE SET
		TOTAL_LEASE_COST = Source.TOTAL_LEASE_COST;

	MERGE LEASE_COST_BY_FUNC_REPORT_DATA AS Target
	USING (
		select VEHICLE_FUNCTION, SUM(TOTAL_MONTHLY_CHARGE) AS TOTAL_LEASE_COST, MONTH(START_CONTRACT) As REPORT_MONTH
		, YEAR(START_CONTRACT) As REPORT_YEAR, START_CONTRACT, REGIONAL FROM MST_FLEET
		WHERE 
		(
			(START_CONTRACT < '2018-06-30')
			AND 
			(
				IIF(END_DATE = null, MONTH(END_CONTRACT), MONTH(END_DATE)) >=6 
				AND (YEAR(END_CONTRACT) >= 2018)
			)
		)
		AND (PROJECT = 1)
		GROUP BY VEHICLE_FUNCTION, REGIONAL, START_CONTRACT
	) AS Source
	ON (Source.VEHICLE_FUNCTION = Target.[FUNCTION] OR (Source.VEHICLE_FUNCTION IS NULL AND Target.[FUNCTION] IS NULL))
	AND (Source.REGIONAL = Target.REGION OR (Source.REGIONAL IS NULL AND Target.REGION IS NULL))
	AND (Source.START_CONTRACT = Target.CREATED_DATE)
	AND (6 = Target.REPORT_MONTH)
	AND (2018 = Target.REPORT_YEAR)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT ([FUNCTION], TOTAL_LEASE_COST, REPORT_MONTH, REPORT_YEAR, CREATED_DATE, REGION)
		VALUES( Source.VEHICLE_FUNCTION, Source.TOTAL_LEASE_COST, 1, 
		2018, Source.START_CONTRACT, Source.REGIONAL)
	WHEN MATCHED THEN
		UPDATE SET
		TOTAL_LEASE_COST = Source.TOTAL_LEASE_COST;

END
