Create procedure [dbo].[FixGetNoOfVehicle]
AS BEGIN

	MERGE NO_OF_VEHICLE_REPORT_DATA AS Target
	USING (
		select VEHICLE_TYPE, SUPPLY_METHOD, VEHICLE_FUNCTION, COUNT(CHASIS_NUMBER) AS NO_OF_VEHICLE, 
		MONTH(START_CONTRACT) AS REPORT_MONTH, YEAR(START_CONTRACT) AS REPORT_YEAR, START_CONTRACT, REGIONAL FROM MST_FLEET
		WHERE 
		(
			(START_CONTRACT < '2018-01-31')
			AND 
			(
				IIF(END_DATE = null, MONTH(END_CONTRACT), MONTH(END_DATE)) >=1 
				AND (YEAR(END_CONTRACT) >= 2018)
			)
		)
		AND (SUPPLY_METHOD = 'Lease' OR SUPPLY_METHOD = 'Services' OR SUPPLY_METHOD = 'Temporary' OR SUPPLY_METHOD = 'Extend')
		GROUP BY VEHICLE_TYPE, SUPPLY_METHOD, VEHICLE_FUNCTION, START_CONTRACT, REGIONAL
	) AS Source
	ON (Source.VEHICLE_TYPE = Target.VEHICLE_TYPE OR (Source.VEHICLE_TYPE IS NULL AND Target.VEHICLE_TYPE IS NULL))
	AND (Source.SUPPLY_METHOD = Target.SUPPLY_METHOD OR (Source.SUPPLY_METHOD IS NULL AND Target.SUPPLY_METHOD IS NULL))
	AND (Source.VEHICLE_FUNCTION = Target.[FUNCTION] OR (Source.VEHICLE_FUNCTION IS NULL AND Target.[FUNCTION] IS NULL))
	AND (Source.REGIONAL = Target.REGION OR (Source.REGIONAL IS NULL AND Target.REGION IS NULL))
	AND (Source.START_CONTRACT = Target.CREATED_DATE)
	AND (1 = Target.REPORT_MONTH)
	AND (2018 = Target.REPORT_YEAR)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (VEHICLE_TYPE, SUPPLY_METHOD, [FUNCTION], NO_OF_VEHICLE, REPORT_MONTH, REPORT_YEAR, CREATED_DATE, REGION)
		VALUES( Source.VEHICLE_TYPE, Source.SUPPLY_METHOD, Source.VEHICLE_FUNCTION, Source.NO_OF_VEHICLE, 1, 
		2018, Source.START_CONTRACT, Source.REGIONAL)
	WHEN MATCHED THEN
		UPDATE SET
		NO_OF_VEHICLE = Source.NO_OF_VEHICLE;

	MERGE NO_OF_VEHICLE_REPORT_DATA AS Target
	USING (
		select VEHICLE_TYPE, SUPPLY_METHOD, VEHICLE_FUNCTION, COUNT(CHASIS_NUMBER) AS NO_OF_VEHICLE, 
		MONTH(START_CONTRACT) AS REPORT_MONTH, YEAR(START_CONTRACT) AS REPORT_YEAR, START_CONTRACT, REGIONAL FROM MST_FLEET
		WHERE 
		(
			(START_CONTRACT < '2018-03-01')
			AND 
			(
				IIF(END_DATE = null, MONTH(END_CONTRACT), MONTH(END_DATE)) >=2 
				AND (YEAR(END_CONTRACT) >= 2018)
			)
		)
		AND (SUPPLY_METHOD = 'Lease' OR SUPPLY_METHOD = 'Services' OR SUPPLY_METHOD = 'Temporary' OR SUPPLY_METHOD = 'Extend')
		GROUP BY VEHICLE_TYPE, SUPPLY_METHOD, VEHICLE_FUNCTION, START_CONTRACT, REGIONAL
	) AS Source
	ON (Source.VEHICLE_TYPE = Target.VEHICLE_TYPE OR (Source.VEHICLE_TYPE IS NULL AND Target.VEHICLE_TYPE IS NULL))
	AND (Source.SUPPLY_METHOD = Target.SUPPLY_METHOD OR (Source.SUPPLY_METHOD IS NULL AND Target.SUPPLY_METHOD IS NULL))
	AND (Source.VEHICLE_FUNCTION = Target.[FUNCTION] OR (Source.VEHICLE_FUNCTION IS NULL AND Target.[FUNCTION] IS NULL))
	AND (Source.REGIONAL = Target.REGION OR (Source.REGIONAL IS NULL AND Target.REGION IS NULL))
	AND (Source.START_CONTRACT = Target.CREATED_DATE)
	AND (2 = Target.REPORT_MONTH)
	AND (2018 = Target.REPORT_YEAR)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (VEHICLE_TYPE, SUPPLY_METHOD, [FUNCTION], NO_OF_VEHICLE, REPORT_MONTH, REPORT_YEAR, CREATED_DATE, REGION)
		VALUES( Source.VEHICLE_TYPE, Source.SUPPLY_METHOD, Source.VEHICLE_FUNCTION, Source.NO_OF_VEHICLE, 2, 
		2018, Source.START_CONTRACT, Source.REGIONAL)
	WHEN MATCHED THEN
		UPDATE SET
		NO_OF_VEHICLE = Source.NO_OF_VEHICLE;

	MERGE NO_OF_VEHICLE_REPORT_DATA AS Target
	USING (
		select VEHICLE_TYPE, SUPPLY_METHOD, VEHICLE_FUNCTION, COUNT(CHASIS_NUMBER) AS NO_OF_VEHICLE, 
		MONTH(START_CONTRACT) AS REPORT_MONTH, YEAR(START_CONTRACT) AS REPORT_YEAR, START_CONTRACT, REGIONAL FROM MST_FLEET
		WHERE 
		(
			(START_CONTRACT < '2018-03-31')
			AND 
			(
				IIF(END_DATE = null, MONTH(END_CONTRACT), MONTH(END_DATE)) >=3 
				AND (YEAR(END_CONTRACT) >= 2018)
			)
		)
		AND (SUPPLY_METHOD = 'Lease' OR SUPPLY_METHOD = 'Services' OR SUPPLY_METHOD = 'Temporary' OR SUPPLY_METHOD = 'Extend')
		GROUP BY VEHICLE_TYPE, SUPPLY_METHOD, VEHICLE_FUNCTION, START_CONTRACT, REGIONAL
	) AS Source
	ON (Source.VEHICLE_TYPE = Target.VEHICLE_TYPE OR (Source.VEHICLE_TYPE IS NULL AND Target.VEHICLE_TYPE IS NULL))
	AND (Source.SUPPLY_METHOD = Target.SUPPLY_METHOD OR (Source.SUPPLY_METHOD IS NULL AND Target.SUPPLY_METHOD IS NULL))
	AND (Source.VEHICLE_FUNCTION = Target.[FUNCTION] OR (Source.VEHICLE_FUNCTION IS NULL AND Target.[FUNCTION] IS NULL))
	AND (Source.REGIONAL = Target.REGION OR (Source.REGIONAL IS NULL AND Target.REGION IS NULL))
	AND (Source.START_CONTRACT = Target.CREATED_DATE)
	AND (3 = Target.REPORT_MONTH)
	AND (2018 = Target.REPORT_YEAR)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (VEHICLE_TYPE, SUPPLY_METHOD, [FUNCTION], NO_OF_VEHICLE, REPORT_MONTH, REPORT_YEAR, CREATED_DATE, REGION)
		VALUES( Source.VEHICLE_TYPE, Source.SUPPLY_METHOD, Source.VEHICLE_FUNCTION, Source.NO_OF_VEHICLE, 3, 
		2018, Source.START_CONTRACT, Source.REGIONAL)
	WHEN MATCHED THEN
		UPDATE SET
		NO_OF_VEHICLE = Source.NO_OF_VEHICLE;

	MERGE NO_OF_VEHICLE_REPORT_DATA AS Target
	USING (
		select VEHICLE_TYPE, SUPPLY_METHOD, VEHICLE_FUNCTION, COUNT(CHASIS_NUMBER) AS NO_OF_VEHICLE, 
		MONTH(START_CONTRACT) AS REPORT_MONTH, YEAR(START_CONTRACT) AS REPORT_YEAR, START_CONTRACT, REGIONAL FROM MST_FLEET
		WHERE 
		(
			(START_CONTRACT < '2018-04-30')
			AND 
			(
				IIF(END_DATE = null, MONTH(END_CONTRACT), MONTH(END_DATE)) >=4 
				AND (YEAR(END_CONTRACT) >= 2018)
			)
		)
		AND (SUPPLY_METHOD = 'Lease' OR SUPPLY_METHOD = 'Services' OR SUPPLY_METHOD = 'Temporary' OR SUPPLY_METHOD = 'Extend')
		GROUP BY VEHICLE_TYPE, SUPPLY_METHOD, VEHICLE_FUNCTION, START_CONTRACT, REGIONAL
	) AS Source
	ON (Source.VEHICLE_TYPE = Target.VEHICLE_TYPE OR (Source.VEHICLE_TYPE IS NULL AND Target.VEHICLE_TYPE IS NULL))
	AND (Source.SUPPLY_METHOD = Target.SUPPLY_METHOD OR (Source.SUPPLY_METHOD IS NULL AND Target.SUPPLY_METHOD IS NULL))
	AND (Source.VEHICLE_FUNCTION = Target.[FUNCTION] OR (Source.VEHICLE_FUNCTION IS NULL AND Target.[FUNCTION] IS NULL))
	AND (Source.REGIONAL = Target.REGION OR (Source.REGIONAL IS NULL AND Target.REGION IS NULL))
	AND (Source.START_CONTRACT = Target.CREATED_DATE)
	AND (4 = Target.REPORT_MONTH)
	AND (2018 = Target.REPORT_YEAR)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (VEHICLE_TYPE, SUPPLY_METHOD, [FUNCTION], NO_OF_VEHICLE, REPORT_MONTH, REPORT_YEAR, CREATED_DATE, REGION)
		VALUES( Source.VEHICLE_TYPE, Source.SUPPLY_METHOD, Source.VEHICLE_FUNCTION, Source.NO_OF_VEHICLE, 4, 
		2018, Source.START_CONTRACT, Source.REGIONAL)
	WHEN MATCHED THEN
		UPDATE SET
		NO_OF_VEHICLE = Source.NO_OF_VEHICLE;

	MERGE NO_OF_VEHICLE_REPORT_DATA AS Target
	USING (
		select VEHICLE_TYPE, SUPPLY_METHOD, VEHICLE_FUNCTION, COUNT(CHASIS_NUMBER) AS NO_OF_VEHICLE, 
		MONTH(START_CONTRACT) AS REPORT_MONTH, YEAR(START_CONTRACT) AS REPORT_YEAR, START_CONTRACT, REGIONAL FROM MST_FLEET
		WHERE 
		(
			(START_CONTRACT < '2018-05-31')
			AND 
			(
				IIF(END_DATE = null, MONTH(END_CONTRACT), MONTH(END_DATE)) >=5 
				AND (YEAR(END_CONTRACT) >= 2018)
			)
		)
		AND (SUPPLY_METHOD = 'Lease' OR SUPPLY_METHOD = 'Services' OR SUPPLY_METHOD = 'Temporary' OR SUPPLY_METHOD = 'Extend')
		GROUP BY VEHICLE_TYPE, SUPPLY_METHOD, VEHICLE_FUNCTION, START_CONTRACT, REGIONAL
	) AS Source
	ON (Source.VEHICLE_TYPE = Target.VEHICLE_TYPE OR (Source.VEHICLE_TYPE IS NULL AND Target.VEHICLE_TYPE IS NULL))
	AND (Source.SUPPLY_METHOD = Target.SUPPLY_METHOD OR (Source.SUPPLY_METHOD IS NULL AND Target.SUPPLY_METHOD IS NULL))
	AND (Source.VEHICLE_FUNCTION = Target.[FUNCTION] OR (Source.VEHICLE_FUNCTION IS NULL AND Target.[FUNCTION] IS NULL))
	AND (Source.REGIONAL = Target.REGION OR (Source.REGIONAL IS NULL AND Target.REGION IS NULL))
	AND (Source.START_CONTRACT = Target.CREATED_DATE)
	AND (5 = Target.REPORT_MONTH)
	AND (2018 = Target.REPORT_YEAR)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (VEHICLE_TYPE, SUPPLY_METHOD, [FUNCTION], NO_OF_VEHICLE, REPORT_MONTH, REPORT_YEAR, CREATED_DATE, REGION)
		VALUES( Source.VEHICLE_TYPE, Source.SUPPLY_METHOD, Source.VEHICLE_FUNCTION, Source.NO_OF_VEHICLE, 5, 
		2018, Source.START_CONTRACT, Source.REGIONAL)
	WHEN MATCHED THEN
		UPDATE SET
		NO_OF_VEHICLE = Source.NO_OF_VEHICLE;

	MERGE NO_OF_VEHICLE_REPORT_DATA AS Target
	USING (
		select VEHICLE_TYPE, SUPPLY_METHOD, VEHICLE_FUNCTION, COUNT(CHASIS_NUMBER) AS NO_OF_VEHICLE, 
		MONTH(START_CONTRACT) AS REPORT_MONTH, YEAR(START_CONTRACT) AS REPORT_YEAR, START_CONTRACT, REGIONAL FROM MST_FLEET
		WHERE 
		(
			(START_CONTRACT < '2018-06-30')
			AND 
			(
				IIF(END_DATE = null, MONTH(END_CONTRACT), MONTH(END_DATE)) >=6 
				AND (YEAR(END_CONTRACT) >= 2018)
			)
		)
		AND (SUPPLY_METHOD = 'Lease' OR SUPPLY_METHOD = 'Services' OR SUPPLY_METHOD = 'Temporary' OR SUPPLY_METHOD = 'Extend')
		GROUP BY VEHICLE_TYPE, SUPPLY_METHOD, VEHICLE_FUNCTION, START_CONTRACT, REGIONAL
	) AS Source
	ON (Source.VEHICLE_TYPE = Target.VEHICLE_TYPE OR (Source.VEHICLE_TYPE IS NULL AND Target.VEHICLE_TYPE IS NULL))
	AND (Source.SUPPLY_METHOD = Target.SUPPLY_METHOD OR (Source.SUPPLY_METHOD IS NULL AND Target.SUPPLY_METHOD IS NULL))
	AND (Source.VEHICLE_FUNCTION = Target.[FUNCTION] OR (Source.VEHICLE_FUNCTION IS NULL AND Target.[FUNCTION] IS NULL))
	AND (Source.REGIONAL = Target.REGION OR (Source.REGIONAL IS NULL AND Target.REGION IS NULL))
	AND (Source.START_CONTRACT = Target.CREATED_DATE)
	AND (6 = Target.REPORT_MONTH)
	AND (2018 = Target.REPORT_YEAR)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (VEHICLE_TYPE, SUPPLY_METHOD, [FUNCTION], NO_OF_VEHICLE, REPORT_MONTH, REPORT_YEAR, CREATED_DATE, REGION)
		VALUES( Source.VEHICLE_TYPE, Source.SUPPLY_METHOD, Source.VEHICLE_FUNCTION, Source.NO_OF_VEHICLE, 6, 
		2018, Source.START_CONTRACT, Source.REGIONAL)
	WHEN MATCHED THEN
		UPDATE SET
		NO_OF_VEHICLE = Source.NO_OF_VEHICLE;
END