use [FMS];

DECLARE @ID int;

delete from MST_MODUL;

--insert first data for home
INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (1,'Home','~/Home','Home',NULL,'SYSTEM',GETDATE(),1);

SELECT @ID = MST_MODUL_ID FROM MST_MODUL WHERE MODUL_NAME = 'Home';

--insert first data for master
INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (2,'MasterData','~/Home','Master Data',@ID,'SYSTEM',GETDATE(),1);

SELECT @ID = MST_MODUL_ID FROM MST_MODUL WHERE MODUL_NAME = 'MasterData';

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (3,'MasterEmployee','~/MstEmployee','Master Employee',@ID,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (4,'MasterFleet','~/MstFleet','Master Fleet',@ID,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (5,'MasterComplaintCategory','~/MstComplaint','Master Complaint Category',@ID,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (6,'MasterPriceList','~/MstPriceList','Master Price List',@ID,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (7,'MasterVendor','~/MstVendor','Master Vendor',@ID,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (8,'MasterSetting','~/MstSetting','Master Setting',@ID,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (9,'MasterEpaf','~/MstEpaf','Master Epaf',@ID,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (10,'MasterPenalty','~/MstPenalty','Master Penalty',@ID,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (11,'MasterGroupCostCenter','~/MstGroupCostCenter','Master Group Cost Center',@ID,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (12,'MasterHoliday','~/MstHolidayCalender','Master Holiday',@ID,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (13,'MasterReason','~/MstReason','Master Reason',@ID,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (14,'MasterFuelOdoMeter','~/MstFuelOdometer','Master Fuel Odometer',@ID,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (15,'MasterVehicleSpect','~/MstVehicleSpect','Master Vehicle Spect',@ID,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (16,'MasterLocationMapping','~/MstLocationMapping','Master Location Mapping',@ID,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (17,'MasterCostOB','~/MstCostOB','Master Cost OB',@ID,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (18,'MasterGS','~/MstGS','Master GS',@ID,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (19,'MasterSalesVolume','~/MstSalesVolume','Master Sales Volume',@ID,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (20,'MasterDelegation','~/MstDelegation','Master Delegation',@ID,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (21,'MasterRemark','~/MstRemark','Master Remark',@ID,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (22,'MasterSysAccess','~/MstSysAccess','Master SysAccess',@ID,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (23,'MasterPenaltyLogic','~/MstPenaltyLogic','Master Penalty Logic',@ID,'SYSTEM',GETDATE(),1);


INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (30,'Transaction','~/Transaction','Transaction',1,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (24,'TraCrf','~/TraCrf','Car Relocation Form',30,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (25,'TraCsf','~/TraCsf','Car Selection Form',30,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (26,'TraCtf','~/TraCtf','Car Termination Form',30,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (27,'TraTmp','~/TraTmp','Temporary Form',30,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (28,'TraCaf','~/TraCaf','Car Accident Form',30,'SYSTEM',GETDATE(),1);

INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (29,'TraCcf','~/TraCcf','Car Complaint Form',30,'SYSTEM',GETDATE(),1);



INSERT INTO MST_MODUL(MST_MODUL_ID,MODUL_NAME,MODUL_URL,MENU_NAME,PARENT_MODUL_ID,CREATED_BY,CREATED_DATE,IS_ACTIVE)
VALUES (31,'Login','~/Login','Login',NULL,'SYSTEM',GETDATE(),1);